{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "fullpanels",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.bylazar",
          "module": "panels",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.bylazar",
          "module": "opmodecontrol",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "telemetry",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "configurables",
          "version": {
            "requires": "0.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "themes",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "capture",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "limelightproxy",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "gamepad",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "field",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "docs",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "battery",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "utils",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-0.0.23.aar",
          "url": "fullpanels-0.0.23.aar",
          "size": 64542,
          "sha512": "736441be36ba9c611a64a7c84def0aac77e4afd8b9231b337372b0f3724f99aab69aaef7e45af50d154cec15366a696acfe382852edab40d50d776a72403ab41",
          "sha256": "a18244aaca2eceab54e59e62243a9ef2469396d3d3bebc206c693ca242b0866f",
          "sha1": "255f9f440b98ff526f9521047f294c6f64c53aac",
          "md5": "cd11b6a4b6605112513d68725025d27d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.bylazar",
          "module": "panels",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.bylazar",
          "module": "opmodecontrol",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "telemetry",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "configurables",
          "version": {
            "requires": "0.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "themes",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "capture",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "limelightproxy",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "gamepad",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "field",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "docs",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "battery",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "utils",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-0.0.23.aar",
          "url": "fullpanels-0.0.23.aar",
          "size": 64542,
          "sha512": "736441be36ba9c611a64a7c84def0aac77e4afd8b9231b337372b0f3724f99aab69aaef7e45af50d154cec15366a696acfe382852edab40d50d776a72403ab41",
          "sha256": "a18244aaca2eceab54e59e62243a9ef2469396d3d3bebc206c693ca242b0866f",
          "sha1": "255f9f440b98ff526f9521047f294c6f64c53aac",
          "md5": "cd11b6a4b6605112513d68725025d27d"
        }
      ]
    }
  ]
}
