{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "configurables",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-1.0.6.aar",
          "url": "configurables-1.0.6.aar",
          "size": 524100,
          "sha512": "007083a441f7e59c57eba9961e9344d43f9c9c95ecaf7efbf520042c7e92f44bf2283a6af0bc1bc217194e112d71e33bee891290333e1d74053dcc8240b44702",
          "sha256": "20f73f56b8721802f76b56b341aae1d33cdaddd5b2dbd0a5334c504adb81a80c",
          "sha1": "e5f0f64dc81c2bcb0301ca77c4d75227e2c0efe1",
          "md5": "8f63651c3b151858c7c6749d313e9d3c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-1.0.6.aar",
          "url": "configurables-1.0.6.aar",
          "size": 524100,
          "sha512": "007083a441f7e59c57eba9961e9344d43f9c9c95ecaf7efbf520042c7e92f44bf2283a6af0bc1bc217194e112d71e33bee891290333e1d74053dcc8240b44702",
          "sha256": "20f73f56b8721802f76b56b341aae1d33cdaddd5b2dbd0a5334c504adb81a80c",
          "sha1": "e5f0f64dc81c2bcb0301ca77c4d75227e2c0efe1",
          "md5": "8f63651c3b151858c7c6749d313e9d3c"
        }
      ]
    }
  ]
}
