{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "exampleplugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.1.aar",
          "url": "exampleplugin-0.0.1.aar",
          "size": 83560,
          "sha512": "af7d6b2daa35b77c5e77e3b3d7a3b7eff091ac239def61a4d6982d1f0345da5d1f867df1cb54bb80f90bfa4d726a59d325a38e34edac771ef4b5f3a8d6a6c723",
          "sha256": "e0373d93dcb480d2ba4d4ec51659fb7481c4e58f056038ab447439626a1d77ae",
          "sha1": "1d6dec226a23a470022ac574d5f50e6de1eddf20",
          "md5": "e8e5cc6ba4064d5c2670f93a903b5da1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.1.aar",
          "url": "exampleplugin-0.0.1.aar",
          "size": 83560,
          "sha512": "af7d6b2daa35b77c5e77e3b3d7a3b7eff091ac239def61a4d6982d1f0345da5d1f867df1cb54bb80f90bfa4d726a59d325a38e34edac771ef4b5f3a8d6a6c723",
          "sha256": "e0373d93dcb480d2ba4d4ec51659fb7481c4e58f056038ab447439626a1d77ae",
          "sha1": "1d6dec226a23a470022ac574d5f50e6de1eddf20",
          "md5": "e8e5cc6ba4064d5c2670f93a903b5da1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "exampleplugin-0.0.1-sources.jar",
          "url": "exampleplugin-0.0.1-sources.jar",
          "size": 2395,
          "sha512": "7a4f75a6fef9107d59c6e3dd9854dc940add8c74f8de8042c59f234f7462feb73ddfb79b796f608492740721b0cc2a18e6c6a497e8e261a63c2e6c358e23f47b",
          "sha256": "479368dfb6d53a183a44252c467a85b8676f75fca9b397b12c2d754aa4f2e0ac",
          "sha1": "c3589270cefa09f52b664674e3d9c420246663c6",
          "md5": "2f04927b41644e5ff03ca1abd39dae97"
        }
      ]
    }
  ]
}
