{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.22.aar",
          "url": "panels-0.0.22.aar",
          "size": 733272,
          "sha512": "41254b58aed36b817c338011167540bb9a2f2b277710528e5df67e6664cff137cb142f1edca94ab3f6d795c7bb6e793db419ba3ea84e8070deab11259e972cb2",
          "sha256": "51a53bd5c40045c56f17f9f8d7f3be44f0e1f34abe3783bca7dd118422ea9400",
          "sha1": "9df97524355149432f16d32b48a84464c060cd39",
          "md5": "300eaa6dbfca4539572b1b96901a6641"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.22.aar",
          "url": "panels-0.0.22.aar",
          "size": 733272,
          "sha512": "41254b58aed36b817c338011167540bb9a2f2b277710528e5df67e6664cff137cb142f1edca94ab3f6d795c7bb6e793db419ba3ea84e8070deab11259e972cb2",
          "sha256": "51a53bd5c40045c56f17f9f8d7f3be44f0e1f34abe3783bca7dd118422ea9400",
          "sha1": "9df97524355149432f16d32b48a84464c060cd39",
          "md5": "300eaa6dbfca4539572b1b96901a6641"
        }
      ]
    }
  ]
}
