{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "field",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.13.aar",
          "url": "field-0.0.13.aar",
          "size": 894036,
          "sha512": "4f036387d58dd2b6ce4c0506a2ec807c519b2a78edb76bcc43c4a761bf397c9a375ced056a49e6b520d2d6650112bb4af1eb12316d46da2b05f900b262f4ed32",
          "sha256": "4b830dc1df6a487d65c75dac41b98537cf7e5495919e8389a7cea06767ce8ec4",
          "sha1": "11a6b0e60da527edf7e75e4708a150c2873a857b",
          "md5": "a7c64adcca22f24d6e7dae954404586d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.13.aar",
          "url": "field-0.0.13.aar",
          "size": 894036,
          "sha512": "4f036387d58dd2b6ce4c0506a2ec807c519b2a78edb76bcc43c4a761bf397c9a375ced056a49e6b520d2d6650112bb4af1eb12316d46da2b05f900b262f4ed32",
          "sha256": "4b830dc1df6a487d65c75dac41b98537cf7e5495919e8389a7cea06767ce8ec4",
          "sha1": "11a6b0e60da527edf7e75e4708a150c2873a857b",
          "md5": "a7c64adcca22f24d6e7dae954404586d"
        }
      ]
    }
  ]
}
