{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.4.aar",
          "url": "panels-0.0.4.aar",
          "size": 262908,
          "sha512": "1fe63f1c53047b859228400faef3294980c25b93f511b6e40059d9c547cbafbf9d23154852252d68fe8c8cb73ce6e6d3167f135d7db62d0a2d6ac968de4a8fbd",
          "sha256": "c0e8227057c43f6021c6d8d21ebc4077bdefab30e7bf907469b669b5c3221a79",
          "sha1": "02049ea18a432809978c541ca486184a01ab4ab0",
          "md5": "7cb49b908a6801c5d0d07c8b5b279229"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.4.aar",
          "url": "panels-0.0.4.aar",
          "size": 262908,
          "sha512": "1fe63f1c53047b859228400faef3294980c25b93f511b6e40059d9c547cbafbf9d23154852252d68fe8c8cb73ce6e6d3167f135d7db62d0a2d6ac968de4a8fbd",
          "sha256": "c0e8227057c43f6021c6d8d21ebc4077bdefab30e7bf907469b669b5c3221a79",
          "sha1": "02049ea18a432809978c541ca486184a01ab4ab0",
          "md5": "7cb49b908a6801c5d0d07c8b5b279229"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "panels-0.0.4-sources.jar",
          "url": "panels-0.0.4-sources.jar",
          "size": 34595,
          "sha512": "d427e14ce13eb3b400d0e6bf758a34621e0f2f939996f5cffef802b418bd556dfe2df388460839bf2400570e11f61b2dc7380569d31d067f7729cbe4f6234df1",
          "sha256": "98fad9e0773791c116a1d5c8f7713976887feb30e83c38b49971e55ec34e727f",
          "sha1": "f700a3e540a1732b81f649e3df6d6f5950c85913",
          "md5": "f0e3e22ced54a96b4ae385dc04f60a18"
        }
      ]
    }
  ]
}
