{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.4.aar",
          "url": "panels-0.0.4.aar",
          "size": 262913,
          "sha512": "22f969b32d90f1de7b5ed7c34193b3bd5cd75e2a96d9d2c2d06fe5914abbc4ea151b222ba4d06b358adbeed7ee4862b5318fc64e8f89760d7f1cb9ef31c9122d",
          "sha256": "435988a9b8ae5694e711a9a016bcecda7c4889eb03e7b1571532a53055d3c564",
          "sha1": "e8ffa547df319d6de12e96f12eeb027e734535b5",
          "md5": "1787469b4015a3cefb7c4b5d94e14329"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.4.aar",
          "url": "panels-0.0.4.aar",
          "size": 262913,
          "sha512": "22f969b32d90f1de7b5ed7c34193b3bd5cd75e2a96d9d2c2d06fe5914abbc4ea151b222ba4d06b358adbeed7ee4862b5318fc64e8f89760d7f1cb9ef31c9122d",
          "sha256": "435988a9b8ae5694e711a9a016bcecda7c4889eb03e7b1571532a53055d3c564",
          "sha1": "e8ffa547df319d6de12e96f12eeb027e734535b5",
          "md5": "1787469b4015a3cefb7c4b5d94e14329"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "panels-0.0.4-sources.jar",
          "url": "panels-0.0.4-sources.jar",
          "size": 34595,
          "sha512": "d427e14ce13eb3b400d0e6bf758a34621e0f2f939996f5cffef802b418bd556dfe2df388460839bf2400570e11f61b2dc7380569d31d067f7729cbe4f6234df1",
          "sha256": "98fad9e0773791c116a1d5c8f7713976887feb30e83c38b49971e55ec34e727f",
          "sha1": "f700a3e540a1732b81f649e3df6d6f5950c85913",
          "md5": "f0e3e22ced54a96b4ae385dc04f60a18"
        }
      ]
    }
  ]
}
