{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "battery",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.3.aar",
          "url": "battery-0.0.3.aar",
          "size": 84936,
          "sha512": "ff6266a0697019bd19031123063cfe07873ce1ae8d01d5043938df9e4aa0bfc916b74bb0945a26192a0ba92b1af0b1995596e8202ea657272c529b09b515ff95",
          "sha256": "0cc2a00f5002808403e01e6cac4799d3885dc86724052a9b2eaf504a0acef61a",
          "sha1": "d313b0b91e3120cd73038f2b8d001446d5a0cc64",
          "md5": "d05b527bc664c49bb08a8943be978372"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.3.aar",
          "url": "battery-0.0.3.aar",
          "size": 84936,
          "sha512": "ff6266a0697019bd19031123063cfe07873ce1ae8d01d5043938df9e4aa0bfc916b74bb0945a26192a0ba92b1af0b1995596e8202ea657272c529b09b515ff95",
          "sha256": "0cc2a00f5002808403e01e6cac4799d3885dc86724052a9b2eaf504a0acef61a",
          "sha1": "d313b0b91e3120cd73038f2b8d001446d5a0cc64",
          "md5": "d05b527bc664c49bb08a8943be978372"
        }
      ]
    }
  ]
}
