{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "docs",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.4.aar",
          "url": "docs-0.0.4.aar",
          "size": 80807,
          "sha512": "b6390fc8c0a3a647c5f1cbf2e444b76b64655124508200b82c5985b1b3b7e4220bb4309225ad7c1d0017b01946bf2659b12c5881dfc257429da6b6f695958c03",
          "sha256": "4ab86cd09327841b33d7baf262c8813bf4014217f067602d2733302750d3c8d2",
          "sha1": "d29ddc290518adc2f42cb3c49d8bef6d15f1c42c",
          "md5": "a21af8b177f466ac09c91980b951b6a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.4.aar",
          "url": "docs-0.0.4.aar",
          "size": 80807,
          "sha512": "b6390fc8c0a3a647c5f1cbf2e444b76b64655124508200b82c5985b1b3b7e4220bb4309225ad7c1d0017b01946bf2659b12c5881dfc257429da6b6f695958c03",
          "sha256": "4ab86cd09327841b33d7baf262c8813bf4014217f067602d2733302750d3c8d2",
          "sha1": "d29ddc290518adc2f42cb3c49d8bef6d15f1c42c",
          "md5": "a21af8b177f466ac09c91980b951b6a0"
        }
      ]
    }
  ]
}
