{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "docs",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.5.aar",
          "url": "docs-0.0.5.aar",
          "size": 589815,
          "sha512": "bacd01ffc869cac0d614388e9a81aa62e37808e80441fce5fab7b40d52e95c9e535af936289acd47515009237fff2d8356b33ae44e90d0fa6945c907efa771ea",
          "sha256": "82a10b90f7f0ad1f1f9381977866db271841a8e88d82bdd2e76ec09a2e440cc2",
          "sha1": "3952e2c344e227853bf8cfdce70ca8652b014f96",
          "md5": "60063e65304db7089581b8bae88b2089"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.5.aar",
          "url": "docs-0.0.5.aar",
          "size": 589815,
          "sha512": "bacd01ffc869cac0d614388e9a81aa62e37808e80441fce5fab7b40d52e95c9e535af936289acd47515009237fff2d8356b33ae44e90d0fa6945c907efa771ea",
          "sha256": "82a10b90f7f0ad1f1f9381977866db271841a8e88d82bdd2e76ec09a2e440cc2",
          "sha1": "3952e2c344e227853bf8cfdce70ca8652b014f96",
          "md5": "60063e65304db7089581b8bae88b2089"
        }
      ]
    }
  ]
}
