{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "docs",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.5.aar",
          "url": "docs-0.0.5.aar",
          "size": 604059,
          "sha512": "b500c6c53d9f83a1e413cb24e05a0eade77e77020fd904f5b16f1188f5788a614ce1dd8d0a4aa568734384d16a2651a3ec5abc252436e71f56cfc10c48ffce37",
          "sha256": "d12e6ee1bf12b9266f6037e79684908d6ba60bc556e0dbf7bc41703b053ff1ac",
          "sha1": "544e5d71238b50e6b26ae99604c50db9cfdf4b9a",
          "md5": "592f9fd926e18ba373c93ac4e07b92b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.5.aar",
          "url": "docs-0.0.5.aar",
          "size": 604059,
          "sha512": "b500c6c53d9f83a1e413cb24e05a0eade77e77020fd904f5b16f1188f5788a614ce1dd8d0a4aa568734384d16a2651a3ec5abc252436e71f56cfc10c48ffce37",
          "sha256": "d12e6ee1bf12b9266f6037e79684908d6ba60bc556e0dbf7bc41703b053ff1ac",
          "sha1": "544e5d71238b50e6b26ae99604c50db9cfdf4b9a",
          "md5": "592f9fd926e18ba373c93ac4e07b92b3"
        }
      ]
    }
  ]
}
