{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "docs",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.5.aar",
          "url": "docs-0.0.5.aar",
          "size": 86705,
          "sha512": "365fc9ec1982481f3b0541759d8f075cae2c31b0846b96b8c76978fc1191b1591eda6561e4119fd4309966bd8920d2fc4204bcd797d5554ef196c71e87b3890f",
          "sha256": "ab53d2a6570e4594b4bcd19f5f6cc3782b0d1d088e5356d72c8fdd9142f0f260",
          "sha1": "79def75b40926b869f1fca2be1652857273f58bd",
          "md5": "238aa7bc9a99bf92c61d839d9c7edac6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.5.aar",
          "url": "docs-0.0.5.aar",
          "size": 86705,
          "sha512": "365fc9ec1982481f3b0541759d8f075cae2c31b0846b96b8c76978fc1191b1591eda6561e4119fd4309966bd8920d2fc4204bcd797d5554ef196c71e87b3890f",
          "sha256": "ab53d2a6570e4594b4bcd19f5f6cc3782b0d1d088e5356d72c8fdd9142f0f260",
          "sha1": "79def75b40926b869f1fca2be1652857273f58bd",
          "md5": "238aa7bc9a99bf92c61d839d9c7edac6"
        }
      ]
    }
  ]
}
