{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "themes",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.9.aar",
          "url": "themes-0.0.9.aar",
          "size": 1243050,
          "sha512": "f871b5ccc74357fc900a8d274050dfba2ced410a338ec9707f4f3c80c390e03b93605a7f91eeb0bf827d3a22be1dd110da2a0759a47ae90b14de874e2279120d",
          "sha256": "1af6cc7b29087623fd7b41565717267e95b2a8f3b6697f3616a322d52ad0d484",
          "sha1": "664ca32714d13dabb302b2dbdff83ee920eff6a9",
          "md5": "951948847121f20786d6a0be0c4ff1ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.9.aar",
          "url": "themes-0.0.9.aar",
          "size": 1243050,
          "sha512": "f871b5ccc74357fc900a8d274050dfba2ced410a338ec9707f4f3c80c390e03b93605a7f91eeb0bf827d3a22be1dd110da2a0759a47ae90b14de874e2279120d",
          "sha256": "1af6cc7b29087623fd7b41565717267e95b2a8f3b6697f3616a322d52ad0d484",
          "sha1": "664ca32714d13dabb302b2dbdff83ee920eff6a9",
          "md5": "951948847121f20786d6a0be0c4ff1ef"
        }
      ]
    }
  ]
}
