{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "themes",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.9.aar",
          "url": "themes-0.0.9.aar",
          "size": 1072378,
          "sha512": "b71e3aba8f5fdf76c06f8f2958a2a253279ad2759e882ece9375dbc55239c939f4dd8888f7f7eb0da223fbed035771341fa5f7c2780dfd75aa6af00698a537d5",
          "sha256": "a576bea9a761e123b2ef43b284347145dd0f1ee1d3079cec9a9444c688c9286d",
          "sha1": "30a0b34e64a97800ccd261b49e5c3a69ee76b0d3",
          "md5": "f12232654293dc70a1075c3a426df455"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.9.aar",
          "url": "themes-0.0.9.aar",
          "size": 1072378,
          "sha512": "b71e3aba8f5fdf76c06f8f2958a2a253279ad2759e882ece9375dbc55239c939f4dd8888f7f7eb0da223fbed035771341fa5f7c2780dfd75aa6af00698a537d5",
          "sha256": "a576bea9a761e123b2ef43b284347145dd0f1ee1d3079cec9a9444c688c9286d",
          "sha1": "30a0b34e64a97800ccd261b49e5c3a69ee76b0d3",
          "md5": "f12232654293dc70a1075c3a426df455"
        }
      ]
    }
  ]
}
