{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "themes",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.9.aar",
          "url": "themes-0.0.9.aar",
          "size": 1254797,
          "sha512": "34cb4519bcab7fb87dfba7f0ac5fa2561040c01fd8876641275ff346a2c2d3366b1407faa657c83b09ee4f1206e1c9c85f17dad4aad58b5b82ee31680f23a529",
          "sha256": "9d0c8cd9bb0c5ae6efa85e794763cc57a79532f4111df82168f97ed16227204c",
          "sha1": "fe880b22541182ae1600afe4c422e756eb4ca743",
          "md5": "2a2a55953cc933e442b8ca2cad40172c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.9.aar",
          "url": "themes-0.0.9.aar",
          "size": 1254797,
          "sha512": "34cb4519bcab7fb87dfba7f0ac5fa2561040c01fd8876641275ff346a2c2d3366b1407faa657c83b09ee4f1206e1c9c85f17dad4aad58b5b82ee31680f23a529",
          "sha256": "9d0c8cd9bb0c5ae6efa85e794763cc57a79532f4111df82168f97ed16227204c",
          "sha1": "fe880b22541182ae1600afe4c422e756eb4ca743",
          "md5": "2a2a55953cc933e442b8ca2cad40172c"
        }
      ]
    }
  ]
}
