{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "gamepad",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.2.aar",
          "url": "gamepad-0.0.2.aar",
          "size": 2871474,
          "sha512": "d5f5f281149d79f7ff9a00a98d2fc17ffdab432f42def16507f2ea67d2a4047085228d3dd2effe906a4fe32eb34f92252b65e8d5d2db965fb007188c772267bc",
          "sha256": "d3f8a30d2d925dcee9963805fd633e56f10bcb59afbede9f7bf5ae9a1defbee6",
          "sha1": "3e037ac37025d33e928b486cd88df81b1200dbd6",
          "md5": "a26c044d251f05750367a7b48a1ec1f4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.2.aar",
          "url": "gamepad-0.0.2.aar",
          "size": 2871474,
          "sha512": "d5f5f281149d79f7ff9a00a98d2fc17ffdab432f42def16507f2ea67d2a4047085228d3dd2effe906a4fe32eb34f92252b65e8d5d2db965fb007188c772267bc",
          "sha256": "d3f8a30d2d925dcee9963805fd633e56f10bcb59afbede9f7bf5ae9a1defbee6",
          "sha1": "3e037ac37025d33e928b486cd88df81b1200dbd6",
          "md5": "a26c044d251f05750367a7b48a1ec1f4"
        }
      ]
    }
  ]
}
