{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "gamepad",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.2.aar",
          "url": "gamepad-0.0.2.aar",
          "size": 2878795,
          "sha512": "d160386f7c024d39c4ffeebaac6c35a9e6611b55501a6bb4043e0b32851c6d1dd9545a1bb70c52c965fb0bb0490c4895a5f4a58d94c3f73be962d95d80422184",
          "sha256": "c21e4fd2ea689e8f4644b37a04188f12b72e96419a384446cf93180004a58bf9",
          "sha1": "f05d554bc22fd87cfaafcdfe45e62d5c5ae60990",
          "md5": "2e5b8eeb5a1bc93a81670888e7b30270"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.2.aar",
          "url": "gamepad-0.0.2.aar",
          "size": 2878795,
          "sha512": "d160386f7c024d39c4ffeebaac6c35a9e6611b55501a6bb4043e0b32851c6d1dd9545a1bb70c52c965fb0bb0490c4895a5f4a58d94c3f73be962d95d80422184",
          "sha256": "c21e4fd2ea689e8f4644b37a04188f12b72e96419a384446cf93180004a58bf9",
          "sha1": "f05d554bc22fd87cfaafcdfe45e62d5c5ae60990",
          "md5": "2e5b8eeb5a1bc93a81670888e7b30270"
        }
      ]
    }
  ]
}
