{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "limelightproxy",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.1.aar",
          "url": "limelightproxy-0.0.1.aar",
          "size": 97901,
          "sha512": "609d9e732d6c48122f835c0f64927592c822264fabe196b01a0f160535043e0e4d4fdb10824132f56602b905b5eb32b4368b2945ba6f3b3be5aba3a34a5d57f3",
          "sha256": "a6f10d38367b01801ae12c510a5506fa7ac9dd8619cd59401a9a0ee84af0205a",
          "sha1": "4cbd54c8e988476ba98094046281a0db14dd66ea",
          "md5": "600fdee728abc5f06807655c9de50634"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.1.aar",
          "url": "limelightproxy-0.0.1.aar",
          "size": 97901,
          "sha512": "609d9e732d6c48122f835c0f64927592c822264fabe196b01a0f160535043e0e4d4fdb10824132f56602b905b5eb32b4368b2945ba6f3b3be5aba3a34a5d57f3",
          "sha256": "a6f10d38367b01801ae12c510a5506fa7ac9dd8619cd59401a9a0ee84af0205a",
          "sha1": "4cbd54c8e988476ba98094046281a0db14dd66ea",
          "md5": "600fdee728abc5f06807655c9de50634"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "limelightproxy-0.0.1-sources.jar",
          "url": "limelightproxy-0.0.1-sources.jar",
          "size": 11385,
          "sha512": "8f5507b55c6da38806a7889fce2f612e6d6cf7a3f7ccbecd14621e4a2307acc8b184e33f9658f89b0029af838b8278a6d9128d012191522ab08a1f4e22254117",
          "sha256": "abb2e41dc871c777fffc32487668567a445e6636f9e873dce917488b73f46566",
          "sha1": "7563b6993aa48ab4b2267a500ca1f0f6ce221b2b",
          "md5": "5911f7cfcc90f4e647f4a93b2ce71f71"
        }
      ]
    }
  ]
}
