{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.11.aar",
          "url": "panels-0.0.11.aar",
          "size": 3938737,
          "sha512": "94d451d53d5073fd07284366aa63cf2b1286a8992844b0d5f9efde312f8fdf09a338605be9cdb09152c44f7865cbd3b9f3adeb1da3128f91bb62bfb634bef391",
          "sha256": "be572c89f1cb8fbccb0c85f5af570a9a9b1289c0c8a06fa5c8bdc89b61d400d8",
          "sha1": "6bde26b211eef342e067017aee591df54f72926b",
          "md5": "9af7e43567f4b65086398e3c7d09f01a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.11.aar",
          "url": "panels-0.0.11.aar",
          "size": 3938737,
          "sha512": "94d451d53d5073fd07284366aa63cf2b1286a8992844b0d5f9efde312f8fdf09a338605be9cdb09152c44f7865cbd3b9f3adeb1da3128f91bb62bfb634bef391",
          "sha256": "be572c89f1cb8fbccb0c85f5af570a9a9b1289c0c8a06fa5c8bdc89b61d400d8",
          "sha1": "6bde26b211eef342e067017aee591df54f72926b",
          "md5": "9af7e43567f4b65086398e3c7d09f01a"
        }
      ]
    }
  ]
}
