{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.11.aar",
          "url": "panels-0.0.11.aar",
          "size": 2865317,
          "sha512": "0b5a79866de99ab3f49b9ab188c38ba480baed2ae72ab352c97f48fe0404e5dc08b2333ff7bb6231f28cb775ffdb17a6c16e42f4896f7391697d83c649f38554",
          "sha256": "6c6292882032ec51ba62a66af4186e53dca2fea287f618c745b2bba80ad06306",
          "sha1": "1bbfc55afb13a1cce7da52676faf17192c21dcd4",
          "md5": "096f4d9cb3189e799e3c053b8d687d23"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.11.aar",
          "url": "panels-0.0.11.aar",
          "size": 2865317,
          "sha512": "0b5a79866de99ab3f49b9ab188c38ba480baed2ae72ab352c97f48fe0404e5dc08b2333ff7bb6231f28cb775ffdb17a6c16e42f4896f7391697d83c649f38554",
          "sha256": "6c6292882032ec51ba62a66af4186e53dca2fea287f618c745b2bba80ad06306",
          "sha1": "1bbfc55afb13a1cce7da52676faf17192c21dcd4",
          "md5": "096f4d9cb3189e799e3c053b8d687d23"
        }
      ]
    }
  ]
}
