{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.11.aar",
          "url": "panels-0.0.11.aar",
          "size": 3060480,
          "sha512": "cfd474107a5d646960d5276c75f7422aef77b52791a5161963975c12d7672980cf64222aa698058afd2e456ab934bd7f06d4810f384659e0c8bf1be22f90fae2",
          "sha256": "3160b955af6994675bee298231d496689ec6e1873630bc3523c01ce5af9b1322",
          "sha1": "e2ae6bfd81fbb26412f38e1db449b4891554b4d6",
          "md5": "c21ea3081750a142c43dc629edecc271"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.11.aar",
          "url": "panels-0.0.11.aar",
          "size": 3060480,
          "sha512": "cfd474107a5d646960d5276c75f7422aef77b52791a5161963975c12d7672980cf64222aa698058afd2e456ab934bd7f06d4810f384659e0c8bf1be22f90fae2",
          "sha256": "3160b955af6994675bee298231d496689ec6e1873630bc3523c01ce5af9b1322",
          "sha1": "e2ae6bfd81fbb26412f38e1db449b4891554b4d6",
          "md5": "c21ea3081750a142c43dc629edecc271"
        }
      ]
    }
  ]
}
