{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "docs",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.8.aar",
          "url": "docs-0.0.8.aar",
          "size": 224782,
          "sha512": "a8c84227880eade3270d85e4dc23035e1ef391db61b532e8b4f6bee8e0f14a9b2582fdf6a4334c1a63ba3970f905ebc90c91249b6b2e61df02ff5c8c77dfb790",
          "sha256": "3ba53781a07a9ce114d07c2727a85601a1698d46ebd630c7d9c2ffa9a7355556",
          "sha1": "927935f47f0ebceee2333202195b8f39534307e9",
          "md5": "42cb8c8fbb3986530a2cf36b3e9d766e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.8.aar",
          "url": "docs-0.0.8.aar",
          "size": 224782,
          "sha512": "a8c84227880eade3270d85e4dc23035e1ef391db61b532e8b4f6bee8e0f14a9b2582fdf6a4334c1a63ba3970f905ebc90c91249b6b2e61df02ff5c8c77dfb790",
          "sha256": "3ba53781a07a9ce114d07c2727a85601a1698d46ebd630c7d9c2ffa9a7355556",
          "sha1": "927935f47f0ebceee2333202195b8f39534307e9",
          "md5": "42cb8c8fbb3986530a2cf36b3e9d766e"
        }
      ]
    }
  ]
}
