{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "themes",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.2.aar",
          "url": "themes-0.0.2.aar",
          "size": 93437,
          "sha512": "14bbded11433181837237bebede4d8aebfdf66b823a8aa4b81ab97c0b3f22eca0d432aa2aa7899cabfc0769fa94f7705f18604d6276e1d09711868f2b33ac4e1",
          "sha256": "d9ffbfaa1ebc08a798a78a665ac87fa3dfcaa51592fcf2276c6f79be731db177",
          "sha1": "651ff42a9e074e3eba6e9a0145b0aea5c99fbd38",
          "md5": "e844493b986dbdd70202e8d09be1600f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.2.aar",
          "url": "themes-0.0.2.aar",
          "size": 93437,
          "sha512": "14bbded11433181837237bebede4d8aebfdf66b823a8aa4b81ab97c0b3f22eca0d432aa2aa7899cabfc0769fa94f7705f18604d6276e1d09711868f2b33ac4e1",
          "sha256": "d9ffbfaa1ebc08a798a78a665ac87fa3dfcaa51592fcf2276c6f79be731db177",
          "sha1": "651ff42a9e074e3eba6e9a0145b0aea5c99fbd38",
          "md5": "e844493b986dbdd70202e8d09be1600f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "themes-0.0.2-sources.jar",
          "url": "themes-0.0.2-sources.jar",
          "size": 1851,
          "sha512": "74da232fa553a8965c8a5e5e1fa215ad05c3ec9570138257656892ef95d8f1d976e77be0984357b42d236e90e53dfa9d29bdd73786c8d30cc2801c43eec093e7",
          "sha256": "2f4736717c78f10edead59249fc591e1370aef494070e2ee102e5e856f5c834c",
          "sha1": "4e0901b2bab42559ec7e0d6fa065a2d090977475",
          "md5": "95bb2831769f9018a648905661f6c105"
        }
      ]
    }
  ]
}
