{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.25.aar",
          "url": "panels-0.0.25.aar",
          "size": 734823,
          "sha512": "bd30f49ccf27fdceda31e55c545ccb1bf0ac21c01580165ac2ef431fa8b1c4d3b613b0b2cd137150e0ea1334a3273c102482cd2dcd36e79ee7f671b316b5539e",
          "sha256": "8cb7094a50f66928213d476d824d2222888688b60a717caf1df7201f6173457b",
          "sha1": "8c77f32b451ddd5c36db853826f69ec6890012f1",
          "md5": "ac7fe9ef3a06ddd21ea3fb0e9e8fcb83"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.25.aar",
          "url": "panels-0.0.25.aar",
          "size": 734823,
          "sha512": "bd30f49ccf27fdceda31e55c545ccb1bf0ac21c01580165ac2ef431fa8b1c4d3b613b0b2cd137150e0ea1334a3273c102482cd2dcd36e79ee7f671b316b5539e",
          "sha256": "8cb7094a50f66928213d476d824d2222888688b60a717caf1df7201f6173457b",
          "sha1": "8c77f32b451ddd5c36db853826f69ec6890012f1",
          "md5": "ac7fe9ef3a06ddd21ea3fb0e9e8fcb83"
        }
      ]
    }
  ]
}
