{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "utils",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-1.0.4.aar",
          "url": "utils-1.0.4.aar",
          "size": 77534,
          "sha512": "13d2a2d1954366a8cedbdcf000b97d29e558565504aa686916b2ab6df991e35c56d77904328b929f5b724e57672949d5f1f2389ded54a623f47a18b37d446721",
          "sha256": "382edb40e3872b912de98cb6a18db62ed5dcc0947ae451dd37495c5ad7fee8a9",
          "sha1": "70b6c1fb5029b1464378a043e2265289d2e04e66",
          "md5": "81be41f190ec625dbb98cb6cf03c1bad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-1.0.4.aar",
          "url": "utils-1.0.4.aar",
          "size": 77534,
          "sha512": "13d2a2d1954366a8cedbdcf000b97d29e558565504aa686916b2ab6df991e35c56d77904328b929f5b724e57672949d5f1f2389ded54a623f47a18b37d446721",
          "sha256": "382edb40e3872b912de98cb6a18db62ed5dcc0947ae451dd37495c5ad7fee8a9",
          "sha1": "70b6c1fb5029b1464378a043e2265289d2e04e66",
          "md5": "81be41f190ec625dbb98cb6cf03c1bad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-1.0.4-sources.jar",
          "url": "utils-1.0.4-sources.jar",
          "size": 1962,
          "sha512": "90a6256be2a5a3e37be90a335cae34b89986c2a0d65f518054632ae53d6259323673ed570004d2c0d2dbe5fbf1f67b34f66e0249871c9fb489a4e7032d33a842",
          "sha256": "4db5e1f47fb49a50c08c3677ea7aea7a627978a71a2e939618d69c805a944114",
          "sha1": "ecc2be3b71b0735ec6c29360e184dd938c15f7dc",
          "md5": "c352dddf4d9cd61cae35418c1a9a00bf"
        }
      ]
    }
  ]
}
