{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "themes",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.8.aar",
          "url": "themes-0.0.8.aar",
          "size": 1072359,
          "sha512": "5e44b016bc543abf34b338c7d56e62c03b09cbc1ec28782271a6115fb07268a3284afbb95ecceccef5a321be8df26a1980469bd54bf3316c861bbf279b30acc9",
          "sha256": "6f1c9fb089a7e5686f864521ee34393eda8389efef3017bb29a6d8e53232734b",
          "sha1": "50432ac28a6a71b2446ba2ef9f8b3e10227d816f",
          "md5": "bbc8152e9da4662d770001e277977e90"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.8.aar",
          "url": "themes-0.0.8.aar",
          "size": 1072359,
          "sha512": "5e44b016bc543abf34b338c7d56e62c03b09cbc1ec28782271a6115fb07268a3284afbb95ecceccef5a321be8df26a1980469bd54bf3316c861bbf279b30acc9",
          "sha256": "6f1c9fb089a7e5686f864521ee34393eda8389efef3017bb29a6d8e53232734b",
          "sha1": "50432ac28a6a71b2446ba2ef9f8b3e10227d816f",
          "md5": "bbc8152e9da4662d770001e277977e90"
        }
      ]
    }
  ]
}
