{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "utils",
    "version": "0.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.16.aar",
          "url": "utils-0.0.16.aar",
          "size": 231592,
          "sha512": "aa3b49ced04c98d21b88f4e3b27c6ce603a7d799f871f3666e010cd3fda5e71cd9a4a17969a880d022462b63237608a1cff7f017de476b9ed1664640f840960e",
          "sha256": "0a7907d87b7e6dae6bcba62f4bc57a270bfa6aea57106ab6417c018a039dc6c1",
          "sha1": "249b86633ebaf86e99996d94c9c46cc093104725",
          "md5": "54654e29b084994d33f91be43fff773a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.16.aar",
          "url": "utils-0.0.16.aar",
          "size": 231592,
          "sha512": "aa3b49ced04c98d21b88f4e3b27c6ce603a7d799f871f3666e010cd3fda5e71cd9a4a17969a880d022462b63237608a1cff7f017de476b9ed1664640f840960e",
          "sha256": "0a7907d87b7e6dae6bcba62f4bc57a270bfa6aea57106ab6417c018a039dc6c1",
          "sha1": "249b86633ebaf86e99996d94c9c46cc093104725",
          "md5": "54654e29b084994d33f91be43fff773a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-0.0.16-sources.jar",
          "url": "utils-0.0.16-sources.jar",
          "size": 1962,
          "sha512": "90a6256be2a5a3e37be90a335cae34b89986c2a0d65f518054632ae53d6259323673ed570004d2c0d2dbe5fbf1f67b34f66e0249871c9fb489a4e7032d33a842",
          "sha256": "4db5e1f47fb49a50c08c3677ea7aea7a627978a71a2e939618d69c805a944114",
          "sha1": "ecc2be3b71b0735ec6c29360e184dd938c15f7dc",
          "md5": "c352dddf4d9cd61cae35418c1a9a00bf"
        }
      ]
    }
  ]
}
