{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "pinger",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "pinger-0.0.10.aar",
          "url": "pinger-0.0.10.aar",
          "size": 231846,
          "sha512": "517d47a06d1be91c1754148dcdabcfac905730bf99bd0722467d847fe55c8d3ef3398d095952bb2e7be73d2437a1e2112e55ddd98dec884c4d0b29080d5677a3",
          "sha256": "c6ae6a65d110b93c0039611d43648ad0add5a07b15802a12ae9ebcbbc2f9a184",
          "sha1": "d4344b334f6ddfe4167081eae5762c9f6b599e28",
          "md5": "c1e5a17f75962ed2d769896bd2031b5a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "pinger-0.0.10.aar",
          "url": "pinger-0.0.10.aar",
          "size": 231846,
          "sha512": "517d47a06d1be91c1754148dcdabcfac905730bf99bd0722467d847fe55c8d3ef3398d095952bb2e7be73d2437a1e2112e55ddd98dec884c4d0b29080d5677a3",
          "sha256": "c6ae6a65d110b93c0039611d43648ad0add5a07b15802a12ae9ebcbbc2f9a184",
          "sha1": "d4344b334f6ddfe4167081eae5762c9f6b599e28",
          "md5": "c1e5a17f75962ed2d769896bd2031b5a"
        }
      ]
    }
  ]
}
