{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "ftcontrol",
    "version": "0.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.5.8.aar",
          "url": "ftcontrol-0.5.8.aar",
          "size": 31748775,
          "sha512": "9a24521875d62c7d9b53db731499811bd180f2a26a90c250c1b21c37ee1dcfb49da3e24e2c7607dc8789f30243ec716625a48704cfc9bdc1f7b490871a92f915",
          "sha256": "5b0ed93bd1fa6b4675e9afb8e92c0cef6542c19ebecc9245c40c126b5ed08b76",
          "sha1": "f1b2692262184d1ff3effa52b4b32f9044aacf18",
          "md5": "35e173a6a8be36ac3500f5d5a9c25bbb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.5.8.aar",
          "url": "ftcontrol-0.5.8.aar",
          "size": 31748775,
          "sha512": "9a24521875d62c7d9b53db731499811bd180f2a26a90c250c1b21c37ee1dcfb49da3e24e2c7607dc8789f30243ec716625a48704cfc9bdc1f7b490871a92f915",
          "sha256": "5b0ed93bd1fa6b4675e9afb8e92c0cef6542c19ebecc9245c40c126b5ed08b76",
          "sha1": "f1b2692262184d1ff3effa52b4b32f9044aacf18",
          "md5": "35e173a6a8be36ac3500f5d5a9c25bbb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftcontrol-0.5.8-sources.jar",
          "url": "ftcontrol-0.5.8-sources.jar",
          "size": 90035,
          "sha512": "22308069034ee36a2cdf4fffd4307233498da8d3737a76e4c643d32b9d1a61a2bfd3a2b69047cdcb9814ed63fbc021730bf65cd2b2840c19b166146bbb045704",
          "sha256": "fe51612bf43abff1b620547b167f54b3aef7f82c55434a9563b77403d234303a",
          "sha1": "227022ae5fe8bd9ae1ece8e9c3dcf0de12def178",
          "md5": "1f95b39f952db91b2821b7339f233d08"
        }
      ]
    }
  ]
}
