{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "configurables",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.5.aar",
          "url": "configurables-0.0.5.aar",
          "size": 166252,
          "sha512": "f58e338a9d1a3307027f7976c43b47b6c492337754bdbdb9caa894ac30198edcaf27a801f6bb5beb058f26b14dd32f995b2952a5f955cba4fc0107c95308391a",
          "sha256": "6933f2062d6df6f2cd0be86ba72515c90febe6cd51fb07d395cafdb8fa7a5141",
          "sha1": "555a11a5752930538bc7b5b43a3a21c25078c381",
          "md5": "b761c75f1617344504cbd33c948b46f6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.5.aar",
          "url": "configurables-0.0.5.aar",
          "size": 166252,
          "sha512": "f58e338a9d1a3307027f7976c43b47b6c492337754bdbdb9caa894ac30198edcaf27a801f6bb5beb058f26b14dd32f995b2952a5f955cba4fc0107c95308391a",
          "sha256": "6933f2062d6df6f2cd0be86ba72515c90febe6cd51fb07d395cafdb8fa7a5141",
          "sha1": "555a11a5752930538bc7b5b43a3a21c25078c381",
          "md5": "b761c75f1617344504cbd33c948b46f6"
        }
      ]
    }
  ]
}
