{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "telemetry",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.4.aar",
          "url": "telemetry-0.0.4.aar",
          "size": 89931,
          "sha512": "5977cccdb872b5001a019cb110d7172822765fed9b270f47cdca0bdaed3cbee60b3c6122df45a92140aff0fe98efc956011474f51dd937f0e000688677d317db",
          "sha256": "e2e0fcf21293084c3748e98dc26089f024c68ccf21d5da7cbbe1df4645f46572",
          "sha1": "70bbbafd3d8f0a14aa1a352e91837e545dde89d8",
          "md5": "5f3d240c303dac0689877b2519b2ead7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.4.aar",
          "url": "telemetry-0.0.4.aar",
          "size": 89931,
          "sha512": "5977cccdb872b5001a019cb110d7172822765fed9b270f47cdca0bdaed3cbee60b3c6122df45a92140aff0fe98efc956011474f51dd937f0e000688677d317db",
          "sha256": "e2e0fcf21293084c3748e98dc26089f024c68ccf21d5da7cbbe1df4645f46572",
          "sha1": "70bbbafd3d8f0a14aa1a352e91837e545dde89d8",
          "md5": "5f3d240c303dac0689877b2519b2ead7"
        }
      ]
    }
  ]
}
