{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "opmodecontrol",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.2.aar",
          "url": "opmodecontrol-0.0.2.aar",
          "size": 104113,
          "sha512": "3e4be4dc1bdf3353567ef9fccd8de3f3536a35bd8c289af5cd444764571f8ce1a2054b9ef82aabdd9c29cd337edc6ddb7cb89439c4e3bc805e77d22ae63f86ae",
          "sha256": "919d7d653653d4d98e5fcc558887588a0cbde7211ad10ee49f4a5236e6e27905",
          "sha1": "debaa0a30237171385e0f478ee94e6ac57679a8a",
          "md5": "c8ffab8172bdf79cad239191ea06b592"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.2.aar",
          "url": "opmodecontrol-0.0.2.aar",
          "size": 104113,
          "sha512": "3e4be4dc1bdf3353567ef9fccd8de3f3536a35bd8c289af5cd444764571f8ce1a2054b9ef82aabdd9c29cd337edc6ddb7cb89439c4e3bc805e77d22ae63f86ae",
          "sha256": "919d7d653653d4d98e5fcc558887588a0cbde7211ad10ee49f4a5236e6e27905",
          "sha1": "debaa0a30237171385e0f478ee94e6ac57679a8a",
          "md5": "c8ffab8172bdf79cad239191ea06b592"
        }
      ]
    }
  ]
}
