{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "ftcontrol",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.2.5.aar",
          "url": "ftcontrol-0.2.5.aar",
          "size": 20615360,
          "sha512": "550f918e809f99ebb4a057804037f14e0c579ba0d7c0927848fb0cafc9fc566a242431e51bbe731b4b29d026bf540e1019d0ef2bcb912c936331cc2c0ed36273",
          "sha256": "d2c5d59402f5b9259eb58902eff19c6dffa44cc8d742e4fbcd2dfdd9c7ab744a",
          "sha1": "f8f3e659b3905fdc446ae787799325ef98ec96e3",
          "md5": "1021f396059084a0807d046f1367e503"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.2.5.aar",
          "url": "ftcontrol-0.2.5.aar",
          "size": 20615360,
          "sha512": "550f918e809f99ebb4a057804037f14e0c579ba0d7c0927848fb0cafc9fc566a242431e51bbe731b4b29d026bf540e1019d0ef2bcb912c936331cc2c0ed36273",
          "sha256": "d2c5d59402f5b9259eb58902eff19c6dffa44cc8d742e4fbcd2dfdd9c7ab744a",
          "sha1": "f8f3e659b3905fdc446ae787799325ef98ec96e3",
          "md5": "1021f396059084a0807d046f1367e503"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftcontrol-0.2.5-sources.jar",
          "url": "ftcontrol-0.2.5-sources.jar",
          "size": 67601,
          "sha512": "830779cd2e4adc924f4d6125bde80b7401276528d141a2d3f4c96a1e0035cb4dcf462951abd87930bcd90954ee4a7bc46074e7478d9cded39a7c4a914332b7a5",
          "sha256": "9a68ef46f24bc6995a1eb4adbaa0843845deb54e8f8910d02a536fd918b385ed",
          "sha1": "926ad6f6ad352006a9f6003f3de6c370ed2ccdb4",
          "md5": "5e7f91a8e50b1a4b6fa34a2e9e850d6d"
        }
      ]
    }
  ]
}
