{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.8.aar",
          "url": "panels-0.0.8.aar",
          "size": 266929,
          "sha512": "cc0295fc5c56830d3c6f517fe76cf174ce32c237e30697fa8fd4944ebffdc63b7eb4faec95c3549fe1f87b8f3744cdbfc87c63ffa2383c787baa6445c541c55e",
          "sha256": "9397d0e247267b5d41c6b6ba7086eaf97bf41471863d75751c9d1008e3de76fc",
          "sha1": "cc8db8f704ae6ddfda92c30f9f433676293c7126",
          "md5": "aeb0a492a93bf143658da41e7a02506d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.8.aar",
          "url": "panels-0.0.8.aar",
          "size": 266929,
          "sha512": "cc0295fc5c56830d3c6f517fe76cf174ce32c237e30697fa8fd4944ebffdc63b7eb4faec95c3549fe1f87b8f3744cdbfc87c63ffa2383c787baa6445c541c55e",
          "sha256": "9397d0e247267b5d41c6b6ba7086eaf97bf41471863d75751c9d1008e3de76fc",
          "sha1": "cc8db8f704ae6ddfda92c30f9f433676293c7126",
          "md5": "aeb0a492a93bf143658da41e7a02506d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "panels-0.0.8-sources.jar",
          "url": "panels-0.0.8-sources.jar",
          "size": 34653,
          "sha512": "9be906dc4c17a78cc146a6edc8820535bc538268f2d2f0421c6eaf26c05374bf1e833b4960041afcba50eaaa4768b7eff3a4a629d29bd1c4049a77cd4b19fa8d",
          "sha256": "5055be724f680f7a876b1a2fe3a3756a4b8ece507b51d5164ace77947ae1d879",
          "sha1": "46c8c182367d59909a2772e520872331cf7bd9e7",
          "md5": "a4079a90115612f9b323c7eb9b04575c"
        }
      ]
    }
  ]
}
