{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-1.0.2.aar",
          "url": "panels-1.0.2.aar",
          "size": 748259,
          "sha512": "c15e220ca565d0f8eaa45b030e2278975e5fbd2807accbe31c141a055616768219721eed3f498bf585b82840c263e9f3b4e909dc4eb7596e7bd1161eb8629a7d",
          "sha256": "71096a1777dad0a6c578afac84b237d47571ed6c566d971af67cc2bddb6ea613",
          "sha1": "f546eb310fe5d676a36754318d82295a5e68af16",
          "md5": "df4a877838b76763d649c860a26a3e3f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-1.0.2.aar",
          "url": "panels-1.0.2.aar",
          "size": 748259,
          "sha512": "c15e220ca565d0f8eaa45b030e2278975e5fbd2807accbe31c141a055616768219721eed3f498bf585b82840c263e9f3b4e909dc4eb7596e7bd1161eb8629a7d",
          "sha256": "71096a1777dad0a6c578afac84b237d47571ed6c566d971af67cc2bddb6ea613",
          "sha1": "f546eb310fe5d676a36754318d82295a5e68af16",
          "md5": "df4a877838b76763d649c860a26a3e3f"
        }
      ]
    }
  ]
}
