{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "docs",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.2.aar",
          "url": "docs-0.0.2.aar",
          "size": 79629,
          "sha512": "40fb6198f6f872cdea4a4bd9fc356a334fa76f8d5796e88be129fdbab69eadfe4b4f06b3092af218e2cebf4295a3cc778223b04a1166fa078880a9eb54fb2cfa",
          "sha256": "3b98d89300190117000336f530e8ec15f9b66f4fc6f86b93109db609676ccda3",
          "sha1": "b0f5cfe882e782b5d9aec73dc0df4630f8cb5a19",
          "md5": "82db82cf833f5c38724cc46204a2965b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.2.aar",
          "url": "docs-0.0.2.aar",
          "size": 79629,
          "sha512": "40fb6198f6f872cdea4a4bd9fc356a334fa76f8d5796e88be129fdbab69eadfe4b4f06b3092af218e2cebf4295a3cc778223b04a1166fa078880a9eb54fb2cfa",
          "sha256": "3b98d89300190117000336f530e8ec15f9b66f4fc6f86b93109db609676ccda3",
          "sha1": "b0f5cfe882e782b5d9aec73dc0df4630f8cb5a19",
          "md5": "82db82cf833f5c38724cc46204a2965b"
        }
      ]
    }
  ]
}
