{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "docs",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.2.aar",
          "url": "docs-0.0.2.aar",
          "size": 79796,
          "sha512": "e01980974f3bc7fa3254cb46f9e7f2ae0e15f5ebcc8577242b9ea771b5b911b29b8c34d52cf3043bedb96139e6c6a878da31d660ec3dc39a13e47ff324fa0b71",
          "sha256": "55d62e841b95af821a78d96852d413c5188edf58259ee8f3e6fe97c9b639fe7b",
          "sha1": "44a89f44b1a97c704164558966f8d53655eaa842",
          "md5": "cda83a9244af38a4ce6ef2bc1bb21e33"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.2.aar",
          "url": "docs-0.0.2.aar",
          "size": 79796,
          "sha512": "e01980974f3bc7fa3254cb46f9e7f2ae0e15f5ebcc8577242b9ea771b5b911b29b8c34d52cf3043bedb96139e6c6a878da31d660ec3dc39a13e47ff324fa0b71",
          "sha256": "55d62e841b95af821a78d96852d413c5188edf58259ee8f3e6fe97c9b639fe7b",
          "sha1": "44a89f44b1a97c704164558966f8d53655eaa842",
          "md5": "cda83a9244af38a4ce6ef2bc1bb21e33"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "docs-0.0.2-sources.jar",
          "url": "docs-0.0.2-sources.jar",
          "size": 1797,
          "sha512": "cb20ad9b5c6c94ffcb1f5ed2bc8aa36e1623dcb23f6bda224aedb3d97cfc9e281d9a6fc32f88fb7e5b1fc0292b4a397b9a5cbe0bd14e49112fa7b476feed5245",
          "sha256": "5d1b4e79a7c0389edab1d17a65f34b84a53f9851650b75765c197b958c947a82",
          "sha1": "61ded4ef1b9a8d8bd50364f0af7e2cdefc853862",
          "md5": "aa6a46dd539ce94b595e490856043022"
        }
      ]
    }
  ]
}
