{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "telemetry",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.6.aar",
          "url": "telemetry-0.0.6.aar",
          "size": 89597,
          "sha512": "6245bff50210ded07d323cf0fbfc2159810d01efc1eafd5e20b0d4f2d38d6dd9218cb169058dd016f199caca556cdc9524ce0d0c8244e59af8d6385031e6ce06",
          "sha256": "af9354886a8e1f7b24088816b1f51b26dbc0aa2a580e6395d7c02f75e42cbbd1",
          "sha1": "31161e25f6bee05061c54f629393018395e99557",
          "md5": "649c27fc14bafe9a07abec437207905d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.6.aar",
          "url": "telemetry-0.0.6.aar",
          "size": 89597,
          "sha512": "6245bff50210ded07d323cf0fbfc2159810d01efc1eafd5e20b0d4f2d38d6dd9218cb169058dd016f199caca556cdc9524ce0d0c8244e59af8d6385031e6ce06",
          "sha256": "af9354886a8e1f7b24088816b1f51b26dbc0aa2a580e6395d7c02f75e42cbbd1",
          "sha1": "31161e25f6bee05061c54f629393018395e99557",
          "md5": "649c27fc14bafe9a07abec437207905d"
        }
      ]
    }
  ]
}
