{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "telemetry",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.6.aar",
          "url": "telemetry-0.0.6.aar",
          "size": 431977,
          "sha512": "7968b88da3d7431d5b00ac681102d653770c90b8dc05b4c607863735ca28bcbd7943cac8bf21e460b84bce0344fa1d5f8a88a4c9f71cb99caa0ee1469169a299",
          "sha256": "206c6deee74a0e775020bd638564dc86168e3803edcc71226a6e59a2fa14dea5",
          "sha1": "eea8712a6e4314771c18c8c93c23bfa3488f2557",
          "md5": "e8b0d2454f56a4260bf959055fefd374"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.6.aar",
          "url": "telemetry-0.0.6.aar",
          "size": 431977,
          "sha512": "7968b88da3d7431d5b00ac681102d653770c90b8dc05b4c607863735ca28bcbd7943cac8bf21e460b84bce0344fa1d5f8a88a4c9f71cb99caa0ee1469169a299",
          "sha256": "206c6deee74a0e775020bd638564dc86168e3803edcc71226a6e59a2fa14dea5",
          "sha1": "eea8712a6e4314771c18c8c93c23bfa3488f2557",
          "md5": "e8b0d2454f56a4260bf959055fefd374"
        }
      ]
    }
  ]
}
