{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "telemetry",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.6.aar",
          "url": "telemetry-0.0.6.aar",
          "size": 93841,
          "sha512": "0194d4d1f8509fadd4b01db8aa1ff725eaac7113c46e9bf91755754f2808711688093f543133c7bd11bd46d64fadb54e94c557ba7889f222ebbb4ec3b5319e87",
          "sha256": "bf26f0cedd7a4d65a03efd6522eb480e6a89b55311728f9524a4d38a64bb6cb8",
          "sha1": "805e3aeb9e16f78782f52098c2b1aad65e848fdf",
          "md5": "ad231674820cbbe4d913efaaa4719792"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.6.aar",
          "url": "telemetry-0.0.6.aar",
          "size": 93841,
          "sha512": "0194d4d1f8509fadd4b01db8aa1ff725eaac7113c46e9bf91755754f2808711688093f543133c7bd11bd46d64fadb54e94c557ba7889f222ebbb4ec3b5319e87",
          "sha256": "bf26f0cedd7a4d65a03efd6522eb480e6a89b55311728f9524a4d38a64bb6cb8",
          "sha1": "805e3aeb9e16f78782f52098c2b1aad65e848fdf",
          "md5": "ad231674820cbbe4d913efaaa4719792"
        }
      ]
    }
  ]
}
