{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "utils",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.12.aar",
          "url": "utils-0.0.12.aar",
          "size": 231518,
          "sha512": "21a78690dbc6b57fbb371686313673deb153885a9c5fc7594a55da7311e3599443d3f16a39d1e8a742fffc2bacd646c12896aacd47c89e374b9b4ecdd8b95ed9",
          "sha256": "db6054ddddaac231d923fbf1b6cc2248f5759309b05aee4f58d5709acc418198",
          "sha1": "8b369b75bf92aeeddf34c2b85bfd88fe0c78d01a",
          "md5": "c47d6c4fb6376f108f08721839a06ccf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.12.aar",
          "url": "utils-0.0.12.aar",
          "size": 231518,
          "sha512": "21a78690dbc6b57fbb371686313673deb153885a9c5fc7594a55da7311e3599443d3f16a39d1e8a742fffc2bacd646c12896aacd47c89e374b9b4ecdd8b95ed9",
          "sha256": "db6054ddddaac231d923fbf1b6cc2248f5759309b05aee4f58d5709acc418198",
          "sha1": "8b369b75bf92aeeddf34c2b85bfd88fe0c78d01a",
          "md5": "c47d6c4fb6376f108f08721839a06ccf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-0.0.12-sources.jar",
          "url": "utils-0.0.12-sources.jar",
          "size": 1962,
          "sha512": "90a6256be2a5a3e37be90a335cae34b89986c2a0d65f518054632ae53d6259323673ed570004d2c0d2dbe5fbf1f67b34f66e0249871c9fb489a4e7032d33a842",
          "sha256": "4db5e1f47fb49a50c08c3677ea7aea7a627978a71a2e939618d69c805a944114",
          "sha1": "ecc2be3b71b0735ec6c29360e184dd938c15f7dc",
          "md5": "c352dddf4d9cd61cae35418c1a9a00bf"
        }
      ]
    }
  ]
}
