{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "pinger",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "pinger-0.0.11.aar",
          "url": "pinger-0.0.11.aar",
          "size": 231845,
          "sha512": "5189e4cd2af64e7a8742b9c105d9fe9e86df36211e1942b9af24a3a4cc098fb3584626393b27e59c916bf09ed98fb2d87e4f82fd4e3340ee83e6d4e4e54301bd",
          "sha256": "3ba8c8c1c9f6d433290be6dd0abbba2c95a8ff3e3cc74eae873cf278972ae148",
          "sha1": "ce0ff10c922a5140c57b1c415973b0bb06f0cafd",
          "md5": "087c5cbb5b842779fdb2cf41b279f15d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "pinger-0.0.11.aar",
          "url": "pinger-0.0.11.aar",
          "size": 231845,
          "sha512": "5189e4cd2af64e7a8742b9c105d9fe9e86df36211e1942b9af24a3a4cc098fb3584626393b27e59c916bf09ed98fb2d87e4f82fd4e3340ee83e6d4e4e54301bd",
          "sha256": "3ba8c8c1c9f6d433290be6dd0abbba2c95a8ff3e3cc74eae873cf278972ae148",
          "sha1": "ce0ff10c922a5140c57b1c415973b0bb06f0cafd",
          "md5": "087c5cbb5b842779fdb2cf41b279f15d"
        }
      ]
    }
  ]
}
