{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "docs",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-1.0.3.aar",
          "url": "docs-1.0.3.aar",
          "size": 75652,
          "sha512": "c9caba700b54b7d1f080edef8d56862b3013c545ccf3f99f416d7a91ca0394053e2046abd33f1ab5c5d9ecd91337a765d9854ff2d626825b12d059488bc3f5f5",
          "sha256": "25109ff3d86e225a589760666acf13d363abb9c9b9e2ed7fc140c90c5d2614d0",
          "sha1": "2c30f74624c023083e77aad6a638b0b293235ac3",
          "md5": "da2966d1f7c639635b9afeff4f0a41c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-1.0.3.aar",
          "url": "docs-1.0.3.aar",
          "size": 75652,
          "sha512": "c9caba700b54b7d1f080edef8d56862b3013c545ccf3f99f416d7a91ca0394053e2046abd33f1ab5c5d9ecd91337a765d9854ff2d626825b12d059488bc3f5f5",
          "sha256": "25109ff3d86e225a589760666acf13d363abb9c9b9e2ed7fc140c90c5d2614d0",
          "sha1": "2c30f74624c023083e77aad6a638b0b293235ac3",
          "md5": "da2966d1f7c639635b9afeff4f0a41c9"
        }
      ]
    }
  ]
}
