{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "gamepad",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.1.aar",
          "url": "gamepad-0.0.1.aar",
          "size": 2871403,
          "sha512": "ef66085937c83b712957f1fedb4eba5c9ac4b790b7b208fc1f3fe1218127ccbc4dbf63324bd7c93afd0ace18ad0fed19b31674f894fb7151c84d0df1197f806c",
          "sha256": "a5d4371bc9b5dc92a921ff203e25eae378ed17e0bd8c714e449e96af4752acac",
          "sha1": "b2f458b4bf808b89f71ebf5683721600ee884839",
          "md5": "c1e1cca7eca0f123a6800153ca225587"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.1.aar",
          "url": "gamepad-0.0.1.aar",
          "size": 2871403,
          "sha512": "ef66085937c83b712957f1fedb4eba5c9ac4b790b7b208fc1f3fe1218127ccbc4dbf63324bd7c93afd0ace18ad0fed19b31674f894fb7151c84d0df1197f806c",
          "sha256": "a5d4371bc9b5dc92a921ff203e25eae378ed17e0bd8c714e449e96af4752acac",
          "sha1": "b2f458b4bf808b89f71ebf5683721600ee884839",
          "md5": "c1e1cca7eca0f123a6800153ca225587"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "gamepad-0.0.1-sources.jar",
          "url": "gamepad-0.0.1-sources.jar",
          "size": 4439,
          "sha512": "074e7617d556bc6c264489be0065117e015ba4f8024be2079d9dd09a6fa95f8400c430678a3e4c7d634ee892078cf66b5255f45a4488de4c609fa33e0bf47315",
          "sha256": "744e717a970498245c20d47e95d45d238bcef3ed49ed3fc4b0aa1910c222273f",
          "sha1": "f37954fd8f0cea2591061accc314c624d7d8da05",
          "md5": "e67c4952a4c6f3b302ce9975837e3ea7"
        }
      ]
    }
  ]
}
