{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "capture",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.3.aar",
          "url": "capture-0.0.3.aar",
          "size": 93984,
          "sha512": "e590b4401eca102ccd8deb0ba992f07cb2295d4ec95d9413c55819fdf4e676b61e9cb60544ff7bc186cf034999dc4b3b5fe1f5ed1074f311e176d38b3726f3a7",
          "sha256": "9cb673e494325204c84c464b07714e50f503f50388d18dcf6da49da50809f17a",
          "sha1": "8aa355ac92a47f6d55e47ab7652a2263fde7e5c7",
          "md5": "56e2cc39f0b3e49a0f8e2821a6829280"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.3.aar",
          "url": "capture-0.0.3.aar",
          "size": 93984,
          "sha512": "e590b4401eca102ccd8deb0ba992f07cb2295d4ec95d9413c55819fdf4e676b61e9cb60544ff7bc186cf034999dc4b3b5fe1f5ed1074f311e176d38b3726f3a7",
          "sha256": "9cb673e494325204c84c464b07714e50f503f50388d18dcf6da49da50809f17a",
          "sha1": "8aa355ac92a47f6d55e47ab7652a2263fde7e5c7",
          "md5": "56e2cc39f0b3e49a0f8e2821a6829280"
        }
      ]
    }
  ]
}
