{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "utils",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.13.aar",
          "url": "utils-0.0.13.aar",
          "size": 231501,
          "sha512": "d818ddf245f634e7fddaddec61ac283acf46056bff44a24b0bc95023161afeb30f69c0c0bccbbb1a211b34e5de9f2e75feca3e9107ae963f8a9fd1be89d32157",
          "sha256": "f524f3ef44483ddf580436ecf70e32c8798bddf8a93873c0463e789549beee8e",
          "sha1": "47a6b944dd02cb94baae6ec84ab538cd482c788c",
          "md5": "ffe7b50e7025c60aaece516138e55153"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.13.aar",
          "url": "utils-0.0.13.aar",
          "size": 231501,
          "sha512": "d818ddf245f634e7fddaddec61ac283acf46056bff44a24b0bc95023161afeb30f69c0c0bccbbb1a211b34e5de9f2e75feca3e9107ae963f8a9fd1be89d32157",
          "sha256": "f524f3ef44483ddf580436ecf70e32c8798bddf8a93873c0463e789549beee8e",
          "sha1": "47a6b944dd02cb94baae6ec84ab538cd482c788c",
          "md5": "ffe7b50e7025c60aaece516138e55153"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-0.0.13-sources.jar",
          "url": "utils-0.0.13-sources.jar",
          "size": 1962,
          "sha512": "90a6256be2a5a3e37be90a335cae34b89986c2a0d65f518054632ae53d6259323673ed570004d2c0d2dbe5fbf1f67b34f66e0249871c9fb489a4e7032d33a842",
          "sha256": "4db5e1f47fb49a50c08c3677ea7aea7a627978a71a2e939618d69c805a944114",
          "sha1": "ecc2be3b71b0735ec6c29360e184dd938c15f7dc",
          "md5": "c352dddf4d9cd61cae35418c1a9a00bf"
        }
      ]
    }
  ]
}
