{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "ftcontrol",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.1.5.aar",
          "url": "ftcontrol-0.1.5.aar",
          "size": 21342755,
          "sha512": "a9291f5828178685d3a0482489dd019c6e6755c9512f959a5c2953dd4570e0f79723baf1a3ece1ea4a17534a25a8225e635d77708b63779df7bf9144504ed218",
          "sha256": "2808d44fe50421202a135aaf5d19e3e0c68dd77112cd11a8024c8e61def4fff9",
          "sha1": "13ff8c52e17b44a59cbed8a5bd90b2d77bb68c60",
          "md5": "bda1e70fabe066c87d1f6c043321c727"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.1.5.aar",
          "url": "ftcontrol-0.1.5.aar",
          "size": 21342755,
          "sha512": "a9291f5828178685d3a0482489dd019c6e6755c9512f959a5c2953dd4570e0f79723baf1a3ece1ea4a17534a25a8225e635d77708b63779df7bf9144504ed218",
          "sha256": "2808d44fe50421202a135aaf5d19e3e0c68dd77112cd11a8024c8e61def4fff9",
          "sha1": "13ff8c52e17b44a59cbed8a5bd90b2d77bb68c60",
          "md5": "bda1e70fabe066c87d1f6c043321c727"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftcontrol-0.1.5-sources.jar",
          "url": "ftcontrol-0.1.5-sources.jar",
          "size": 79273,
          "sha512": "979a7f7754573480e7a9563fa66c7b8bdf4cd106d66b63b7cd45693b5dbae2fce7a37e5209123466dfaff68dbf5e53bff6aa01774ab070a6bdaf0d572b1d8db8",
          "sha256": "69b4cb03550984678877c331957ca9fafcf40177687b174c3a7a434d825995c1",
          "sha1": "0549b525d43a4f8a93e82fce44a9dbec34cb3d77",
          "md5": "ba31168eb5e8b9b39c9d150d128187d9"
        }
      ]
    }
  ]
}
