{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "capture",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.5.aar",
          "url": "capture-0.0.5.aar",
          "size": 1426455,
          "sha512": "86b6261298c6e460cfcebc89fe8e946fa1e92fa9a94f172f6f73e4f26c53364c380f5187c0396be056f7880a2bce17cb30e5ae724e82197864f28b742a8b6f2a",
          "sha256": "78e3cf623d140e87e8bbb8e1e40f02cbb46d598ec8b1b53f3b6e59cd58e4831a",
          "sha1": "51c9c0d8a7e04ec10450cef16790dd5e7efd8560",
          "md5": "251b5beae4799868ebe9087012474310"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.5.aar",
          "url": "capture-0.0.5.aar",
          "size": 1426455,
          "sha512": "86b6261298c6e460cfcebc89fe8e946fa1e92fa9a94f172f6f73e4f26c53364c380f5187c0396be056f7880a2bce17cb30e5ae724e82197864f28b742a8b6f2a",
          "sha256": "78e3cf623d140e87e8bbb8e1e40f02cbb46d598ec8b1b53f3b6e59cd58e4831a",
          "sha1": "51c9c0d8a7e04ec10450cef16790dd5e7efd8560",
          "md5": "251b5beae4799868ebe9087012474310"
        }
      ]
    }
  ]
}
