{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "utils",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.8.aar",
          "url": "utils-0.0.8.aar",
          "size": 1392686,
          "sha512": "54657e374d47825d05f4df1cd76b56f2ca18043770cb018cc648272861bce6ae6f4e0024cdef842ea53bf8b4218a65573b138e9fcb776c7cc0b77352fa0f14bd",
          "sha256": "61b4584ad3978050154c0c59a64d8cccadf7da73b7535fdd0d5293bc2321a839",
          "sha1": "6fce51956e71cd6fc14d76569e7854fd52d01b4c",
          "md5": "e14a07f45e60cf63ef3114eb757e7793"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.8.aar",
          "url": "utils-0.0.8.aar",
          "size": 1392686,
          "sha512": "54657e374d47825d05f4df1cd76b56f2ca18043770cb018cc648272861bce6ae6f4e0024cdef842ea53bf8b4218a65573b138e9fcb776c7cc0b77352fa0f14bd",
          "sha256": "61b4584ad3978050154c0c59a64d8cccadf7da73b7535fdd0d5293bc2321a839",
          "sha1": "6fce51956e71cd6fc14d76569e7854fd52d01b4c",
          "md5": "e14a07f45e60cf63ef3114eb757e7793"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-0.0.8-sources.jar",
          "url": "utils-0.0.8-sources.jar",
          "size": 1962,
          "sha512": "90a6256be2a5a3e37be90a335cae34b89986c2a0d65f518054632ae53d6259323673ed570004d2c0d2dbe5fbf1f67b34f66e0249871c9fb489a4e7032d33a842",
          "sha256": "4db5e1f47fb49a50c08c3677ea7aea7a627978a71a2e939618d69c805a944114",
          "sha1": "ecc2be3b71b0735ec6c29360e184dd938c15f7dc",
          "md5": "c352dddf4d9cd61cae35418c1a9a00bf"
        }
      ]
    }
  ]
}
