{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "utils",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.8.aar",
          "url": "utils-0.0.8.aar",
          "size": 1404513,
          "sha512": "1a2b2b3d6127344eba28c2eb7d4e11c3b8bbe8575cf17ea81e3f353929b9b1d20bbb7d0d32f7afc308eea56f849b137ca195f74b90a2f1199ebb5b7a7ea23d70",
          "sha256": "5950271535d6a412784a904c4b0f117f208618d0c567644702a25209d05c7e58",
          "sha1": "68e61857638db3a17f87e0317ca9f559726f58f5",
          "md5": "eccf40ea159a46c74a8b1d9170ae20a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.8.aar",
          "url": "utils-0.0.8.aar",
          "size": 1404513,
          "sha512": "1a2b2b3d6127344eba28c2eb7d4e11c3b8bbe8575cf17ea81e3f353929b9b1d20bbb7d0d32f7afc308eea56f849b137ca195f74b90a2f1199ebb5b7a7ea23d70",
          "sha256": "5950271535d6a412784a904c4b0f117f208618d0c567644702a25209d05c7e58",
          "sha1": "68e61857638db3a17f87e0317ca9f559726f58f5",
          "md5": "eccf40ea159a46c74a8b1d9170ae20a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-0.0.8-sources.jar",
          "url": "utils-0.0.8-sources.jar",
          "size": 1962,
          "sha512": "90a6256be2a5a3e37be90a335cae34b89986c2a0d65f518054632ae53d6259323673ed570004d2c0d2dbe5fbf1f67b34f66e0249871c9fb489a4e7032d33a842",
          "sha256": "4db5e1f47fb49a50c08c3677ea7aea7a627978a71a2e939618d69c805a944114",
          "sha1": "ecc2be3b71b0735ec6c29360e184dd938c15f7dc",
          "md5": "c352dddf4d9cd61cae35418c1a9a00bf"
        }
      ]
    }
  ]
}
