{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "fullpanels",
    "version": "1.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.bylazar",
          "module": "panels",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "opmodecontrol",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "telemetry",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "configurables",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "themes",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "capture",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "limelightproxy",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "gamepad",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "field",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.bylazar",
          "module": "docs",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "battery",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "utils",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "pinger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "graph",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "lights",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "camerastream",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-1.0.11.aar",
          "url": "fullpanels-1.0.11.aar",
          "size": 91092,
          "sha512": "27b77280e3068d332ccb96712147006e8ffc9fa96a3c52b4a43213dbc7a57610fdfea587257dd32d3abce06104faa5cda5ba8cfdbc9362e6085bb2bc0dfca120",
          "sha256": "513777227950f23a1a0a240841285a3e34a779c9669810d985281049bec6e3ed",
          "sha1": "9d0367ea54b2df09e1510a0d9e2fb3459902eae1",
          "md5": "45599407070f5b4f9aa1fa0c87eb1ef8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.bylazar",
          "module": "panels",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "opmodecontrol",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "telemetry",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "configurables",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "themes",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "capture",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "limelightproxy",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "gamepad",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "field",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.bylazar",
          "module": "docs",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "battery",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "utils",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "pinger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "graph",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.bylazar",
          "module": "lights",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "camerastream",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-1.0.11.aar",
          "url": "fullpanels-1.0.11.aar",
          "size": 91092,
          "sha512": "27b77280e3068d332ccb96712147006e8ffc9fa96a3c52b4a43213dbc7a57610fdfea587257dd32d3abce06104faa5cda5ba8cfdbc9362e6085bb2bc0dfca120",
          "sha256": "513777227950f23a1a0a240841285a3e34a779c9669810d985281049bec6e3ed",
          "sha1": "9d0367ea54b2df09e1510a0d9e2fb3459902eae1",
          "md5": "45599407070f5b4f9aa1fa0c87eb1ef8"
        }
      ]
    }
  ]
}
