{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "limelightproxy",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.14.aar",
          "url": "limelightproxy-0.0.14.aar",
          "size": 245852,
          "sha512": "3fd08cf07d29a5729d0b375438ae627ad8239cc1dff66cd9a10a1ca32dcd6d7d9405d0f81c3cf8132146e1eafd5d6b206213a8ee2a7e27a8e8c143e661318c8e",
          "sha256": "933b0f149ad3fb1a08cb5d3ffb675b794efbc7aa81d0fed57bd9ffe8841e7bd4",
          "sha1": "9eb336ea1dd694fe544ac23adc6040ffde50d39b",
          "md5": "0fea8e19b7ebe0a6c9378fc5b18adbc9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.14.aar",
          "url": "limelightproxy-0.0.14.aar",
          "size": 245852,
          "sha512": "3fd08cf07d29a5729d0b375438ae627ad8239cc1dff66cd9a10a1ca32dcd6d7d9405d0f81c3cf8132146e1eafd5d6b206213a8ee2a7e27a8e8c143e661318c8e",
          "sha256": "933b0f149ad3fb1a08cb5d3ffb675b794efbc7aa81d0fed57bd9ffe8841e7bd4",
          "sha1": "9eb336ea1dd694fe544ac23adc6040ffde50d39b",
          "md5": "0fea8e19b7ebe0a6c9378fc5b18adbc9"
        }
      ]
    }
  ]
}
