{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "opmodecontrol",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.3.aar",
          "url": "opmodecontrol-0.0.3.aar",
          "size": 729004,
          "sha512": "e4067e120cae2d7405ee317aa104958d5ebbe5f1b9f8aebf728e7f37d7a83170b62100476858133ec54d288cb33387c33161edc3e4381a1fb91e2621e026401a",
          "sha256": "ee68ad12dd4f5e112850f7bb26094aaf2325ade669aaee87b1c3375ac7c86ef3",
          "sha1": "ebef25c16b6149cf91a8af07bc132b62a6e31add",
          "md5": "f0e2185a7d7cf3c49343cfe7064fd0f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.3.aar",
          "url": "opmodecontrol-0.0.3.aar",
          "size": 729004,
          "sha512": "e4067e120cae2d7405ee317aa104958d5ebbe5f1b9f8aebf728e7f37d7a83170b62100476858133ec54d288cb33387c33161edc3e4381a1fb91e2621e026401a",
          "sha256": "ee68ad12dd4f5e112850f7bb26094aaf2325ade669aaee87b1c3375ac7c86ef3",
          "sha1": "ebef25c16b6149cf91a8af07bc132b62a6e31add",
          "md5": "f0e2185a7d7cf3c49343cfe7064fd0f3"
        }
      ]
    }
  ]
}
