{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "ftcontrol",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.5.0.aar",
          "url": "ftcontrol-0.5.0.aar",
          "size": 29987737,
          "sha512": "220c9d888dc0259f44a321919d896e3fc524ac9cda7848d77786158f04c9c8918b980c421a3b446ed4cc01e4151f05735b69952f40a69ab56b6932b13271f04e",
          "sha256": "6adbdd1ecffd3085b2c5079917da651cdacd694e6bb6043b5ed27f5eae61ff6f",
          "sha1": "dc49c8fbf2d64b2369264a496f01e7b21313ad86",
          "md5": "b5d6c28cdc0ea2ef515a686ace32bb26"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.5.0.aar",
          "url": "ftcontrol-0.5.0.aar",
          "size": 29987737,
          "sha512": "220c9d888dc0259f44a321919d896e3fc524ac9cda7848d77786158f04c9c8918b980c421a3b446ed4cc01e4151f05735b69952f40a69ab56b6932b13271f04e",
          "sha256": "6adbdd1ecffd3085b2c5079917da651cdacd694e6bb6043b5ed27f5eae61ff6f",
          "sha1": "dc49c8fbf2d64b2369264a496f01e7b21313ad86",
          "md5": "b5d6c28cdc0ea2ef515a686ace32bb26"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftcontrol-0.5.0-sources.jar",
          "url": "ftcontrol-0.5.0-sources.jar",
          "size": 87927,
          "sha512": "0b1a1fe10324cfb61da16bb76b300e3785a1ad12a2859f62f59374c3d290d3dcecf13994edf87eef08d6ed2bfa03390089572d1257e90e4f3b3432f654cef8f3",
          "sha256": "0a50f5cfc0c8892fda2372ee106c91fe8dab38c203766f26a99354b759f5b717",
          "sha1": "08a036a55bfbc996ab1b44f07774a3d0a0dfa013",
          "md5": "926274f8c3b1661029b226c3e3e6f547"
        }
      ]
    }
  ]
}
