{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "telemetry",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.14.aar",
          "url": "telemetry-0.0.14.aar",
          "size": 235638,
          "sha512": "2ca62feaf990ed920eb12eba0c7d5871a8f6534b458fcd900f5a2120b263a5a9e1ff55ec2ef67b2caaf193f018f52c5aab5bee36bed2343039fd4918ca049900",
          "sha256": "41a76240da1db7c46ef902d31265b6cf4c7bc1ac6a19dd75d58844f908396646",
          "sha1": "71aecd23265efee07d475feb30354f99df9d03f5",
          "md5": "922b7052da988ce4772b556c41941cff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.14.aar",
          "url": "telemetry-0.0.14.aar",
          "size": 235638,
          "sha512": "2ca62feaf990ed920eb12eba0c7d5871a8f6534b458fcd900f5a2120b263a5a9e1ff55ec2ef67b2caaf193f018f52c5aab5bee36bed2343039fd4918ca049900",
          "sha256": "41a76240da1db7c46ef902d31265b6cf4c7bc1ac6a19dd75d58844f908396646",
          "sha1": "71aecd23265efee07d475feb30354f99df9d03f5",
          "md5": "922b7052da988ce4772b556c41941cff"
        }
      ]
    }
  ]
}
