{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "field",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.4.aar",
          "url": "field-0.0.4.aar",
          "size": 747025,
          "sha512": "c75931ec9597b47766deea429b91d4d175c1c36e35098ef557600c86c7dda96b9969c69e28531f8594a02c22f20c7171e837fb2927bf489fc0ee5784e87ea2f6",
          "sha256": "bf88093648098363c0734ba5f7bdc93b5d3c7fbe2d393a433030441b9033da87",
          "sha1": "2b1d7419b03fecb6592afe165181929e63ab697b",
          "md5": "b83247d31e0f8c083d3e91b7de6d20e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.4.aar",
          "url": "field-0.0.4.aar",
          "size": 747025,
          "sha512": "c75931ec9597b47766deea429b91d4d175c1c36e35098ef557600c86c7dda96b9969c69e28531f8594a02c22f20c7171e837fb2927bf489fc0ee5784e87ea2f6",
          "sha256": "bf88093648098363c0734ba5f7bdc93b5d3c7fbe2d393a433030441b9033da87",
          "sha1": "2b1d7419b03fecb6592afe165181929e63ab697b",
          "md5": "b83247d31e0f8c083d3e91b7de6d20e4"
        }
      ]
    }
  ]
}
