{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "capture",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.6.aar",
          "url": "capture-0.0.6.aar",
          "size": 1427914,
          "sha512": "2ba6c882a7853460bdee9cff9a7c7ab7b00b847a74a52ff34b218cbc797f60a103982deede7624b93efccfb1e860a0a3ca0c5829e74a2c2ba751fd3e9526742a",
          "sha256": "2de05a2681fd7058c27f3dd1e73ab12a9d984400c21fd1c2ccdffe717fe122da",
          "sha1": "1997c23932b108e3e5faaa67dae9496df8ae747f",
          "md5": "93e6ef59133450438b6fc2bbde6f755c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.6.aar",
          "url": "capture-0.0.6.aar",
          "size": 1427914,
          "sha512": "2ba6c882a7853460bdee9cff9a7c7ab7b00b847a74a52ff34b218cbc797f60a103982deede7624b93efccfb1e860a0a3ca0c5829e74a2c2ba751fd3e9526742a",
          "sha256": "2de05a2681fd7058c27f3dd1e73ab12a9d984400c21fd1c2ccdffe717fe122da",
          "sha1": "1997c23932b108e3e5faaa67dae9496df8ae747f",
          "md5": "93e6ef59133450438b6fc2bbde6f755c"
        }
      ]
    }
  ]
}
