{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "capture",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.6.aar",
          "url": "capture-0.0.6.aar",
          "size": 1426481,
          "sha512": "8e18a7b8bcda38e376c274d8bbf83b866133417e72838ebc37148c85ccbe6c23b757cba05d7885f364b0b3876aa06a7187bb8e285a4626181493ba2d3efed278",
          "sha256": "632fde6b0723b942bccddf729d415d142ec38df69f039351a6353dc813dd3fa2",
          "sha1": "240660d2e8f2f90676a024921fce2352649b173a",
          "md5": "75da8de1b05540498df805ba18dabfc6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.6.aar",
          "url": "capture-0.0.6.aar",
          "size": 1426481,
          "sha512": "8e18a7b8bcda38e376c274d8bbf83b866133417e72838ebc37148c85ccbe6c23b757cba05d7885f364b0b3876aa06a7187bb8e285a4626181493ba2d3efed278",
          "sha256": "632fde6b0723b942bccddf729d415d142ec38df69f039351a6353dc813dd3fa2",
          "sha1": "240660d2e8f2f90676a024921fce2352649b173a",
          "md5": "75da8de1b05540498df805ba18dabfc6"
        }
      ]
    }
  ]
}
