{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "capture",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.7.aar",
          "url": "capture-0.0.7.aar",
          "size": 1596689,
          "sha512": "a76ca6ada60fa5a3f714fe7fac063396f58029791ab170960946a82b7b82356e78ce50f548523713f0d7d5980ee00dac9244589458e4e100b3c479bde22eeca9",
          "sha256": "019aae5835b1e6cdf9922d25e9341c9034c63a660d7aba9b8bb1e141b78ad22f",
          "sha1": "371b95bfb95c8f780951aaf6e2b9c74302f084e0",
          "md5": "8d3bfefbea0a14422f9af2ae1859862a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.7.aar",
          "url": "capture-0.0.7.aar",
          "size": 1596689,
          "sha512": "a76ca6ada60fa5a3f714fe7fac063396f58029791ab170960946a82b7b82356e78ce50f548523713f0d7d5980ee00dac9244589458e4e100b3c479bde22eeca9",
          "sha256": "019aae5835b1e6cdf9922d25e9341c9034c63a660d7aba9b8bb1e141b78ad22f",
          "sha1": "371b95bfb95c8f780951aaf6e2b9c74302f084e0",
          "md5": "8d3bfefbea0a14422f9af2ae1859862a"
        }
      ]
    }
  ]
}
