{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "capture",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.7.aar",
          "url": "capture-0.0.7.aar",
          "size": 1603133,
          "sha512": "494fbbaa9b5b8699c50f76e0622a0b44027897607d2f87eaff95d645030b33ee7c59890693c518d4abec827a5ec91d3986d532cb3eadb4973117af6925ba66d3",
          "sha256": "e56878869af9ff6a5ce367435de6a201fec1e6a8f269b720336ddd256e6dbd46",
          "sha1": "90c6efdfde79bf23c9977e4c5a431c60f819f760",
          "md5": "3f9d255f00a12fe7050d8c7ac633af46"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.7.aar",
          "url": "capture-0.0.7.aar",
          "size": 1603133,
          "sha512": "494fbbaa9b5b8699c50f76e0622a0b44027897607d2f87eaff95d645030b33ee7c59890693c518d4abec827a5ec91d3986d532cb3eadb4973117af6925ba66d3",
          "sha256": "e56878869af9ff6a5ce367435de6a201fec1e6a8f269b720336ddd256e6dbd46",
          "sha1": "90c6efdfde79bf23c9977e4c5a431c60f819f760",
          "md5": "3f9d255f00a12fe7050d8c7ac633af46"
        }
      ]
    }
  ]
}
