{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-1.0.6.aar",
          "url": "panels-1.0.6.aar",
          "size": 747222,
          "sha512": "433e1b53bcea66411c2e754597d048df72a8afb6a1a824f2fda6939eeb212976528f27a4ca5ba0a1eb0047e52f4b9c18d4bff03ddfe0ff0c37092a8f0c3ef5e0",
          "sha256": "6aeb1674fdcc0df94c270288b6fcd9b8a5cea649304096aa2c373391c5ce07b5",
          "sha1": "9ad0f2768d934267603bc6bbcb1e8943235b2e4c",
          "md5": "e26a0fdc4681a42b66e477440e55e964"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-1.0.6.aar",
          "url": "panels-1.0.6.aar",
          "size": 747222,
          "sha512": "433e1b53bcea66411c2e754597d048df72a8afb6a1a824f2fda6939eeb212976528f27a4ca5ba0a1eb0047e52f4b9c18d4bff03ddfe0ff0c37092a8f0c3ef5e0",
          "sha256": "6aeb1674fdcc0df94c270288b6fcd9b8a5cea649304096aa2c373391c5ce07b5",
          "sha1": "9ad0f2768d934267603bc6bbcb1e8943235b2e4c",
          "md5": "e26a0fdc4681a42b66e477440e55e964"
        }
      ]
    }
  ]
}
