{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "battery",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.5.aar",
          "url": "battery-0.0.5.aar",
          "size": 373001,
          "sha512": "2186a2abb85fae38e053b19898da87b1b4db476a246481e214cd5dc1710ef9eca45b4f2ce1750193f30e180c0d95c689434ddae5c55e392d9d5fa8a465aa6ef9",
          "sha256": "992d3eb6abd7b208ceb25d48e3c7327ac4a5c6122a78b3d81745348b2621d219",
          "sha1": "de69a0cd3626e550ef6fda626a8e2324078e0a3a",
          "md5": "aae1054fafc73ec3c1a195591705a233"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.5.aar",
          "url": "battery-0.0.5.aar",
          "size": 373001,
          "sha512": "2186a2abb85fae38e053b19898da87b1b4db476a246481e214cd5dc1710ef9eca45b4f2ce1750193f30e180c0d95c689434ddae5c55e392d9d5fa8a465aa6ef9",
          "sha256": "992d3eb6abd7b208ceb25d48e3c7327ac4a5c6122a78b3d81745348b2621d219",
          "sha1": "de69a0cd3626e550ef6fda626a8e2324078e0a3a",
          "md5": "aae1054fafc73ec3c1a195591705a233"
        }
      ]
    }
  ]
}
