{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "field",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.9.aar",
          "url": "field-0.0.9.aar",
          "size": 1104003,
          "sha512": "276ca6dd2079da63ad14afda16f8ffcd9fdc97fc70a322caea022f6ec3198fc1e048807f63afb9725dab9d825d3ca403fc56adcb9c6fcd1d7c6a8ab98e1ae8d8",
          "sha256": "bfc7eb368adceb96e20436694a16f7ac66e704d38570487c960c2165fb50b884",
          "sha1": "701be2fc9687f16273c9f5f9d103cc3b923c30cf",
          "md5": "483e27296b6b9a36e97128ae58993b8e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.9.aar",
          "url": "field-0.0.9.aar",
          "size": 1104003,
          "sha512": "276ca6dd2079da63ad14afda16f8ffcd9fdc97fc70a322caea022f6ec3198fc1e048807f63afb9725dab9d825d3ca403fc56adcb9c6fcd1d7c6a8ab98e1ae8d8",
          "sha256": "bfc7eb368adceb96e20436694a16f7ac66e704d38570487c960c2165fb50b884",
          "sha1": "701be2fc9687f16273c9f5f9d103cc3b923c30cf",
          "md5": "483e27296b6b9a36e97128ae58993b8e"
        }
      ]
    }
  ]
}
