{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "field",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.9.aar",
          "url": "field-0.0.9.aar",
          "size": 753185,
          "sha512": "b6d67b7dc4259a43c0be2fe977682b900034073c1d26c3cb50c5ca07ee0f553b86159e716edb2ff485898b600eb01b5f9babb46919e6511a567920a971e57234",
          "sha256": "f22d4eb81935e2bfbff9f1e334277c8500004d830557ebcb395839d14d0943db",
          "sha1": "1271d1fc06805eefd98cffab9de8c06397fe50b4",
          "md5": "fd9b558878b48b41689e0b65d31f2c47"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.9.aar",
          "url": "field-0.0.9.aar",
          "size": 753185,
          "sha512": "b6d67b7dc4259a43c0be2fe977682b900034073c1d26c3cb50c5ca07ee0f553b86159e716edb2ff485898b600eb01b5f9babb46919e6511a567920a971e57234",
          "sha256": "f22d4eb81935e2bfbff9f1e334277c8500004d830557ebcb395839d14d0943db",
          "sha1": "1271d1fc06805eefd98cffab9de8c06397fe50b4",
          "md5": "fd9b558878b48b41689e0b65d31f2c47"
        }
      ]
    }
  ]
}
