{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "capture",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.9.aar",
          "url": "capture-0.0.9.aar",
          "size": 1603161,
          "sha512": "1eac0c1d25c3e98d6e00f10aeee7fc2c1120c289756cb13c3d8430b532e84f89e769fc7f931d9bfdb6ff1fd8959a0b721a3639ad8d2b5f80686747739b8f9a49",
          "sha256": "57175017ea40c5b6aa16a068374c28dcf701332770dfbef313fa3d24a25e734b",
          "sha1": "243c67519b04a29821b30da46ef52644e6237649",
          "md5": "166b71db358718de70101ebf709a92f0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.9.aar",
          "url": "capture-0.0.9.aar",
          "size": 1603161,
          "sha512": "1eac0c1d25c3e98d6e00f10aeee7fc2c1120c289756cb13c3d8430b532e84f89e769fc7f931d9bfdb6ff1fd8959a0b721a3639ad8d2b5f80686747739b8f9a49",
          "sha256": "57175017ea40c5b6aa16a068374c28dcf701332770dfbef313fa3d24a25e734b",
          "sha1": "243c67519b04a29821b30da46ef52644e6237649",
          "md5": "166b71db358718de70101ebf709a92f0"
        }
      ]
    }
  ]
}
