{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "configurables",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.2.aar",
          "url": "configurables-0.0.2.aar",
          "size": 163239,
          "sha512": "f667115811c48201b9dd2f23ecc06a93b4ac00f06ad7c0d1e261cb38b0eae371254d8632f4796e8086aa35e88e3ab05ac600d14ecd3dc7da305b9390267d993e",
          "sha256": "28ba76ccc29adce71d2c20dfa1ff570ba7e8d6fbbb07e9df115429bdae3af3b8",
          "sha1": "85eb51041175aec68e1c4ddc570cb7786f47b398",
          "md5": "c40df0f9a7d5d911ebc539138bcff55e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.2.aar",
          "url": "configurables-0.0.2.aar",
          "size": 163239,
          "sha512": "f667115811c48201b9dd2f23ecc06a93b4ac00f06ad7c0d1e261cb38b0eae371254d8632f4796e8086aa35e88e3ab05ac600d14ecd3dc7da305b9390267d993e",
          "sha256": "28ba76ccc29adce71d2c20dfa1ff570ba7e8d6fbbb07e9df115429bdae3af3b8",
          "sha1": "85eb51041175aec68e1c4ddc570cb7786f47b398",
          "md5": "c40df0f9a7d5d911ebc539138bcff55e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "configurables-0.0.2-sources.jar",
          "url": "configurables-0.0.2-sources.jar",
          "size": 27961,
          "sha512": "d25b7e2830825ac66efe8b91da042504eb5a3a1fce7726d90ee6931af11d8bf95b41549a416d079f9f152cf3534d5db9dbe473e58cbcebea0e105f1528847ea0",
          "sha256": "f9eb1ea30b237f4de4e2ffbefe110bd5cbcc4acb5c7d0ac67a2f04f21a359254",
          "sha1": "a9613ecf0cf40d1b94a70f67454b3d34878fca90",
          "md5": "a51629698b61e44f6c947b89883c4276"
        }
      ]
    }
  ]
}
