{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "battery",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.6.aar",
          "url": "battery-0.0.6.aar",
          "size": 372707,
          "sha512": "6ff43f8ecb28e95bf5b12712c3c5414000f20a1f0afdf687ff26f354b145e96ee8fb317cbedb6b1f1503b502e64b415862bf472d66c80546eaa4835d61fbd4f2",
          "sha256": "51cddcc962c45de8f45c62e32e58e9dbe5950f0a51ee2f1254ae65ee12eba2a5",
          "sha1": "7f331cbacd84d75feb92fb2f848b9e3eebcc79b7",
          "md5": "dfd2b2f6ec1b49cec48d06ef9a8a69d3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.6.aar",
          "url": "battery-0.0.6.aar",
          "size": 372707,
          "sha512": "6ff43f8ecb28e95bf5b12712c3c5414000f20a1f0afdf687ff26f354b145e96ee8fb317cbedb6b1f1503b502e64b415862bf472d66c80546eaa4835d61fbd4f2",
          "sha256": "51cddcc962c45de8f45c62e32e58e9dbe5950f0a51ee2f1254ae65ee12eba2a5",
          "sha1": "7f331cbacd84d75feb92fb2f848b9e3eebcc79b7",
          "md5": "dfd2b2f6ec1b49cec48d06ef9a8a69d3"
        }
      ]
    }
  ]
}
