{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "opmodecontrol",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.8.aar",
          "url": "opmodecontrol-0.0.8.aar",
          "size": 905672,
          "sha512": "f94189779d288b099c66eec90c69f405e9d23df94047323ac5144d47dc83ea4e8fb22d7dad1274a310f020a6945f7ff1f28a4acaec83fa1a6154975a7ebdbb97",
          "sha256": "8722f87a92c3dd4b7a9139b3ef6a534e5a5054c6d5114b88178ff6cb4d9913ef",
          "sha1": "60e4997a3a999661ea5ff8a2a52a1355c121b4e0",
          "md5": "852cef21e7897c1f24e995002fd7633a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.8.aar",
          "url": "opmodecontrol-0.0.8.aar",
          "size": 905672,
          "sha512": "f94189779d288b099c66eec90c69f405e9d23df94047323ac5144d47dc83ea4e8fb22d7dad1274a310f020a6945f7ff1f28a4acaec83fa1a6154975a7ebdbb97",
          "sha256": "8722f87a92c3dd4b7a9139b3ef6a534e5a5054c6d5114b88178ff6cb4d9913ef",
          "sha1": "60e4997a3a999661ea5ff8a2a52a1355c121b4e0",
          "md5": "852cef21e7897c1f24e995002fd7633a"
        }
      ]
    }
  ]
}
