{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "telemetry",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-1.0.7.aar",
          "url": "telemetry-1.0.7.aar",
          "size": 60211,
          "sha512": "da6aba21e38a5ae81ecf99d4827a5b9d2eb12c0abba984c9e502515e91f1a162043b8cce02443204098e726b9eff4916bc02f482d4c8ab0054dc1c521c2fb588",
          "sha256": "4dbf2d59d6a2f2ec6f31c1e3990539819db67e6f9b0e3715143b663ace02ef42",
          "sha1": "15549081fd6332707e9f2f7080ffeb476d0d737e",
          "md5": "56d508e9a7294be6c2576f78d65dff33"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-1.0.7.aar",
          "url": "telemetry-1.0.7.aar",
          "size": 60211,
          "sha512": "da6aba21e38a5ae81ecf99d4827a5b9d2eb12c0abba984c9e502515e91f1a162043b8cce02443204098e726b9eff4916bc02f482d4c8ab0054dc1c521c2fb588",
          "sha256": "4dbf2d59d6a2f2ec6f31c1e3990539819db67e6f9b0e3715143b663ace02ef42",
          "sha1": "15549081fd6332707e9f2f7080ffeb476d0d737e",
          "md5": "56d508e9a7294be6c2576f78d65dff33"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "telemetry-1.0.7-sources.jar",
          "url": "telemetry-1.0.7-sources.jar",
          "size": 4097,
          "sha512": "e6bcd7106a581da2cb355a0b32af5de9354af7ec1f9ec6e963889da86b843764965bd6b388e02ca5b574f24c6df00afbb8f2f51eddfb9e1d305babe44390bec4",
          "sha256": "dea99e33a742b08966f35af4d0d2f19198c15ca902d5f9765801b30037d6efd7",
          "sha1": "7d1a03ba8ebb670bd2287882c609c8c2316dc211",
          "md5": "60351e0132b64c613b6ecc582c0fe642"
        }
      ]
    }
  ]
}
