{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "exampleplugin",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.6.aar",
          "url": "exampleplugin-0.0.6.aar",
          "size": 82658,
          "sha512": "0b96523e4b62209022e69feb716fe2dcb15eaef2c90fd2c59889a4a3f6c02da31b8e91d75c3989eb6663a13ce81d6908e7a0fec35a00e0a7fcf17bad65d1229a",
          "sha256": "f8d4f1c5cf67564087667ce26a3cdc52cb5ac06335b32ac26797f6a1d8874c8a",
          "sha1": "fd1d0283647f36b20d34399b76ef83656a4eea70",
          "md5": "6ee13af50e6a1afe44a9e79219ed6d12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.6.aar",
          "url": "exampleplugin-0.0.6.aar",
          "size": 82658,
          "sha512": "0b96523e4b62209022e69feb716fe2dcb15eaef2c90fd2c59889a4a3f6c02da31b8e91d75c3989eb6663a13ce81d6908e7a0fec35a00e0a7fcf17bad65d1229a",
          "sha256": "f8d4f1c5cf67564087667ce26a3cdc52cb5ac06335b32ac26797f6a1d8874c8a",
          "sha1": "fd1d0283647f36b20d34399b76ef83656a4eea70",
          "md5": "6ee13af50e6a1afe44a9e79219ed6d12"
        }
      ]
    }
  ]
}
