{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "exampleplugin",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.6.aar",
          "url": "exampleplugin-0.0.6.aar",
          "size": 417257,
          "sha512": "0b49d63502e1be5bf32de7f6082d43278503d686c89055f132b6c1fec504e69df4aa88f6f7ceefa82b3da6918c8d4b556b0fde1f6cfa19b141323d449076b96e",
          "sha256": "9ac3532933598ffbe6e9b5d58385b85c0c2aef1f860a35b3607c18983c33b9c8",
          "sha1": "d626693c6a55765a9bdf25791dab4a8b4dae1eb0",
          "md5": "367d6e20ae37f3c23b190c52a773d3e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.6.aar",
          "url": "exampleplugin-0.0.6.aar",
          "size": 417257,
          "sha512": "0b49d63502e1be5bf32de7f6082d43278503d686c89055f132b6c1fec504e69df4aa88f6f7ceefa82b3da6918c8d4b556b0fde1f6cfa19b141323d449076b96e",
          "sha256": "9ac3532933598ffbe6e9b5d58385b85c0c2aef1f860a35b3607c18983c33b9c8",
          "sha1": "d626693c6a55765a9bdf25791dab4a8b4dae1eb0",
          "md5": "367d6e20ae37f3c23b190c52a773d3e0"
        }
      ]
    }
  ]
}
