{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "fullpanels",
    "version": "0.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.bylazar",
          "module": "panels",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.bylazar",
          "module": "opmodecontrol",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "telemetry",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "configurables",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "themes",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "capture",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "limelightproxy",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "gamepad",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "field",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "docs",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "battery",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "utils",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-0.0.18.aar",
          "url": "fullpanels-0.0.18.aar",
          "size": 64541,
          "sha512": "124a4c2779cd07d0d0a43c15336c17c3c3a7093d6d2eeca11a12857195034fcca4aae6e9f40de6d050ca5da778a93c7d0e6c243c494f54e2eeb1ad7b36915374",
          "sha256": "87f26a5f465331038522e7187a9d5ea0cc88cd950e618f85825e6bdd39ea2148",
          "sha1": "822ecac9b18d245e985cdc01a418859dae49f676",
          "md5": "111df7ed4136f8899b37d96505d2b52d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.bylazar",
          "module": "panels",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.bylazar",
          "module": "opmodecontrol",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "telemetry",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "configurables",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "themes",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "capture",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "limelightproxy",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.bylazar",
          "module": "gamepad",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "field",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "docs",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "battery",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.bylazar",
          "module": "utils",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-0.0.18.aar",
          "url": "fullpanels-0.0.18.aar",
          "size": 64541,
          "sha512": "124a4c2779cd07d0d0a43c15336c17c3c3a7093d6d2eeca11a12857195034fcca4aae6e9f40de6d050ca5da778a93c7d0e6c243c494f54e2eeb1ad7b36915374",
          "sha256": "87f26a5f465331038522e7187a9d5ea0cc88cd950e618f85825e6bdd39ea2148",
          "sha1": "822ecac9b18d245e985cdc01a418859dae49f676",
          "md5": "111df7ed4136f8899b37d96505d2b52d"
        }
      ]
    }
  ]
}
