{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "battery",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-1.0.0.aar",
          "url": "battery-1.0.0.aar",
          "size": 523113,
          "sha512": "624da506a4707b9135efcd51ae8ec49f93870514dfe057e8193de0c0d8bed0da4a7aced7e2bd7b89dbf85027d61307364232fd10ea86b920a2996e5f7fdad5ee",
          "sha256": "2a2c31c584b9a6ec3b305125ace5b5434d289592a89da618c2d347899ba71aaf",
          "sha1": "b365ff38c8ec963454b2a5cb07968af88d23863f",
          "md5": "561c1af0d5e7671a5a7b454929ad39ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-1.0.0.aar",
          "url": "battery-1.0.0.aar",
          "size": 523113,
          "sha512": "624da506a4707b9135efcd51ae8ec49f93870514dfe057e8193de0c0d8bed0da4a7aced7e2bd7b89dbf85027d61307364232fd10ea86b920a2996e5f7fdad5ee",
          "sha256": "2a2c31c584b9a6ec3b305125ace5b5434d289592a89da618c2d347899ba71aaf",
          "sha1": "b365ff38c8ec963454b2a5cb07968af88d23863f",
          "md5": "561c1af0d5e7671a5a7b454929ad39ce"
        }
      ]
    }
  ]
}
