{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "opmodecontrol",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-1.0.1.aar",
          "url": "opmodecontrol-1.0.1.aar",
          "size": 1037464,
          "sha512": "87520e12e6d883161467fff78d9c32ec44fa1525033a1c2fd0128d2b40ed9eef6386cd972c789c182d8ad1eb11754110091e8914e16d97912002144c5bd4d4a2",
          "sha256": "61ce6008691cdedff5b7cf38dce74ea487006c6efe8719edaa13528c7634638f",
          "sha1": "dc7bfca55d179ad74ee4994f58b3c142bfb377ac",
          "md5": "eb5b26b67085ef5b7e7960546de28840"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-1.0.1.aar",
          "url": "opmodecontrol-1.0.1.aar",
          "size": 1037464,
          "sha512": "87520e12e6d883161467fff78d9c32ec44fa1525033a1c2fd0128d2b40ed9eef6386cd972c789c182d8ad1eb11754110091e8914e16d97912002144c5bd4d4a2",
          "sha256": "61ce6008691cdedff5b7cf38dce74ea487006c6efe8719edaa13528c7634638f",
          "sha1": "dc7bfca55d179ad74ee4994f58b3c142bfb377ac",
          "md5": "eb5b26b67085ef5b7e7960546de28840"
        }
      ]
    }
  ]
}
