{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.12.aar",
          "url": "panels-0.0.12.aar",
          "size": 6130491,
          "sha512": "325f0e100c047b44691d0eef9a27c4a33fd0c3f3403eb0bfe02a0011f0ecd966153ce36b12589f79adbfd8f8c89913e993412f94fb65c221cdc474cf275a38eb",
          "sha256": "978333a638ecadbb5cb294e82cd5d8f7ce4d885ec6b55f8f25ee65898dbc5d21",
          "sha1": "d50c8e46072416551f40c0d8d33aa8e04e2ac8a4",
          "md5": "55f8f9b3e8cfde0b86b937760646ee1e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.12.aar",
          "url": "panels-0.0.12.aar",
          "size": 6130491,
          "sha512": "325f0e100c047b44691d0eef9a27c4a33fd0c3f3403eb0bfe02a0011f0ecd966153ce36b12589f79adbfd8f8c89913e993412f94fb65c221cdc474cf275a38eb",
          "sha256": "978333a638ecadbb5cb294e82cd5d8f7ce4d885ec6b55f8f25ee65898dbc5d21",
          "sha1": "d50c8e46072416551f40c0d8d33aa8e04e2ac8a4",
          "md5": "55f8f9b3e8cfde0b86b937760646ee1e"
        }
      ]
    }
  ]
}
