{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.28.aar",
          "url": "panels-0.0.28.aar",
          "size": 735999,
          "sha512": "fe68d09e5d4ea45e46318f417a794e1c5e0c00662013c0a5187ed2e01752a3ef352e113b27292934d90b1c72da5c28569664822cd9edb8686a0f841511595d5d",
          "sha256": "1f667d489aba3038bc183141088aaa9dd1150d3bab9d1c65eff5b870bd9a6a81",
          "sha1": "6e3daa1b4917671d7c4ad872fd6de97d41605494",
          "md5": "f4f263ebf370bd569e434f2c654eb872"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.28.aar",
          "url": "panels-0.0.28.aar",
          "size": 735999,
          "sha512": "fe68d09e5d4ea45e46318f417a794e1c5e0c00662013c0a5187ed2e01752a3ef352e113b27292934d90b1c72da5c28569664822cd9edb8686a0f841511595d5d",
          "sha256": "1f667d489aba3038bc183141088aaa9dd1150d3bab9d1c65eff5b870bd9a6a81",
          "sha1": "6e3daa1b4917671d7c4ad872fd6de97d41605494",
          "md5": "f4f263ebf370bd569e434f2c654eb872"
        }
      ]
    }
  ]
}
