{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "configurables",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-1.0.5.aar",
          "url": "configurables-1.0.5.aar",
          "size": 523945,
          "sha512": "89c47e0467c3b13c5dabe581085f3904ceb9900bca5ca7861f4288c0692852d929a328913b5b1c7a7caa725df6dc3cc64b999dabb9ff4f1a4574de2b7dc2192d",
          "sha256": "0554f7783236435be9cdabd272e0440f9c98970437ec868ccba5636de57ac4fd",
          "sha1": "6479e11aef97074ff7ef217ea49f22ee070c0a3c",
          "md5": "f29a9ce1380c4f5a83bf0d3f1d329a53"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-1.0.5.aar",
          "url": "configurables-1.0.5.aar",
          "size": 523945,
          "sha512": "89c47e0467c3b13c5dabe581085f3904ceb9900bca5ca7861f4288c0692852d929a328913b5b1c7a7caa725df6dc3cc64b999dabb9ff4f1a4574de2b7dc2192d",
          "sha256": "0554f7783236435be9cdabd272e0440f9c98970437ec868ccba5636de57ac4fd",
          "sha1": "6479e11aef97074ff7ef217ea49f22ee070c0a3c",
          "md5": "f29a9ce1380c4f5a83bf0d3f1d329a53"
        }
      ]
    }
  ]
}
