{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "ftcontrol",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.4.2.aar",
          "url": "ftcontrol-0.4.2.aar",
          "size": 28504839,
          "sha512": "58d66520455aa30148ba49ddd63216949b41a4a508058297d0e56cc2f25355c0c4f53a8779ef66e5306871cd93c5c9be3e74095ff191ea11c6fef9f996f6a899",
          "sha256": "f270cee8330b88f19059a1111683b35ebd09dd3604baf374535b9150496505b9",
          "sha1": "3c8d480566718eaa1f6d81f79defeff431c17013",
          "md5": "784c314408f60cd42cc6d6cbf9683895"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.4.2.aar",
          "url": "ftcontrol-0.4.2.aar",
          "size": 28504839,
          "sha512": "58d66520455aa30148ba49ddd63216949b41a4a508058297d0e56cc2f25355c0c4f53a8779ef66e5306871cd93c5c9be3e74095ff191ea11c6fef9f996f6a899",
          "sha256": "f270cee8330b88f19059a1111683b35ebd09dd3604baf374535b9150496505b9",
          "sha1": "3c8d480566718eaa1f6d81f79defeff431c17013",
          "md5": "784c314408f60cd42cc6d6cbf9683895"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftcontrol-0.4.2-sources.jar",
          "url": "ftcontrol-0.4.2-sources.jar",
          "size": 87083,
          "sha512": "9fea0bee4511448701dd047cae881112adc55d49f0faee04b5f71ae0cae83fdcbbd8b611ddae7d337fe869d6c24fa1d1397d23c389f41ca8196ac05505f1853a",
          "sha256": "71a1bef595b4bbbee8068e21b18b4c68eaacd854ef3e644496cb5778e60cf2e9",
          "sha1": "900277a80581f7af62650a150589238e65eeec1d",
          "md5": "1a7151a7adba9d02ea862523b465bb04"
        }
      ]
    }
  ]
}
