{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.15.aar",
          "url": "panels-0.0.15.aar",
          "size": 281339,
          "sha512": "d0d47e80128cc9f03746d9d481387ae48e2fe49d280aaf3dd30f094e189d7638573790db395ce1f3968487249ba24e5360debb46f776a54cecb1ea387f217652",
          "sha256": "e506f5d6adbdfbf87c0697e7c74eb11235af0efa7b8712882fe2be343ce81aea",
          "sha1": "d22f4afe38427a7565ca37b1c62e9d0286e4cbcc",
          "md5": "bfc27a0a69c68b761035cd882f695e63"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.15.aar",
          "url": "panels-0.0.15.aar",
          "size": 281339,
          "sha512": "d0d47e80128cc9f03746d9d481387ae48e2fe49d280aaf3dd30f094e189d7638573790db395ce1f3968487249ba24e5360debb46f776a54cecb1ea387f217652",
          "sha256": "e506f5d6adbdfbf87c0697e7c74eb11235af0efa7b8712882fe2be343ce81aea",
          "sha1": "d22f4afe38427a7565ca37b1c62e9d0286e4cbcc",
          "md5": "bfc27a0a69c68b761035cd882f695e63"
        }
      ]
    }
  ]
}
