{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "configurables",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.7.aar",
          "url": "configurables-0.0.7.aar",
          "size": 165727,
          "sha512": "b3ac280b2ece00d8475c223c8230a0b1e100c4df6bcbf21db4a08bfdb75f3e4a90d210bbb6200e7c606a91a52e498a7978c8ad7d772fb029a8077dea4c011190",
          "sha256": "ce502a735e891df87fc7812a3137ada8ff8d3f6794b085d1cca5af50355c7246",
          "sha1": "ffeb514941c68696c619a2a4137bad48aab363fa",
          "md5": "a13b16e802f9d602b7edf50e831fe927"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.7.aar",
          "url": "configurables-0.0.7.aar",
          "size": 165727,
          "sha512": "b3ac280b2ece00d8475c223c8230a0b1e100c4df6bcbf21db4a08bfdb75f3e4a90d210bbb6200e7c606a91a52e498a7978c8ad7d772fb029a8077dea4c011190",
          "sha256": "ce502a735e891df87fc7812a3137ada8ff8d3f6794b085d1cca5af50355c7246",
          "sha1": "ffeb514941c68696c619a2a4137bad48aab363fa",
          "md5": "a13b16e802f9d602b7edf50e831fe927"
        }
      ]
    }
  ]
}
