{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "field",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-1.0.0.aar",
          "url": "field-1.0.0.aar",
          "size": 1164054,
          "sha512": "d34d2408d95210b187ba04af2dbc64b0b0428ae4aed3fb9d319bb3f4866cd68161a2ac18b4879598ddd7a508249643aebb0b82b0fc4d94415af187db60de7eac",
          "sha256": "4c6df734dd69565d4e4cf683f2fa6c78cc4bb19979124a05a180d2fcb331bf87",
          "sha1": "701f8a64991f426b8e3688d0d131f98d1a7b4474",
          "md5": "2f07db205ab23016aff5dcc4359654ca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-1.0.0.aar",
          "url": "field-1.0.0.aar",
          "size": 1164054,
          "sha512": "d34d2408d95210b187ba04af2dbc64b0b0428ae4aed3fb9d319bb3f4866cd68161a2ac18b4879598ddd7a508249643aebb0b82b0fc4d94415af187db60de7eac",
          "sha256": "4c6df734dd69565d4e4cf683f2fa6c78cc4bb19979124a05a180d2fcb331bf87",
          "sha1": "701f8a64991f426b8e3688d0d131f98d1a7b4474",
          "md5": "2f07db205ab23016aff5dcc4359654ca"
        }
      ]
    }
  ]
}
