{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "pinger",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "pinger-0.0.4.aar",
          "url": "pinger-0.0.4.aar",
          "size": 250111,
          "sha512": "6cbdaf8dea77b3d6030485854b87b70729cf3cad7abd7c43d4c495d24fc8cf86faf0dfc46ccb336f90cd747abdec54f6d7a37b7c28bd7baa777377dc7248aa99",
          "sha256": "fb956ee3299edf642b8e8ca2306dc5d20446cb69f7327b6e692a3b4a89c8804c",
          "sha1": "ea1a090b664f5f65a52bd32c237df70455b87871",
          "md5": "0299454eac4a5c753ed21b48c648031e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "pinger-0.0.4.aar",
          "url": "pinger-0.0.4.aar",
          "size": 250111,
          "sha512": "6cbdaf8dea77b3d6030485854b87b70729cf3cad7abd7c43d4c495d24fc8cf86faf0dfc46ccb336f90cd747abdec54f6d7a37b7c28bd7baa777377dc7248aa99",
          "sha256": "fb956ee3299edf642b8e8ca2306dc5d20446cb69f7327b6e692a3b4a89c8804c",
          "sha1": "ea1a090b664f5f65a52bd32c237df70455b87871",
          "md5": "0299454eac4a5c753ed21b48c648031e"
        }
      ]
    }
  ]
}
