{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "pinger",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "pinger-0.0.4.aar",
          "url": "pinger-0.0.4.aar",
          "size": 257918,
          "sha512": "e54c8d404a79e6b9024d6e3e31ac6467b26655f01ff5ad36437353b4d9a397a86c08169fd13038f21a395b7ee45465c041b6b530790a83180e0fa1b8393681dd",
          "sha256": "9da76b04eeaaa47530eea3b0cf963f63397f9698921344d98ebd1e3c650c6c1a",
          "sha1": "f32ce4186c090c6468d7931bedaf6e937c786c64",
          "md5": "44f0928ea72796b246f3ae7d0bcc6fbc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "pinger-0.0.4.aar",
          "url": "pinger-0.0.4.aar",
          "size": 257918,
          "sha512": "e54c8d404a79e6b9024d6e3e31ac6467b26655f01ff5ad36437353b4d9a397a86c08169fd13038f21a395b7ee45465c041b6b530790a83180e0fa1b8393681dd",
          "sha256": "9da76b04eeaaa47530eea3b0cf963f63397f9698921344d98ebd1e3c650c6c1a",
          "sha1": "f32ce4186c090c6468d7931bedaf6e937c786c64",
          "md5": "44f0928ea72796b246f3ae7d0bcc6fbc"
        }
      ]
    }
  ]
}
