{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "limelightproxy",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-1.0.4.aar",
          "url": "limelightproxy-1.0.4.aar",
          "size": 1522356,
          "sha512": "5113ba8ece9581f170c1cce9c4dfce392a6f21b6ddf462fc4ea8c9e8cb180badd606cef567b562ccb5b07f1c6d770867544f1fbccefc7983f4d64bef4e600d29",
          "sha256": "f42f0db718a76ae8785d1eeb13f9ae12536942a11be6f703dc546bde7ac6c4d7",
          "sha1": "d2eaf00caf6c6890b82795cc0cd6ae9f37b5fa02",
          "md5": "a2267c977bdfd0ca1ddc0d0aaf3b0df4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-1.0.4.aar",
          "url": "limelightproxy-1.0.4.aar",
          "size": 1522356,
          "sha512": "5113ba8ece9581f170c1cce9c4dfce392a6f21b6ddf462fc4ea8c9e8cb180badd606cef567b562ccb5b07f1c6d770867544f1fbccefc7983f4d64bef4e600d29",
          "sha256": "f42f0db718a76ae8785d1eeb13f9ae12536942a11be6f703dc546bde7ac6c4d7",
          "sha1": "d2eaf00caf6c6890b82795cc0cd6ae9f37b5fa02",
          "md5": "a2267c977bdfd0ca1ddc0d0aaf3b0df4"
        }
      ]
    }
  ]
}
