{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "pinger",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "pinger-0.0.3.aar",
          "url": "pinger-0.0.3.aar",
          "size": 75468,
          "sha512": "290180d3a2c53273c00b28501e6cd120fd4261bcd9165f4c976538ea26f91756d5a29607ce8cf96c8d9ba97e7a312d85cd1f42eb415c09fe36f6252845c6c765",
          "sha256": "28d912ca2931d897bb578362c4638ae016ca41c68cb43dc9fa764b5c9f54f643",
          "sha1": "fc5cfadae03ec9e4fe8eaaf43b6355d5ca622f33",
          "md5": "9bb0209920daf7dd6f3c0ef6b41cc8c5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "pinger-0.0.3.aar",
          "url": "pinger-0.0.3.aar",
          "size": 75468,
          "sha512": "290180d3a2c53273c00b28501e6cd120fd4261bcd9165f4c976538ea26f91756d5a29607ce8cf96c8d9ba97e7a312d85cd1f42eb415c09fe36f6252845c6c765",
          "sha256": "28d912ca2931d897bb578362c4638ae016ca41c68cb43dc9fa764b5c9f54f643",
          "sha1": "fc5cfadae03ec9e4fe8eaaf43b6355d5ca622f33",
          "md5": "9bb0209920daf7dd6f3c0ef6b41cc8c5"
        }
      ]
    }
  ]
}
