{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-1.0.3.aar",
          "url": "panels-1.0.3.aar",
          "size": 748285,
          "sha512": "16e8338bf37b485e51c4ad4148c49ea43abc24ba9f91ce0e09b260a3248e891abe4d6eac09ef7c8178cd434db873e01743b2c6fd1887bba6ea6f2bd8c09874b9",
          "sha256": "74f1f055321c0e3d77f4884bde1c60ebddc44fd18f16d4bf528e574a2e500ae4",
          "sha1": "d4e98ada980a310883c8f4f34094526068262152",
          "md5": "5b75927851a261927dfab4cd9b744278"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-1.0.3.aar",
          "url": "panels-1.0.3.aar",
          "size": 748285,
          "sha512": "16e8338bf37b485e51c4ad4148c49ea43abc24ba9f91ce0e09b260a3248e891abe4d6eac09ef7c8178cd434db873e01743b2c6fd1887bba6ea6f2bd8c09874b9",
          "sha256": "74f1f055321c0e3d77f4884bde1c60ebddc44fd18f16d4bf528e574a2e500ae4",
          "sha1": "d4e98ada980a310883c8f4f34094526068262152",
          "md5": "5b75927851a261927dfab4cd9b744278"
        }
      ]
    }
  ]
}
