{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-1.0.3.aar",
          "url": "panels-1.0.3.aar",
          "size": 748277,
          "sha512": "89b0a6633270e97d6531fd6147e245c666b8ac03b6052c06ee085442932ac0031bcff11ae2d8e4650b907624676f88cd5d54d3028fa010ec71b22a50e3ee6f30",
          "sha256": "756a2d8394cdc831341dbed3d518745f0187223384d2dcd20b57550b8deed91f",
          "sha1": "f1680396e8a8d75a26090dcfccc8cf2fb7a289c1",
          "md5": "f358de95b1c341d02b03ed8c2246438b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-1.0.3.aar",
          "url": "panels-1.0.3.aar",
          "size": 748277,
          "sha512": "89b0a6633270e97d6531fd6147e245c666b8ac03b6052c06ee085442932ac0031bcff11ae2d8e4650b907624676f88cd5d54d3028fa010ec71b22a50e3ee6f30",
          "sha256": "756a2d8394cdc831341dbed3d518745f0187223384d2dcd20b57550b8deed91f",
          "sha1": "f1680396e8a8d75a26090dcfccc8cf2fb7a289c1",
          "md5": "f358de95b1c341d02b03ed8c2246438b"
        }
      ]
    }
  ]
}
