{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-1.0.3.aar",
          "url": "panels-1.0.3.aar",
          "size": 748332,
          "sha512": "3cc0e9f0b52fca0a101aebafaa9037e5eb3eb8420c0eb463e875847c94d7595d8e394bb6e3fc7183446d15b7a33b4681b765292c0c680c7028d382cb06f5b172",
          "sha256": "dea19d8cef2663fd68457b8822a52e1314cf49aabdda4f49c2e62a6090d8b842",
          "sha1": "3fe22849a01139f7a7616f103a2bfaeb94d0cc43",
          "md5": "61aa19c8242e07d7a59ce85752d4f9e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-1.0.3.aar",
          "url": "panels-1.0.3.aar",
          "size": 748332,
          "sha512": "3cc0e9f0b52fca0a101aebafaa9037e5eb3eb8420c0eb463e875847c94d7595d8e394bb6e3fc7183446d15b7a33b4681b765292c0c680c7028d382cb06f5b172",
          "sha256": "dea19d8cef2663fd68457b8822a52e1314cf49aabdda4f49c2e62a6090d8b842",
          "sha1": "3fe22849a01139f7a7616f103a2bfaeb94d0cc43",
          "md5": "61aa19c8242e07d7a59ce85752d4f9e0"
        }
      ]
    }
  ]
}
