{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "gamepad",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-1.0.0.aar",
          "url": "gamepad-1.0.0.aar",
          "size": 10417585,
          "sha512": "213307d485a1a319b64bcf4a09fde9cd86f6cf48b9309fcf01a5468a95a27658056468256f92edc4a5bc5d9f7d5e0f0231be54d3a143838561e2f3b804408c37",
          "sha256": "eff11ffb0ecf2edf14ed13f6a01faf9e2d09e89e09a6e4fca1ac68a5e816dc90",
          "sha1": "cd6dc8c5c2cd2306abb1100e1cc68108e1f755df",
          "md5": "31e54469af580e08ade139f5faef4733"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-1.0.0.aar",
          "url": "gamepad-1.0.0.aar",
          "size": 10417585,
          "sha512": "213307d485a1a319b64bcf4a09fde9cd86f6cf48b9309fcf01a5468a95a27658056468256f92edc4a5bc5d9f7d5e0f0231be54d3a143838561e2f3b804408c37",
          "sha256": "eff11ffb0ecf2edf14ed13f6a01faf9e2d09e89e09a6e4fca1ac68a5e816dc90",
          "sha1": "cd6dc8c5c2cd2306abb1100e1cc68108e1f755df",
          "md5": "31e54469af580e08ade139f5faef4733"
        }
      ]
    }
  ]
}
