{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "utils",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.7.aar",
          "url": "utils-0.0.7.aar",
          "size": 69831,
          "sha512": "d2622578683d80e3f9c281a3fad64d13ca39baa2d4196de7913ea0788e48be1fd147d05d16df13a8c91cee1e02c5b38e5e4878dd247f8bf53511e932237de584",
          "sha256": "73d92f080e62b4eed2d01477cfd50ff829a2857ff003ebf42e646cdf053595ef",
          "sha1": "7c2a4f20472c1a30667bb4014c95add54cef05c8",
          "md5": "d5a587dda9cab3068ad177518058e5c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.7.aar",
          "url": "utils-0.0.7.aar",
          "size": 69831,
          "sha512": "d2622578683d80e3f9c281a3fad64d13ca39baa2d4196de7913ea0788e48be1fd147d05d16df13a8c91cee1e02c5b38e5e4878dd247f8bf53511e932237de584",
          "sha256": "73d92f080e62b4eed2d01477cfd50ff829a2857ff003ebf42e646cdf053595ef",
          "sha1": "7c2a4f20472c1a30667bb4014c95add54cef05c8",
          "md5": "d5a587dda9cab3068ad177518058e5c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-0.0.7-sources.jar",
          "url": "utils-0.0.7-sources.jar",
          "size": 1950,
          "sha512": "ee95204818ade1e7d6bb5eeaa00aa41f7d2ff4d33cb7ff880a51282e2d98fe8f36c56fc0fa552181a3c2e1569304160883207e8e28e3c3e95a4b2d949100f010",
          "sha256": "67c69510212d892daaf2e3e26925e496d4bfa6c7d2bbe826c28bd391af29fbd6",
          "sha1": "08b9584456f88742dc5a4372205c2f6d874cf446",
          "md5": "e915ba90a9ea0e2321ae89e0d4f3663d"
        }
      ]
    }
  ]
}
