{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "telemetry",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-1.0.4.aar",
          "url": "telemetry-1.0.4.aar",
          "size": 90385,
          "sha512": "63ee25deee54280600ee3fb7398370a3f75727edd66eb939f904797a7317da5e422b85a42bbaf8e34898dcb8f5bcf91246e230085301ae626a6d48800ad700e5",
          "sha256": "257a43dd38988dc283ee8e05f8cef44f308f254ece105fb3e80c0fe4f4a7402d",
          "sha1": "c45500e06429269b9264688c9cfc6d521c8ed5d7",
          "md5": "b58d3768a68bf2d87e492c4169947417"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-1.0.4.aar",
          "url": "telemetry-1.0.4.aar",
          "size": 90385,
          "sha512": "63ee25deee54280600ee3fb7398370a3f75727edd66eb939f904797a7317da5e422b85a42bbaf8e34898dcb8f5bcf91246e230085301ae626a6d48800ad700e5",
          "sha256": "257a43dd38988dc283ee8e05f8cef44f308f254ece105fb3e80c0fe4f4a7402d",
          "sha1": "c45500e06429269b9264688c9cfc6d521c8ed5d7",
          "md5": "b58d3768a68bf2d87e492c4169947417"
        }
      ]
    }
  ]
}
