{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "themes",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.3.aar",
          "url": "themes-0.0.3.aar",
          "size": 93135,
          "sha512": "7d14fc92fda8b35e37b94f7426160404baec836621d8f0b66ed14762249091b6798879874a25b2fde3569e7749ecd0e9a7c0e6733e9e545171fddbc45a8ee8f3",
          "sha256": "c84d7d0905eba428619777c8503cc5e510f3746ae0de907331d8df291693fd13",
          "sha1": "99b6f5adc7317ade6084a1305ac77a43fafa5013",
          "md5": "282bff8eb56150c2f205341e0d6de8d3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.3.aar",
          "url": "themes-0.0.3.aar",
          "size": 93135,
          "sha512": "7d14fc92fda8b35e37b94f7426160404baec836621d8f0b66ed14762249091b6798879874a25b2fde3569e7749ecd0e9a7c0e6733e9e545171fddbc45a8ee8f3",
          "sha256": "c84d7d0905eba428619777c8503cc5e510f3746ae0de907331d8df291693fd13",
          "sha1": "99b6f5adc7317ade6084a1305ac77a43fafa5013",
          "md5": "282bff8eb56150c2f205341e0d6de8d3"
        }
      ]
    }
  ]
}
