{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "battery",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.7.aar",
          "url": "battery-0.0.7.aar",
          "size": 374218,
          "sha512": "ff3cec9328060d2a440f53d9c5a0a89dea73474a53b6782cb999746f2d5ef1cd678d5b117e0ef47e2ab322dee0085d2b75862cdb0893fcd11cbd7566a09bdf97",
          "sha256": "06907b6b10d02eaf64dbffff32ccf77ef91a969d56a1196e2af3b3e009cdb937",
          "sha1": "32381d41a932f70fc1bc6c555b04821e8a68689d",
          "md5": "cdd000483ee0fc838de143181d908281"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.7.aar",
          "url": "battery-0.0.7.aar",
          "size": 374218,
          "sha512": "ff3cec9328060d2a440f53d9c5a0a89dea73474a53b6782cb999746f2d5ef1cd678d5b117e0ef47e2ab322dee0085d2b75862cdb0893fcd11cbd7566a09bdf97",
          "sha256": "06907b6b10d02eaf64dbffff32ccf77ef91a969d56a1196e2af3b3e009cdb937",
          "sha1": "32381d41a932f70fc1bc6c555b04821e8a68689d",
          "md5": "cdd000483ee0fc838de143181d908281"
        }
      ]
    }
  ]
}
