{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "battery",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.8.aar",
          "url": "battery-0.0.8.aar",
          "size": 945804,
          "sha512": "18e482341a07cceb01baa330ff2dbf4f87381583e8cdf23e9195c49f106db32721b231e592d69bef30a8335283c6bcd4c81e18bc7d1bb749d4bc844402aaed0e",
          "sha256": "60721198cbbe68bdcffa4225195e034e1e9dfd01865297cc79f59b3487396e8c",
          "sha1": "79884aef13eaf5d6ebeff446d48059bc744254a9",
          "md5": "e06e6bb4f8904586ca2a9e448a6251d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.8.aar",
          "url": "battery-0.0.8.aar",
          "size": 945804,
          "sha512": "18e482341a07cceb01baa330ff2dbf4f87381583e8cdf23e9195c49f106db32721b231e592d69bef30a8335283c6bcd4c81e18bc7d1bb749d4bc844402aaed0e",
          "sha256": "60721198cbbe68bdcffa4225195e034e1e9dfd01865297cc79f59b3487396e8c",
          "sha1": "79884aef13eaf5d6ebeff446d48059bc744254a9",
          "md5": "e06e6bb4f8904586ca2a9e448a6251d0"
        }
      ]
    }
  ]
}
