{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "telemetry",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.8.aar",
          "url": "telemetry-0.0.8.aar",
          "size": 445274,
          "sha512": "97593087f1c8161f5b6d52ee885f6757cf2a00b8d08c7f4ddaf118316412ba3942213d1b60ea7d2fc665d8766aa564edcbd992ca52bdafdb9b3f2c11f0a3f934",
          "sha256": "8a59f4e98c9eb5c06f22b027fb0398e5b21f75f91794260acd6baf38f0fcef40",
          "sha1": "5104e030b25b5ecc550e70341862ac3470791d5e",
          "md5": "76a42308f0550db6fa02a9fc376e0ee5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.8.aar",
          "url": "telemetry-0.0.8.aar",
          "size": 445274,
          "sha512": "97593087f1c8161f5b6d52ee885f6757cf2a00b8d08c7f4ddaf118316412ba3942213d1b60ea7d2fc665d8766aa564edcbd992ca52bdafdb9b3f2c11f0a3f934",
          "sha256": "8a59f4e98c9eb5c06f22b027fb0398e5b21f75f91794260acd6baf38f0fcef40",
          "sha1": "5104e030b25b5ecc550e70341862ac3470791d5e",
          "md5": "76a42308f0550db6fa02a9fc376e0ee5"
        }
      ]
    }
  ]
}
