{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "field",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.10.aar",
          "url": "field-0.0.10.aar",
          "size": 1104010,
          "sha512": "fcc58ccf2b25429468590774b7217ca4d9d9e0730a04ab4bc25618c12c0731635c85a7ff174b54d4e4548b279a21ea27e1dd379dab4127722b5afadf438e5bb5",
          "sha256": "d6724404365250fb649e71eb090a9830069dc35aaa0c5a9f2c31606359aabfa0",
          "sha1": "9c2b9cd14f30b3dd3666f6a2aee03ad58e7ce0a5",
          "md5": "ab416cac11950af727c4639cac217e25"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.10.aar",
          "url": "field-0.0.10.aar",
          "size": 1104010,
          "sha512": "fcc58ccf2b25429468590774b7217ca4d9d9e0730a04ab4bc25618c12c0731635c85a7ff174b54d4e4548b279a21ea27e1dd379dab4127722b5afadf438e5bb5",
          "sha256": "d6724404365250fb649e71eb090a9830069dc35aaa0c5a9f2c31606359aabfa0",
          "sha1": "9c2b9cd14f30b3dd3666f6a2aee03ad58e7ce0a5",
          "md5": "ab416cac11950af727c4639cac217e25"
        }
      ]
    }
  ]
}
