{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "capture",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.2.aar",
          "url": "capture-0.0.2.aar",
          "size": 92000,
          "sha512": "9ad53eea8a60ce7240c37eab1da22f4413baad719b8b6555da426e24a3520059ab59e42c4aa7bcb29746dff1cc353dc6aba4237e2ae5b1f7be08ab5051552ce1",
          "sha256": "d967843572657385667650598a44b482cba8e20beb2e2b89402e315704b49bcf",
          "sha1": "445a7f66ccb0d9d9f9fb40c01cb444afe5a23d3b",
          "md5": "c6deb2f2d53caa5ae740e34562b7d640"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.2.aar",
          "url": "capture-0.0.2.aar",
          "size": 92000,
          "sha512": "9ad53eea8a60ce7240c37eab1da22f4413baad719b8b6555da426e24a3520059ab59e42c4aa7bcb29746dff1cc353dc6aba4237e2ae5b1f7be08ab5051552ce1",
          "sha256": "d967843572657385667650598a44b482cba8e20beb2e2b89402e315704b49bcf",
          "sha1": "445a7f66ccb0d9d9f9fb40c01cb444afe5a23d3b",
          "md5": "c6deb2f2d53caa5ae740e34562b7d640"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "capture-0.0.2-sources.jar",
          "url": "capture-0.0.2-sources.jar",
          "size": 1857,
          "sha512": "f1c78f27ca57225885220dde158797bbbdb62fcde9676358725e27cc3b3ad8ced927e679fb22a3945ccb6dbed676526b1ae6f197c1075511fe030a3a8315457c",
          "sha256": "564d4b8fb3b1b9ad48687df77dc0d0758f8e6016fd166e78d73429b389dbcb35",
          "sha1": "d43506f22653ddaa9ea54b98a87d40d0ce7a040e",
          "md5": "b09e5a53833c2dad80cf7cad5d374bde"
        }
      ]
    }
  ]
}
