{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "capture",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.2.aar",
          "url": "capture-0.0.2.aar",
          "size": 93984,
          "sha512": "6b2fa963923ccb220223b61990679fef5c96f49fb71093b5039f9dc4ca627f1d1f59bc40b790f854116136c83f556eecafa3750c2d076881e49619f8f0bc9021",
          "sha256": "495023e16c4ef6188fb142cd730c36372752b8df6c6d2144102c5ce024a29f1e",
          "sha1": "7d417c9ff140bb7d56f060b450d7171fb5798cdd",
          "md5": "977553ef02f6a3333943dacf14ace578"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.2.aar",
          "url": "capture-0.0.2.aar",
          "size": 93984,
          "sha512": "6b2fa963923ccb220223b61990679fef5c96f49fb71093b5039f9dc4ca627f1d1f59bc40b790f854116136c83f556eecafa3750c2d076881e49619f8f0bc9021",
          "sha256": "495023e16c4ef6188fb142cd730c36372752b8df6c6d2144102c5ce024a29f1e",
          "sha1": "7d417c9ff140bb7d56f060b450d7171fb5798cdd",
          "md5": "977553ef02f6a3333943dacf14ace578"
        }
      ]
    }
  ]
}
