{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "exampleplugin",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.4.aar",
          "url": "exampleplugin-0.0.4.aar",
          "size": 84187,
          "sha512": "4859d4168325ff69105b46a725ba4080cc0dda7ba61dbdb47d8880d2c2cd75b61b29287e8cd71f03b03146e9882178a90a794921263ecbed6dbb4fe2a8330f5c",
          "sha256": "f1711ba2b04bed1a2f163ef75116cc9c23b528e0d8ca886e5cdc4f795a6c43f2",
          "sha1": "f64bde5489300ee51b19993743d23fda19ea22e6",
          "md5": "96052631c6b7e3b00e77a757d1671665"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.4.aar",
          "url": "exampleplugin-0.0.4.aar",
          "size": 84187,
          "sha512": "4859d4168325ff69105b46a725ba4080cc0dda7ba61dbdb47d8880d2c2cd75b61b29287e8cd71f03b03146e9882178a90a794921263ecbed6dbb4fe2a8330f5c",
          "sha256": "f1711ba2b04bed1a2f163ef75116cc9c23b528e0d8ca886e5cdc4f795a6c43f2",
          "sha1": "f64bde5489300ee51b19993743d23fda19ea22e6",
          "md5": "96052631c6b7e3b00e77a757d1671665"
        }
      ]
    }
  ]
}
