{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "exampleplugin",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.4.aar",
          "url": "exampleplugin-0.0.4.aar",
          "size": 83422,
          "sha512": "bd173afb377b48f533476e64512fce828983d2a3023a6756867e72467f687a28f3e5fd7351c01303946a39d968dd71ddf03d383c6f7d3ca8fc6446575f3a7ec2",
          "sha256": "9d3e887fec1a78cd0c84d2052444d8461efde4250b2626c58bbd1dc651a8123e",
          "sha1": "bc67020fad8543fa607734833356a99987e67ec6",
          "md5": "480c72b1e352d6f77d39f246d4fe5129"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.4.aar",
          "url": "exampleplugin-0.0.4.aar",
          "size": 83422,
          "sha512": "bd173afb377b48f533476e64512fce828983d2a3023a6756867e72467f687a28f3e5fd7351c01303946a39d968dd71ddf03d383c6f7d3ca8fc6446575f3a7ec2",
          "sha256": "9d3e887fec1a78cd0c84d2052444d8461efde4250b2626c58bbd1dc651a8123e",
          "sha1": "bc67020fad8543fa607734833356a99987e67ec6",
          "md5": "480c72b1e352d6f77d39f246d4fe5129"
        }
      ]
    }
  ]
}
