{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "ftcontrol",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.4.5.aar",
          "url": "ftcontrol-0.4.5.aar",
          "size": 29265529,
          "sha512": "4710b11401ab649660e0d7229198eddf312909ffaa5e0b396b5c8abe99c3e96593df60cf14b720da268db9c14363d8c5569b6ddfcc97c88c41dc5df92e464804",
          "sha256": "19e355524583728d3dce04de222ce5129faa38f8ea2decbaf6dc00a49222ad58",
          "sha1": "c5af97f229323165eec839873454583863cc79cc",
          "md5": "4bf657ddf73f0202404e686379ff4b99"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.4.5.aar",
          "url": "ftcontrol-0.4.5.aar",
          "size": 29265529,
          "sha512": "4710b11401ab649660e0d7229198eddf312909ffaa5e0b396b5c8abe99c3e96593df60cf14b720da268db9c14363d8c5569b6ddfcc97c88c41dc5df92e464804",
          "sha256": "19e355524583728d3dce04de222ce5129faa38f8ea2decbaf6dc00a49222ad58",
          "sha1": "c5af97f229323165eec839873454583863cc79cc",
          "md5": "4bf657ddf73f0202404e686379ff4b99"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftcontrol-0.4.5-sources.jar",
          "url": "ftcontrol-0.4.5-sources.jar",
          "size": 87827,
          "sha512": "51b42d23af4cf559a5ce854be1b810b6c76f5fa36e31ab8ff8b68c0e5da76fb3e3b6d3f5d20f81eac4a9a72be49c48e023198d61a4018c67d6ac1d445533d7af",
          "sha256": "e50592ec5310016362c67f72065d1804ce1cda4cd6b8b4bc145a648c04c71f0d",
          "sha1": "426ff581e1cdd1f7928715200a27fe5244e5b4fd",
          "md5": "39918f9064aed247e5839f34a98d4927"
        }
      ]
    }
  ]
}
