{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "configurables",
    "version": "0.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.16.aar",
          "url": "configurables-0.0.16.aar",
          "size": 296567,
          "sha512": "e683529f7aa700ef9f1489c442f80b47b4cef7ca38afa6a25fe4ed56cad2cde871a6c6797b0b2eefcff82faced6f29c818be753d049baf3752ba508dbb6d42a2",
          "sha256": "c83d25c1eaf72abd628ec9632a800adce0cebdd435362c28a8761d663eb0d99f",
          "sha1": "c3d5e71ccc1b509b676744f2001bcb2bc6367c60",
          "md5": "4169fa88ce8b7331e4948769bb0bd1b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.16.aar",
          "url": "configurables-0.0.16.aar",
          "size": 296567,
          "sha512": "e683529f7aa700ef9f1489c442f80b47b4cef7ca38afa6a25fe4ed56cad2cde871a6c6797b0b2eefcff82faced6f29c818be753d049baf3752ba508dbb6d42a2",
          "sha256": "c83d25c1eaf72abd628ec9632a800adce0cebdd435362c28a8761d663eb0d99f",
          "sha1": "c3d5e71ccc1b509b676744f2001bcb2bc6367c60",
          "md5": "4169fa88ce8b7331e4948769bb0bd1b6"
        }
      ]
    }
  ]
}
