{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "utils",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.3.aar",
          "url": "utils-0.0.3.aar",
          "size": 66295,
          "sha512": "1fc82e33683968801611ebdd9bd1b962dbefbf16f3d71b6a16768a5a858601f3945bf9894477f2edcf64c5fbaabd6b1496a2f461e3be672f877be86eb97bf59c",
          "sha256": "639e95c13bf2ab4a6e720bce90fd7a7c90026f2bdd5e8ed2351270bc30dc6573",
          "sha1": "5e6bfb702addf3965f6f81a945e9c2a0152907f9",
          "md5": "0db9428bb0e49999d5375bdaa8320704"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.3.aar",
          "url": "utils-0.0.3.aar",
          "size": 66295,
          "sha512": "1fc82e33683968801611ebdd9bd1b962dbefbf16f3d71b6a16768a5a858601f3945bf9894477f2edcf64c5fbaabd6b1496a2f461e3be672f877be86eb97bf59c",
          "sha256": "639e95c13bf2ab4a6e720bce90fd7a7c90026f2bdd5e8ed2351270bc30dc6573",
          "sha1": "5e6bfb702addf3965f6f81a945e9c2a0152907f9",
          "md5": "0db9428bb0e49999d5375bdaa8320704"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-0.0.3-sources.jar",
          "url": "utils-0.0.3-sources.jar",
          "size": 1950,
          "sha512": "3062d8dead813c9e6c78f9dac67b20cc143041fea946aaf502762fa4e0b0be81232bac986afa39cb3c8a3e6dae0aaf5878639f6f7ab05d207eb67b90036d470e",
          "sha256": "0ee62737110064502b397b2397fea016d9d8f095fd5c5c9419355e785e3341d6",
          "sha1": "4bed957ad7bfa632d883501e822d6d7b48400799",
          "md5": "4b80b4335611339b03721d1ac897b0e4"
        }
      ]
    }
  ]
}
