{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "utils",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.3.aar",
          "url": "utils-0.0.3.aar",
          "size": 92123,
          "sha512": "87d566b467a43a614d19ad870cdb179a4e0bd593851f890dbb941c9a8f56cd4810d869fe958faddf682eb4f7cab726ace03a0923b6fbf923e3462455cf689ef9",
          "sha256": "65a9d7b8525f352cc98d63ec08189fca4ef198cc4bfaad52c3db0100ba52251e",
          "sha1": "dea552173842cd350fa27c0b33de0a293f6fe8aa",
          "md5": "ae74f757efd764a1a40959fb37e50843"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.3.aar",
          "url": "utils-0.0.3.aar",
          "size": 92123,
          "sha512": "87d566b467a43a614d19ad870cdb179a4e0bd593851f890dbb941c9a8f56cd4810d869fe958faddf682eb4f7cab726ace03a0923b6fbf923e3462455cf689ef9",
          "sha256": "65a9d7b8525f352cc98d63ec08189fca4ef198cc4bfaad52c3db0100ba52251e",
          "sha1": "dea552173842cd350fa27c0b33de0a293f6fe8aa",
          "md5": "ae74f757efd764a1a40959fb37e50843"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "utils-0.0.3-sources.jar",
          "url": "utils-0.0.3-sources.jar",
          "size": 3541,
          "sha512": "f1b5693f745ee24679e188c42e0017e17624dbdb68c073390fa18c9a6a7c3a3a2dc507ea9e05a724eb95c16685c4c3796872ceb7414aaea485a9a6521612c5b5",
          "sha256": "394bc8a2fb618819e556fa8eb38a70713c1ea280996a7365ee5e259ac3c89ef3",
          "sha1": "84353d46cc4c7a3d660b1766bf8fbc10c96f79b3",
          "md5": "1e069cb982b3e3fd2dba7ccac5d26a6f"
        }
      ]
    }
  ]
}
