{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "battery",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.2.aar",
          "url": "battery-0.0.2.aar",
          "size": 84934,
          "sha512": "2eb7700e71e479518d8cdd8abe4b8b1fcdf6b3bd4b6bf47b7bf27e097848d3219d3f09c7dbaf22f03e44511b713c42b61d8b62785a72325f15d5ddcf97c6f9b3",
          "sha256": "3d9c7ef434b01cd8fd3e7f44281869742f1eed5479aab0be4678450d33790769",
          "sha1": "ff8d1a6afdc769f214424c10c6745b55afb4cc5f",
          "md5": "f224ef4eca2bb1978119653cedebef9e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.2.aar",
          "url": "battery-0.0.2.aar",
          "size": 84934,
          "sha512": "2eb7700e71e479518d8cdd8abe4b8b1fcdf6b3bd4b6bf47b7bf27e097848d3219d3f09c7dbaf22f03e44511b713c42b61d8b62785a72325f15d5ddcf97c6f9b3",
          "sha256": "3d9c7ef434b01cd8fd3e7f44281869742f1eed5479aab0be4678450d33790769",
          "sha1": "ff8d1a6afdc769f214424c10c6745b55afb4cc5f",
          "md5": "f224ef4eca2bb1978119653cedebef9e"
        }
      ]
    }
  ]
}
