{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "battery",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.2.aar",
          "url": "battery-0.0.2.aar",
          "size": 84834,
          "sha512": "86953a6826cebb08795156710418aa690c2b3101f9ff5a75000339ffb3a634cc69228caaee2fc8a2a5c6c47d8a556f329f59726063e7f494455a3a7bc78c3fab",
          "sha256": "b427c0c2095755cfaea0968e2e90383c83e9b32c71c7460c269ff1716547cc14",
          "sha1": "f5bc28b033e622766bba12cf81f8da8c00de6508",
          "md5": "d74616ca5baf882f846a4e9c6ec85884"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.2.aar",
          "url": "battery-0.0.2.aar",
          "size": 84834,
          "sha512": "86953a6826cebb08795156710418aa690c2b3101f9ff5a75000339ffb3a634cc69228caaee2fc8a2a5c6c47d8a556f329f59726063e7f494455a3a7bc78c3fab",
          "sha256": "b427c0c2095755cfaea0968e2e90383c83e9b32c71c7460c269ff1716547cc14",
          "sha1": "f5bc28b033e622766bba12cf81f8da8c00de6508",
          "md5": "d74616ca5baf882f846a4e9c6ec85884"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "battery-0.0.2-sources.jar",
          "url": "battery-0.0.2-sources.jar",
          "size": 4125,
          "sha512": "4e8fa262af448959b28f68ad254b393743e243fb0df453fb835e204fbdff297fa31c9b26453e3a31ceb093aa0915c362d3ba335809ff2407e1710fd2f9dfea75",
          "sha256": "35854464f1befb9b4e616eb67fbe4e1a97f9c8f01ddc2a64751d5b44010cc238",
          "sha1": "4d3ffe22334302e7816c3243b4986d301b5d4379",
          "md5": "9d2509cbd404940997ff96f9673fe734"
        }
      ]
    }
  ]
}
