{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "limelightproxy",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.12.aar",
          "url": "limelightproxy-0.0.12.aar",
          "size": 245848,
          "sha512": "76d4276b2512f4ae7dee6125e0c078624b3e4d54c684271f9cc676fab55a2f9a70d4905eff449eca02258fafc85d6663659d08d4d5d14dc18507cc9e6d37c179",
          "sha256": "2b247706f3af1271777cb4df46881eea494a47bae57221c6d355f3ee56486372",
          "sha1": "7532497831deee06d924f420d68a556c9cf79a2f",
          "md5": "382338ee2cbe1417a6f856536ce3556d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.12.aar",
          "url": "limelightproxy-0.0.12.aar",
          "size": 245848,
          "sha512": "76d4276b2512f4ae7dee6125e0c078624b3e4d54c684271f9cc676fab55a2f9a70d4905eff449eca02258fafc85d6663659d08d4d5d14dc18507cc9e6d37c179",
          "sha256": "2b247706f3af1271777cb4df46881eea494a47bae57221c6d355f3ee56486372",
          "sha1": "7532497831deee06d924f420d68a556c9cf79a2f",
          "md5": "382338ee2cbe1417a6f856536ce3556d"
        }
      ]
    }
  ]
}
