{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "ftcontrol",
    "version": "0.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.6.4.aar",
          "url": "ftcontrol-0.6.4.aar",
          "size": 32954345,
          "sha512": "7b09fd22b2f1afac80d2039d429da0143d321baba5c62bdd3ef910176edfdacbd2d0370001572c3e9842faeba36adab106bd9e764be5acc3666cfdd996dc6600",
          "sha256": "ef02797f6727cbbaa0628f0d3af1fc8689e110af3af1dc4c94590c14efec56b6",
          "sha1": "a2f089697ca51a03a1b652a210e4dde27c65a027",
          "md5": "c8945c44be79ae50d4af86ee2e123460"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.6.4.aar",
          "url": "ftcontrol-0.6.4.aar",
          "size": 32954345,
          "sha512": "7b09fd22b2f1afac80d2039d429da0143d321baba5c62bdd3ef910176edfdacbd2d0370001572c3e9842faeba36adab106bd9e764be5acc3666cfdd996dc6600",
          "sha256": "ef02797f6727cbbaa0628f0d3af1fc8689e110af3af1dc4c94590c14efec56b6",
          "sha1": "a2f089697ca51a03a1b652a210e4dde27c65a027",
          "md5": "c8945c44be79ae50d4af86ee2e123460"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftcontrol-0.6.4-sources.jar",
          "url": "ftcontrol-0.6.4-sources.jar",
          "size": 92331,
          "sha512": "ae80fa1f63ae4cb11bb920af339dcedb2ce1fca477436de2271e41ae20dac525677349bb48807c4cabb935f0c4831f852de1a6b6f045a214a1b4b170039eee33",
          "sha256": "3cde27f86325996c07de06b36b03c9b1367bddc8a984e3663559dd31944dcf38",
          "sha1": "9ba0d1a65b14e0533454f0c50a504ddc715a11ca",
          "md5": "6207c3a60f7da8c87500ddb11f3e9f35"
        }
      ]
    }
  ]
}
