{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "opmodecontrol",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-1.0.3.aar",
          "url": "opmodecontrol-1.0.3.aar",
          "size": 1037505,
          "sha512": "27755097a7a7a555bb63a4a549ecbbdd95b959badc9250049c323a68a384e658a1439d391f45279ec175b318a853878225ff01695872f2c380c36b644657fec4",
          "sha256": "810f97f55d3bd6d5a488128b84340f5b6ae0c4a31e7cf0f7f991329c1a798ed8",
          "sha1": "9dcbf6fc868196220afc1edf3958f1678dcb52b6",
          "md5": "a5db4ebe94ccc49f04ac389aa65706fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-1.0.3.aar",
          "url": "opmodecontrol-1.0.3.aar",
          "size": 1037505,
          "sha512": "27755097a7a7a555bb63a4a549ecbbdd95b959badc9250049c323a68a384e658a1439d391f45279ec175b318a853878225ff01695872f2c380c36b644657fec4",
          "sha256": "810f97f55d3bd6d5a488128b84340f5b6ae0c4a31e7cf0f7f991329c1a798ed8",
          "sha1": "9dcbf6fc868196220afc1edf3958f1678dcb52b6",
          "md5": "a5db4ebe94ccc49f04ac389aa65706fe"
        }
      ]
    }
  ]
}
