{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "configurables",
    "version": "0.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.18.aar",
          "url": "configurables-0.0.18.aar",
          "size": 296567,
          "sha512": "2ad22d3a63ae8b18373c79f115910fb12b7d33f9abc16b145e9c55a879d5c557231b3c6dc00371767676ec695b73bfc61fa619381322be595e2f939703fed8d9",
          "sha256": "8f066addeee9c44c71e3230c82c61ff3d9795ff5247da76b0b1c6fe519a5a169",
          "sha1": "222572f0d7ead740a603500d44572909f638c721",
          "md5": "bd94f77ab2149d852f0441b232511308"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.18.aar",
          "url": "configurables-0.0.18.aar",
          "size": 296567,
          "sha512": "2ad22d3a63ae8b18373c79f115910fb12b7d33f9abc16b145e9c55a879d5c557231b3c6dc00371767676ec695b73bfc61fa619381322be595e2f939703fed8d9",
          "sha256": "8f066addeee9c44c71e3230c82c61ff3d9795ff5247da76b0b1c6fe519a5a169",
          "sha1": "222572f0d7ead740a603500d44572909f638c721",
          "md5": "bd94f77ab2149d852f0441b232511308"
        }
      ]
    }
  ]
}
