{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "opmodecontrol",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.14.aar",
          "url": "opmodecontrol-0.0.14.aar",
          "size": 875135,
          "sha512": "56a4f70d5cce85ee6e9039b1689276d1a6c2d36ef625b08dad7407f005fcf244362779af9cc8cb7cead2480e069d2c0c03258f9acf5e0dcc78dcb5d2c491c15d",
          "sha256": "3d3821b09958d0575b847ddec3cbe8f431b9b75b005f370eeab9b4a965c40cfc",
          "sha1": "b15a1d59118aef469ad19ed0906c86c9493ed178",
          "md5": "6b9ae9e162e7e5e80869ba29e3ea5a31"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.14.aar",
          "url": "opmodecontrol-0.0.14.aar",
          "size": 875135,
          "sha512": "56a4f70d5cce85ee6e9039b1689276d1a6c2d36ef625b08dad7407f005fcf244362779af9cc8cb7cead2480e069d2c0c03258f9acf5e0dcc78dcb5d2c491c15d",
          "sha256": "3d3821b09958d0575b847ddec3cbe8f431b9b75b005f370eeab9b4a965c40cfc",
          "sha1": "b15a1d59118aef469ad19ed0906c86c9493ed178",
          "md5": "6b9ae9e162e7e5e80869ba29e3ea5a31"
        }
      ]
    }
  ]
}
