{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "ftcontrol",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.2.6.aar",
          "url": "ftcontrol-0.2.6.aar",
          "size": 20578604,
          "sha512": "4c30950975267834249c40dbbe086ae269e5b2cb5fc2bdf01209bb67921963028ca127a236fde6b12b649848c54c4d70d2a6c284f12d925fc41337babfc61afb",
          "sha256": "176ac2f86c5967aa4fac1533ff023dbdd4efb263df76318d691120256ac35c70",
          "sha1": "192f8530af253c53f65fa6aa82a0e73b4f1e758a",
          "md5": "a070543fee9009fc1709cf938a377688"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.2.6.aar",
          "url": "ftcontrol-0.2.6.aar",
          "size": 20578604,
          "sha512": "4c30950975267834249c40dbbe086ae269e5b2cb5fc2bdf01209bb67921963028ca127a236fde6b12b649848c54c4d70d2a6c284f12d925fc41337babfc61afb",
          "sha256": "176ac2f86c5967aa4fac1533ff023dbdd4efb263df76318d691120256ac35c70",
          "sha1": "192f8530af253c53f65fa6aa82a0e73b4f1e758a",
          "md5": "a070543fee9009fc1709cf938a377688"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftcontrol-0.2.6-sources.jar",
          "url": "ftcontrol-0.2.6-sources.jar",
          "size": 68455,
          "sha512": "655d293ca7a2949846ffa64909d8fb2926438468db38af25630a4e6ecbe2b272e0e9ab6b2482f4a46bff5e3b6ef3c5ae4da2918bcfb9a74fdc3b55622cf3720a",
          "sha256": "7bd118b012cdb7e626ef8db4d57129debc7d2b757853320ce784382d9f64b804",
          "sha1": "782a881da197a37b498c13e3874483bdf2f6ea9d",
          "md5": "062d6d7f0d7610a72590aa7587846e53"
        }
      ]
    }
  ]
}
