{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "graph",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "graph-1.0.5.aar",
          "url": "graph-1.0.5.aar",
          "size": 2531499,
          "sha512": "7470b651051f5eedb7f56e9e02e8c6d065760d44c330af23d4ffee1c1843994f24c53fcec7922e052434adf4284de07b7b8c2f9b246483a341dcc4b19a2b6fc8",
          "sha256": "3714106875717462447691d26ff9891486b553d3194bea9bb5f5df996a39fe90",
          "sha1": "350c2eda88130fd310c338f0e4a54f6ab9597c45",
          "md5": "3777f59769bd68a1c7ead9a45cf60825"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "graph-1.0.5.aar",
          "url": "graph-1.0.5.aar",
          "size": 2531499,
          "sha512": "7470b651051f5eedb7f56e9e02e8c6d065760d44c330af23d4ffee1c1843994f24c53fcec7922e052434adf4284de07b7b8c2f9b246483a341dcc4b19a2b6fc8",
          "sha256": "3714106875717462447691d26ff9891486b553d3194bea9bb5f5df996a39fe90",
          "sha1": "350c2eda88130fd310c338f0e4a54f6ab9597c45",
          "md5": "3777f59769bd68a1c7ead9a45cf60825"
        }
      ]
    }
  ]
}
