{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "telemetry",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.10.aar",
          "url": "telemetry-0.0.10.aar",
          "size": 235200,
          "sha512": "1cde2f370c8926dc59d3ad4bd9db07446e0e8bd275151a1b869b2ab1d5eb9d08090a781ddd69da21771f212e18251bb74dd08b7f638fd4234f2369dda729ab01",
          "sha256": "96ab2751c9cc6f9c9f5eea0bb19384a241eb619220cf35f64fff7ef70a52d97e",
          "sha1": "b5140e8b32b9171c099f4ae4e94474c7893bcd7c",
          "md5": "bc153765856e757edc7b97fc0871a5ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.10.aar",
          "url": "telemetry-0.0.10.aar",
          "size": 235200,
          "sha512": "1cde2f370c8926dc59d3ad4bd9db07446e0e8bd275151a1b869b2ab1d5eb9d08090a781ddd69da21771f212e18251bb74dd08b7f638fd4234f2369dda729ab01",
          "sha256": "96ab2751c9cc6f9c9f5eea0bb19384a241eb619220cf35f64fff7ef70a52d97e",
          "sha1": "b5140e8b32b9171c099f4ae4e94474c7893bcd7c",
          "md5": "bc153765856e757edc7b97fc0871a5ef"
        }
      ]
    }
  ]
}
