{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "fullpanels",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.bylazar",
          "module": "panels",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "com.bylazar",
          "module": "opmodecontrol",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "exampleplugin",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "telemetry",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "configurables",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "themes",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "capture",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "limelightproxy",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "gamepad",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "field",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "docs",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "battery",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "utils",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-0.0.11.aar",
          "url": "fullpanels-0.0.11.aar",
          "size": 64651,
          "sha512": "4ad7359c7dc537b65d5f06efab99e58dc66917774f4519288fbd609f5af288338ca3a44e962fb58be523e73d5d9fef12902924293271f9b01c58ddbad03b75c8",
          "sha256": "4df555259cd56f23963270454d9c90df9db4e3acd605716b4a8bab8ae071cbfb",
          "sha1": "f0e7799b22d97f45581504265579d074ea516eeb",
          "md5": "49900d1d9702f8fc219bfee54cd1d148"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.bylazar",
          "module": "panels",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "com.bylazar",
          "module": "opmodecontrol",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "exampleplugin",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "telemetry",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "configurables",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "themes",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "capture",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "limelightproxy",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "gamepad",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "field",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "docs",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "battery",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bylazar",
          "module": "utils",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-0.0.11.aar",
          "url": "fullpanels-0.0.11.aar",
          "size": 64651,
          "sha512": "4ad7359c7dc537b65d5f06efab99e58dc66917774f4519288fbd609f5af288338ca3a44e962fb58be523e73d5d9fef12902924293271f9b01c58ddbad03b75c8",
          "sha256": "4df555259cd56f23963270454d9c90df9db4e3acd605716b4a8bab8ae071cbfb",
          "sha1": "f0e7799b22d97f45581504265579d074ea516eeb",
          "md5": "49900d1d9702f8fc219bfee54cd1d148"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fullpanels-0.0.11-sources.jar",
          "url": "fullpanels-0.0.11-sources.jar",
          "size": 1893,
          "sha512": "3b49007bf7298578c8b712b3e1006291120dfbb806d259afd35e0afb010f16e3f83d187673cb06791ad30e608622c67bab6b350d608e510306f2037a7d435419",
          "sha256": "cd16e6940d253b155f9c2a09ccb20495e877ddd9683f32550f187420ba9dac8f",
          "sha1": "99a11f2e1b59704ecd173843703a48e8a6c44346",
          "md5": "66b7e857805c5a803a232782794329db"
        }
      ]
    }
  ]
}
