{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.13.aar",
          "url": "panels-0.0.13.aar",
          "size": 284500,
          "sha512": "92ca05c4a2786611a2bcb6eb87efff84cb81772f8eddee302f5d4e2eea38f79d14fb158b59459e411e31be4aac67dfbfde5ca0b04b3c51fe734aa6b690be84aa",
          "sha256": "f9ef0a8c46448566f464cec3e26d86d5c6717f6bdabd7cd868ca4b8d74050f4c",
          "sha1": "8142ae2fbb30ef40c55986984b58548a69c9fb1a",
          "md5": "040cce15bd87b89635fdec41ec4d6898"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.13.aar",
          "url": "panels-0.0.13.aar",
          "size": 284500,
          "sha512": "92ca05c4a2786611a2bcb6eb87efff84cb81772f8eddee302f5d4e2eea38f79d14fb158b59459e411e31be4aac67dfbfde5ca0b04b3c51fe734aa6b690be84aa",
          "sha256": "f9ef0a8c46448566f464cec3e26d86d5c6717f6bdabd7cd868ca4b8d74050f4c",
          "sha1": "8142ae2fbb30ef40c55986984b58548a69c9fb1a",
          "md5": "040cce15bd87b89635fdec41ec4d6898"
        }
      ]
    }
  ]
}
