{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.13.aar",
          "url": "panels-0.0.13.aar",
          "size": 284602,
          "sha512": "7f7eceb060d2c698472f7ca77888336192f80b12410fae83cafc88c9b1d02c94fe3608b3c0dd0c23b2d30f16e6d810e757899d7d86149ac280da07152e3c75e5",
          "sha256": "b356ed5311ee688026ae38bfa394ceaf2bc3fb9dbd2597cafd7a25d8d8c4cec9",
          "sha1": "30d10693b8be4ac25ff68a28fff965f3a6c61c67",
          "md5": "5eaeb96b181a5638323629b0ddb63800"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.13.aar",
          "url": "panels-0.0.13.aar",
          "size": 284602,
          "sha512": "7f7eceb060d2c698472f7ca77888336192f80b12410fae83cafc88c9b1d02c94fe3608b3c0dd0c23b2d30f16e6d810e757899d7d86149ac280da07152e3c75e5",
          "sha256": "b356ed5311ee688026ae38bfa394ceaf2bc3fb9dbd2597cafd7a25d8d8c4cec9",
          "sha1": "30d10693b8be4ac25ff68a28fff965f3a6c61c67",
          "md5": "5eaeb96b181a5638323629b0ddb63800"
        }
      ]
    }
  ]
}
