{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "limelightproxy",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.2.aar",
          "url": "limelightproxy-0.0.2.aar",
          "size": 97901,
          "sha512": "37060e8559bf91755c8e0579b358c333a5bbcb834cb3814f0388aea5e07f0a6c7aa6f8b0995d242192e75cf0d963dbf1580877435910cfc597b766c40e3a993a",
          "sha256": "f54181e5ada61a7a466da70e56396c9ccd14d2896edecd52deeb3c476ec31226",
          "sha1": "2acd56bce8d9446c6c9464a25c43dceb720a9f25",
          "md5": "4135fe39ff67ed3e1ef40c37492e6ec5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.2.aar",
          "url": "limelightproxy-0.0.2.aar",
          "size": 97901,
          "sha512": "37060e8559bf91755c8e0579b358c333a5bbcb834cb3814f0388aea5e07f0a6c7aa6f8b0995d242192e75cf0d963dbf1580877435910cfc597b766c40e3a993a",
          "sha256": "f54181e5ada61a7a466da70e56396c9ccd14d2896edecd52deeb3c476ec31226",
          "sha1": "2acd56bce8d9446c6c9464a25c43dceb720a9f25",
          "md5": "4135fe39ff67ed3e1ef40c37492e6ec5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "limelightproxy-0.0.2-sources.jar",
          "url": "limelightproxy-0.0.2-sources.jar",
          "size": 11385,
          "sha512": "8f5507b55c6da38806a7889fce2f612e6d6cf7a3f7ccbecd14621e4a2307acc8b184e33f9658f89b0029af838b8278a6d9128d012191522ab08a1f4e22254117",
          "sha256": "abb2e41dc871c777fffc32487668567a445e6636f9e873dce917488b73f46566",
          "sha1": "7563b6993aa48ab4b2267a500ca1f0f6ce221b2b",
          "md5": "5911f7cfcc90f4e647f4a93b2ce71f71"
        }
      ]
    }
  ]
}
