{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "utils",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-1.0.5.aar",
          "url": "utils-1.0.5.aar",
          "size": 77686,
          "sha512": "0d15eca4efeeea538dd5f2b32eaa3ce0877d5a2da1d9678f9a31aec500c7dd8b9637a60e78fcd6c579ea6d199fed656712b6fa01653ba26e499c58c9ee162937",
          "sha256": "8bd3485ce5c791223ce06d903b8ee513512ac512836a4d87eb9849d139fbe89b",
          "sha1": "ccddde1ea8ea6aa63eb3ef49ff54f671d32239b4",
          "md5": "bfe55e3d2e0b8226015382ef29d356e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-1.0.5.aar",
          "url": "utils-1.0.5.aar",
          "size": 77686,
          "sha512": "0d15eca4efeeea538dd5f2b32eaa3ce0877d5a2da1d9678f9a31aec500c7dd8b9637a60e78fcd6c579ea6d199fed656712b6fa01653ba26e499c58c9ee162937",
          "sha256": "8bd3485ce5c791223ce06d903b8ee513512ac512836a4d87eb9849d139fbe89b",
          "sha1": "ccddde1ea8ea6aa63eb3ef49ff54f671d32239b4",
          "md5": "bfe55e3d2e0b8226015382ef29d356e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-1.0.5-sources.jar",
          "url": "utils-1.0.5-sources.jar",
          "size": 1962,
          "sha512": "90a6256be2a5a3e37be90a335cae34b89986c2a0d65f518054632ae53d6259323673ed570004d2c0d2dbe5fbf1f67b34f66e0249871c9fb489a4e7032d33a842",
          "sha256": "4db5e1f47fb49a50c08c3677ea7aea7a627978a71a2e939618d69c805a944114",
          "sha1": "ecc2be3b71b0735ec6c29360e184dd938c15f7dc",
          "md5": "c352dddf4d9cd61cae35418c1a9a00bf"
        }
      ]
    }
  ]
}
