{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "opmodecontrol",
    "version": "0.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.16.aar",
          "url": "opmodecontrol-0.0.16.aar",
          "size": 875154,
          "sha512": "23e48958c010d98d1886b86dfa71b1833e8422cb6e0beaa898614d13b26835dde1399ab579b19c26ea6959a4d5e17d45444f3cae20ebefc5a12c8245ddfe1eed",
          "sha256": "9cc6c5e6496bcf6cec9a33a159254bb06613c2f542ebb400e4eff45b17922c64",
          "sha1": "231e99e8c2fb8f92dba3ebf5f3e4cbf40e691af5",
          "md5": "1179220730a0e578b7002a4844036944"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.16.aar",
          "url": "opmodecontrol-0.0.16.aar",
          "size": 875154,
          "sha512": "23e48958c010d98d1886b86dfa71b1833e8422cb6e0beaa898614d13b26835dde1399ab579b19c26ea6959a4d5e17d45444f3cae20ebefc5a12c8245ddfe1eed",
          "sha256": "9cc6c5e6496bcf6cec9a33a159254bb06613c2f542ebb400e4eff45b17922c64",
          "sha1": "231e99e8c2fb8f92dba3ebf5f3e4cbf40e691af5",
          "md5": "1179220730a0e578b7002a4844036944"
        }
      ]
    }
  ]
}
