{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "limelightproxy",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.3.aar",
          "url": "limelightproxy-0.0.3.aar",
          "size": 131541,
          "sha512": "db8d12f8c6cae2d95147e5541411cb143e5dff5e40963aeed34c7d3c882dcb4e6ced961df0057e0c3fbdb1625ae70590f25c9a583fe9a8f4130a1ac49ef2dec7",
          "sha256": "5ef0da0206e3aac41cfee4e5d075f70418fa5c4cdd6b1231f2bc933ffacb6852",
          "sha1": "e0216fdcb6f1b381cd803cf583f2b82e1ab6e550",
          "md5": "7de62ac3f043e9c20e973a219fd970ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.3.aar",
          "url": "limelightproxy-0.0.3.aar",
          "size": 131541,
          "sha512": "db8d12f8c6cae2d95147e5541411cb143e5dff5e40963aeed34c7d3c882dcb4e6ced961df0057e0c3fbdb1625ae70590f25c9a583fe9a8f4130a1ac49ef2dec7",
          "sha256": "5ef0da0206e3aac41cfee4e5d075f70418fa5c4cdd6b1231f2bc933ffacb6852",
          "sha1": "e0216fdcb6f1b381cd803cf583f2b82e1ab6e550",
          "md5": "7de62ac3f043e9c20e973a219fd970ee"
        }
      ]
    }
  ]
}
