{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "limelightproxy",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.10.aar",
          "url": "limelightproxy-0.0.10.aar",
          "size": 495097,
          "sha512": "4f17cff530ef71d47fa97854a988fb42d9c1b3cbfe5506b50ead8a27a8ed4ea1f75440633bcbe68ac35dab7eb6d43118794133f035fce63f66a925e56d634b6e",
          "sha256": "8aa6186d68c82b5348bc768aa1d9adae5797709777a21ee133a849cc547462c9",
          "sha1": "8c222cca5e505cd95b75fc0a8b15592deabe6232",
          "md5": "d5c551717a575ca2b1e58d8120f74d22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.10.aar",
          "url": "limelightproxy-0.0.10.aar",
          "size": 495097,
          "sha512": "4f17cff530ef71d47fa97854a988fb42d9c1b3cbfe5506b50ead8a27a8ed4ea1f75440633bcbe68ac35dab7eb6d43118794133f035fce63f66a925e56d634b6e",
          "sha256": "8aa6186d68c82b5348bc768aa1d9adae5797709777a21ee133a849cc547462c9",
          "sha1": "8c222cca5e505cd95b75fc0a8b15592deabe6232",
          "md5": "d5c551717a575ca2b1e58d8120f74d22"
        }
      ]
    }
  ]
}
