{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "docs",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "docs-1.0.8.aar",
          "url": "docs-1.0.8.aar",
          "size": 47240,
          "sha512": "6aff84b1c740ae6edbbe0dd8e570a60005e56da9a166cfb30491f8b78efa8a5dc8f073422e5012b87123355b0b3b3b8397bb50598d22ca2a1a34381e82b6f849",
          "sha256": "001f64bd0805b9d5ef6908d3ff13b8327f1d21e5e797d0a6217cbd0601429a4f",
          "sha1": "19cacd95384253573ece3ef8edf7c98f33a8fcec",
          "md5": "5ad0f54001c7159cad511578ed0a4a2a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "docs-1.0.8.aar",
          "url": "docs-1.0.8.aar",
          "size": 47240,
          "sha512": "6aff84b1c740ae6edbbe0dd8e570a60005e56da9a166cfb30491f8b78efa8a5dc8f073422e5012b87123355b0b3b3b8397bb50598d22ca2a1a34381e82b6f849",
          "sha256": "001f64bd0805b9d5ef6908d3ff13b8327f1d21e5e797d0a6217cbd0601429a4f",
          "sha1": "19cacd95384253573ece3ef8edf7c98f33a8fcec",
          "md5": "5ad0f54001c7159cad511578ed0a4a2a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "docs-1.0.8-sources.jar",
          "url": "docs-1.0.8-sources.jar",
          "size": 1096,
          "sha512": "21275b076e8fe82846f25513de99d64a9149734d44ef3bea0644cc5800ec7c5ae4012d63f675e3f50400d1741d227f546d0c4a1e978137e8b37d82ca07247b99",
          "sha256": "d1e82876ec298965b4f543b3dc3f30dbcfa132e3ff3f6b78ec94a686b340d79b",
          "sha1": "d1277d153be0d096c4390f49b380b6c5dc5513c7",
          "md5": "da3435bc28f83b1972e03945c0dab199"
        }
      ]
    }
  ]
}
