{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "limelightproxy",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.4.aar",
          "url": "limelightproxy-0.0.4.aar",
          "size": 131541,
          "sha512": "7a3b7fbab749224e4e6aec38d068252c8b1b5bfa71faf691ea6a7c398b54f60df1b981564916bb4e307e4de7bdf4707c3bb714205f42f89c99b84f49b03c262d",
          "sha256": "eb5021d91877728fdb916a5ea865c4ad4ed244d82caf9ada107154571193585d",
          "sha1": "9c415a05cd7f1512666c89e53eb06cc4c7c2e50d",
          "md5": "0f34d8be270152be711a54763ca1b61d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.4.aar",
          "url": "limelightproxy-0.0.4.aar",
          "size": 131541,
          "sha512": "7a3b7fbab749224e4e6aec38d068252c8b1b5bfa71faf691ea6a7c398b54f60df1b981564916bb4e307e4de7bdf4707c3bb714205f42f89c99b84f49b03c262d",
          "sha256": "eb5021d91877728fdb916a5ea865c4ad4ed244d82caf9ada107154571193585d",
          "sha1": "9c415a05cd7f1512666c89e53eb06cc4c7c2e50d",
          "md5": "0f34d8be270152be711a54763ca1b61d"
        }
      ]
    }
  ]
}
