{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "limelightproxy",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.4.aar",
          "url": "limelightproxy-0.0.4.aar",
          "size": 132305,
          "sha512": "fad131003c068d05a861639948ba9afababfb945741a9e1a282eae51737af216c496e8b5f8506abcde6a4ac0c3bf4d39c46f917adfb89db218ba4ae4187f7155",
          "sha256": "516dfd3da58a4e2f8c82ee1375b05f8127b0a5d2e91297ca41b14eff6bebb3b6",
          "sha1": "9ca1895364140335ca1dbb7a443415108dbe2187",
          "md5": "3ecf381e7aa8e1e1943903a4319b857a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.4.aar",
          "url": "limelightproxy-0.0.4.aar",
          "size": 132305,
          "sha512": "fad131003c068d05a861639948ba9afababfb945741a9e1a282eae51737af216c496e8b5f8506abcde6a4ac0c3bf4d39c46f917adfb89db218ba4ae4187f7155",
          "sha256": "516dfd3da58a4e2f8c82ee1375b05f8127b0a5d2e91297ca41b14eff6bebb3b6",
          "sha1": "9ca1895364140335ca1dbb7a443415108dbe2187",
          "md5": "3ecf381e7aa8e1e1943903a4319b857a"
        }
      ]
    }
  ]
}
