{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "field",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.12.aar",
          "url": "field-0.0.12.aar",
          "size": 894051,
          "sha512": "67e9ca730617893e416a77ccd436163086ab5f2b249dbc5c3c1f67c61512ab7d2eeef11c17b9fddab8bbcf072534ccded7925b98445a00e29afadec972adba07",
          "sha256": "cd4406eb8acd56308b0985dc624b8a599d9af6a32ef78d23f70b485fc6d9d885",
          "sha1": "ebd947d70e10ce859e91a89b6cc2c6647f3226b9",
          "md5": "6e2cd2d395cea55fe314f4a86a498913"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.12.aar",
          "url": "field-0.0.12.aar",
          "size": 894051,
          "sha512": "67e9ca730617893e416a77ccd436163086ab5f2b249dbc5c3c1f67c61512ab7d2eeef11c17b9fddab8bbcf072534ccded7925b98445a00e29afadec972adba07",
          "sha256": "cd4406eb8acd56308b0985dc624b8a599d9af6a32ef78d23f70b485fc6d9d885",
          "sha1": "ebd947d70e10ce859e91a89b6cc2c6647f3226b9",
          "md5": "6e2cd2d395cea55fe314f4a86a498913"
        }
      ]
    }
  ]
}
