{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "battery",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.9.aar",
          "url": "battery-0.0.9.aar",
          "size": 945837,
          "sha512": "1f8187f726ac06c4a0f321e4d0bf42707ff3ffa9a3d0d58cf695934a3d09b5a08c6b1c789dc5c61f9dd14e3eeb4054275b83001e38e9a2b93f128cd106f16a4b",
          "sha256": "4ee7b0a824586ac998bcf8b8531168fe8338a80f42707a8051cca783724ce92e",
          "sha1": "65998259e8ce150a3a770b2dea90ca28b5666de8",
          "md5": "2e89dfa030951f4682e44c8c145944f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.9.aar",
          "url": "battery-0.0.9.aar",
          "size": 945837,
          "sha512": "1f8187f726ac06c4a0f321e4d0bf42707ff3ffa9a3d0d58cf695934a3d09b5a08c6b1c789dc5c61f9dd14e3eeb4054275b83001e38e9a2b93f128cd106f16a4b",
          "sha256": "4ee7b0a824586ac998bcf8b8531168fe8338a80f42707a8051cca783724ce92e",
          "sha1": "65998259e8ce150a3a770b2dea90ca28b5666de8",
          "md5": "2e89dfa030951f4682e44c8c145944f1"
        }
      ]
    }
  ]
}
