{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "docs",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.3.aar",
          "url": "docs-0.0.3.aar",
          "size": 80739,
          "sha512": "16454cf84fd347f04db9e359753a939655b2d0ca00f46ba5805b805b21f14cead2816f680bf5e21a03e37f7fde1bd4f483bfb300099eff9a034e8aedd0ca3621",
          "sha256": "b11e8b05e3f3cb114bd5a95be881df9b43fbed8803c88d7b1fb5d1fb88935e70",
          "sha1": "d95b2a2257ef9a67c30fe4b08bd5e95db3835905",
          "md5": "60dfcdac9b0cd9d1b36a815714ed77c3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.3.aar",
          "url": "docs-0.0.3.aar",
          "size": 80739,
          "sha512": "16454cf84fd347f04db9e359753a939655b2d0ca00f46ba5805b805b21f14cead2816f680bf5e21a03e37f7fde1bd4f483bfb300099eff9a034e8aedd0ca3621",
          "sha256": "b11e8b05e3f3cb114bd5a95be881df9b43fbed8803c88d7b1fb5d1fb88935e70",
          "sha1": "d95b2a2257ef9a67c30fe4b08bd5e95db3835905",
          "md5": "60dfcdac9b0cd9d1b36a815714ed77c3"
        }
      ]
    }
  ]
}
