{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "gamepad",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.4.aar",
          "url": "gamepad-0.0.4.aar",
          "size": 2879550,
          "sha512": "5e01047e2d80b419a8c00467229bf83ec4b4b2676570d748fa5f5720942f57ef582407feecef0bcfdd1ec990502ea55a81ea80f1f397e8751bbf1961f73d25a2",
          "sha256": "f4edcb32e739f364449480e84a731da2b1c31fed7a615fa5c1fd989091b985f4",
          "sha1": "34fcc7d36a5a4f865d56b68b46317221c4942a8f",
          "md5": "41f1a6836508f5df0241e4d96714db63"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.4.aar",
          "url": "gamepad-0.0.4.aar",
          "size": 2879550,
          "sha512": "5e01047e2d80b419a8c00467229bf83ec4b4b2676570d748fa5f5720942f57ef582407feecef0bcfdd1ec990502ea55a81ea80f1f397e8751bbf1961f73d25a2",
          "sha256": "f4edcb32e739f364449480e84a731da2b1c31fed7a615fa5c1fd989091b985f4",
          "sha1": "34fcc7d36a5a4f865d56b68b46317221c4942a8f",
          "md5": "41f1a6836508f5df0241e4d96714db63"
        }
      ]
    }
  ]
}
