{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "gamepad",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.4.aar",
          "url": "gamepad-0.0.4.aar",
          "size": 2878796,
          "sha512": "033fd5958fd6ef182e3a73cb7e66b38b4849b4738cf5ed419a6774eb658e4b1e3f60fa69693f07f516e0c21b41024da3b77baa670d65caaf19438aad9147dbc9",
          "sha256": "a6c9fddea06ea3d415252d9858b8ff94e9f2e0d052c0e575b4621d63a3c342ba",
          "sha1": "c6c8534acd99f16739146e5a8a069b66289e791f",
          "md5": "ef6775a036e7f5cdd469c950db8b3537"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.4.aar",
          "url": "gamepad-0.0.4.aar",
          "size": 2878796,
          "sha512": "033fd5958fd6ef182e3a73cb7e66b38b4849b4738cf5ed419a6774eb658e4b1e3f60fa69693f07f516e0c21b41024da3b77baa670d65caaf19438aad9147dbc9",
          "sha256": "a6c9fddea06ea3d415252d9858b8ff94e9f2e0d052c0e575b4621d63a3c342ba",
          "sha1": "c6c8534acd99f16739146e5a8a069b66289e791f",
          "md5": "ef6775a036e7f5cdd469c950db8b3537"
        }
      ]
    }
  ]
}
