{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "themes",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.1.aar",
          "url": "themes-0.0.1.aar",
          "size": 93437,
          "sha512": "d2f7b189a3dca34d5c8f7ffe8aa1a56c5ce5089f2c1c95510b7d08356b9481f99cbba1182596648b5221177cd60739872f2fefd1c41ab672ff7580fa29cfa3eb",
          "sha256": "a0a499d7bc798ba62479aaf0cbf75948f3fef2f9a9be16d881cf081a0e1c3e18",
          "sha1": "e9880c481b13cac959e113d4fed3d539df659407",
          "md5": "7938c8d784c2f21b7c75cbb29e1f3dcf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.1.aar",
          "url": "themes-0.0.1.aar",
          "size": 93437,
          "sha512": "d2f7b189a3dca34d5c8f7ffe8aa1a56c5ce5089f2c1c95510b7d08356b9481f99cbba1182596648b5221177cd60739872f2fefd1c41ab672ff7580fa29cfa3eb",
          "sha256": "a0a499d7bc798ba62479aaf0cbf75948f3fef2f9a9be16d881cf081a0e1c3e18",
          "sha1": "e9880c481b13cac959e113d4fed3d539df659407",
          "md5": "7938c8d784c2f21b7c75cbb29e1f3dcf"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "themes-0.0.1-sources.jar",
          "url": "themes-0.0.1-sources.jar",
          "size": 1851,
          "sha512": "74da232fa553a8965c8a5e5e1fa215ad05c3ec9570138257656892ef95d8f1d976e77be0984357b42d236e90e53dfa9d29bdd73786c8d30cc2801c43eec093e7",
          "sha256": "2f4736717c78f10edead59249fc591e1370aef494070e2ee102e5e856f5c834c",
          "sha1": "4e0901b2bab42559ec7e0d6fa065a2d090977475",
          "md5": "95bb2831769f9018a648905661f6c105"
        }
      ]
    }
  ]
}
