{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "ftcontrol",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.5.1.aar",
          "url": "ftcontrol-0.5.1.aar",
          "size": 22157881,
          "sha512": "e2c46e8fb805d2651b4fdce40ee0ff385eb751e750b8e6dc1e16c83936bdf7477c3ee5cca12a00bc9aae0c470eb2b045834a6e67190ac517ce0e85a2b375e0c0",
          "sha256": "f8c80a21e7340acc5739bf97aef5e6d30dfb6ca5b0cee88e5cf65e58d41aeb79",
          "sha1": "7b72f7ac05d4af2beff8747125746c0df64e3305",
          "md5": "d65c103b8cae0e587d2c7fa7dc94e435"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.5.1.aar",
          "url": "ftcontrol-0.5.1.aar",
          "size": 22157881,
          "sha512": "e2c46e8fb805d2651b4fdce40ee0ff385eb751e750b8e6dc1e16c83936bdf7477c3ee5cca12a00bc9aae0c470eb2b045834a6e67190ac517ce0e85a2b375e0c0",
          "sha256": "f8c80a21e7340acc5739bf97aef5e6d30dfb6ca5b0cee88e5cf65e58d41aeb79",
          "sha1": "7b72f7ac05d4af2beff8747125746c0df64e3305",
          "md5": "d65c103b8cae0e587d2c7fa7dc94e435"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftcontrol-0.5.1-sources.jar",
          "url": "ftcontrol-0.5.1-sources.jar",
          "size": 88881,
          "sha512": "d24f9c6f51350a67779a2ea955912c8fd79b5703798c75b257b39e5678a505d88461d404ef32d37ebab43503839c3bea1654ccbef66a7d2a53bf7c2725403593",
          "sha256": "7976f33b52bea322f9bf6f81f45a306ad47b0d22b826fa30249fa72bcb2fb5a6",
          "sha1": "2db70fa7fcecaacddefdf92cd975f6724fba9736",
          "md5": "e801dff9b7d335958fb848f34777c952"
        }
      ]
    }
  ]
}
