{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "opmodecontrol",
    "version": "0.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.15.aar",
          "url": "opmodecontrol-0.0.15.aar",
          "size": 875134,
          "sha512": "edd9cca43f9da23fbd00c14ecb18f9bb8778ee9e037e99dfffde2b5dae74116390d15e8026e53ff74faee0e4a08616df40de4cdf1a5e0c9b9094198b0aab8933",
          "sha256": "39b8c1d0ace0478ed9bb2771c94b9ef6b42e8bb1ff035224469a9f5d7730ae37",
          "sha1": "68956a8eac1cd944432ee175f3928d1e0f7f1722",
          "md5": "d21ab065af5a56efee89e3dda4aa01fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.15.aar",
          "url": "opmodecontrol-0.0.15.aar",
          "size": 875134,
          "sha512": "edd9cca43f9da23fbd00c14ecb18f9bb8778ee9e037e99dfffde2b5dae74116390d15e8026e53ff74faee0e4a08616df40de4cdf1a5e0c9b9094198b0aab8933",
          "sha256": "39b8c1d0ace0478ed9bb2771c94b9ef6b42e8bb1ff035224469a9f5d7730ae37",
          "sha1": "68956a8eac1cd944432ee175f3928d1e0f7f1722",
          "md5": "d21ab065af5a56efee89e3dda4aa01fd"
        }
      ]
    }
  ]
}
