{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "themes",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.7.aar",
          "url": "themes-0.0.7.aar",
          "size": 1072289,
          "sha512": "7ff1a520cb074d2239d0c19b2121b7dcfb5659458e5a089a76b8d88c61837879cb67492e7996bd58902e65494a5f49506d01cb8e865d3a470529665d891a0775",
          "sha256": "48263d09c7c75c2879b7f06eaff6b3222ddd84fd6646b8c79847827a19ea94d7",
          "sha1": "de639ee97e25615b7754ae4ddade18e0258fc918",
          "md5": "748530230a5d36d3e4fd4ffbe2b944d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.7.aar",
          "url": "themes-0.0.7.aar",
          "size": 1072289,
          "sha512": "7ff1a520cb074d2239d0c19b2121b7dcfb5659458e5a089a76b8d88c61837879cb67492e7996bd58902e65494a5f49506d01cb8e865d3a470529665d891a0775",
          "sha256": "48263d09c7c75c2879b7f06eaff6b3222ddd84fd6646b8c79847827a19ea94d7",
          "sha1": "de639ee97e25615b7754ae4ddade18e0258fc918",
          "md5": "748530230a5d36d3e4fd4ffbe2b944d0"
        }
      ]
    }
  ]
}
