{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "fullpanels",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.bylazar",
          "module": "panels",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.bylazar",
          "module": "opmodecontrol",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "telemetry",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.bylazar",
          "module": "configurables",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.bylazar",
          "module": "themes",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "capture",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "limelightproxy",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.bylazar",
          "module": "gamepad",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.bylazar",
          "module": "field",
          "version": {
            "requires": "1.0.10"
          }
        },
        {
          "group": "com.bylazar",
          "module": "docs",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "com.bylazar",
          "module": "battery",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "utils",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.bylazar",
          "module": "pinger",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "graph",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.bylazar",
          "module": "lights",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "camerastream",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-1.0.17.aar",
          "url": "fullpanels-1.0.17.aar",
          "size": 62179,
          "sha512": "6aa7afe2276b8925fe071550a81bf6079d3e22535f1ad66eb08a5d6f0a89428f7b8bd500c4a7e159ff592232081a996d320794cfcdebc301499c1c3ef2a45e88",
          "sha256": "b6ce919ad5e413549fec0449cf4cdf9e57df09089f9dfc42b40793c2ca5eb6b4",
          "sha1": "0e770787a4d798a8e477e5bdf1a8c15b65e52678",
          "md5": "fb3fd97b7ec6689f965fe8a0a8ca63a7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.bylazar",
          "module": "panels",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.bylazar",
          "module": "opmodecontrol",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "telemetry",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.bylazar",
          "module": "configurables",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.bylazar",
          "module": "themes",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "capture",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "limelightproxy",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.bylazar",
          "module": "gamepad",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.bylazar",
          "module": "field",
          "version": {
            "requires": "1.0.10"
          }
        },
        {
          "group": "com.bylazar",
          "module": "docs",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "com.bylazar",
          "module": "battery",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "utils",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.bylazar",
          "module": "pinger",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "graph",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.bylazar",
          "module": "lights",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.bylazar",
          "module": "camerastream",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-1.0.17.aar",
          "url": "fullpanels-1.0.17.aar",
          "size": 62179,
          "sha512": "6aa7afe2276b8925fe071550a81bf6079d3e22535f1ad66eb08a5d6f0a89428f7b8bd500c4a7e159ff592232081a996d320794cfcdebc301499c1c3ef2a45e88",
          "sha256": "b6ce919ad5e413549fec0449cf4cdf9e57df09089f9dfc42b40793c2ca5eb6b4",
          "sha1": "0e770787a4d798a8e477e5bdf1a8c15b65e52678",
          "md5": "fb3fd97b7ec6689f965fe8a0a8ca63a7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fullpanels-1.0.17-sources.jar",
          "url": "fullpanels-1.0.17-sources.jar",
          "size": 1157,
          "sha512": "65ee73e19966c382e732c16b2e3880ee2f4bb848a3489b9d564efddd99a77c589d17bc5105007ae1c1f6559508a3712edb97da7673ee17f11e042cd973a438a4",
          "sha256": "fc00156f4f0d28ecf74ba3af615b23b11555f994367b3004b4fe565c0e640b4c",
          "sha1": "2a2adb79a6c3acd2e1f8f371a31da21f9eebf314",
          "md5": "ac09535e53e8b84de3b84b28d9f2ffab"
        }
      ]
    }
  ]
}
