{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "ftcontrol",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.3.0.aar",
          "url": "ftcontrol-0.3.0.aar",
          "size": 20743383,
          "sha512": "b711b55ce7e101dab8fd9a417a00ae9d6bdaa858e07730e4e2805e7e77ee391ba4ba842d9b4aee2dad1cc31d4d13dcd41367d56abda90af00a4fce065cf29248",
          "sha256": "389d625426afa4c613b69a41f2ee0ea74bbbe331a8dec6901c1218293a8598e9",
          "sha1": "a3417631c44337aa508390379b0cb23afceb4d9a",
          "md5": "9637293f223906ddf0418487d2e23ff4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.3.0.aar",
          "url": "ftcontrol-0.3.0.aar",
          "size": 20743383,
          "sha512": "b711b55ce7e101dab8fd9a417a00ae9d6bdaa858e07730e4e2805e7e77ee391ba4ba842d9b4aee2dad1cc31d4d13dcd41367d56abda90af00a4fce065cf29248",
          "sha256": "389d625426afa4c613b69a41f2ee0ea74bbbe331a8dec6901c1218293a8598e9",
          "sha1": "a3417631c44337aa508390379b0cb23afceb4d9a",
          "md5": "9637293f223906ddf0418487d2e23ff4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftcontrol-0.3.0-sources.jar",
          "url": "ftcontrol-0.3.0-sources.jar",
          "size": 67783,
          "sha512": "8a5753f9727fdeb05a6442abed4e8d22dba3ef72f19c6cbc99741452f51d4d91a2f1d2168692420327d1738bc48fd8c09193c725e7809c092be433e794a6758c",
          "sha256": "41ad0bd48ae8665a266878553625bb6a4a52544c7a4f8848b4ccd8b6662bbae6",
          "sha1": "eef920a1d093480b46062cb712ceed414f5a232a",
          "md5": "93e3115772d579123a719d60fa706fbc"
        }
      ]
    }
  ]
}
