{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "ftcontrol",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.4.3.aar",
          "url": "ftcontrol-0.4.3.aar",
          "size": 28758812,
          "sha512": "6e909de273918643e28c651ab1734da4f77a4465d03c6465915f89f648304918cb89d74e30e9087e42f3b7c94456b53e3edad8757e155f97779f5055cb83fa43",
          "sha256": "3d1c3fc96f67b32e4a0f03c2c8dbd3c84d1b016ad75220a2acba6a66805123ec",
          "sha1": "3f4939aaecdb73fa4a91aaafd3805cc72c7b85f9",
          "md5": "a59055c26b57fddfcee16d4712b8d68c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.4.3.aar",
          "url": "ftcontrol-0.4.3.aar",
          "size": 28758812,
          "sha512": "6e909de273918643e28c651ab1734da4f77a4465d03c6465915f89f648304918cb89d74e30e9087e42f3b7c94456b53e3edad8757e155f97779f5055cb83fa43",
          "sha256": "3d1c3fc96f67b32e4a0f03c2c8dbd3c84d1b016ad75220a2acba6a66805123ec",
          "sha1": "3f4939aaecdb73fa4a91aaafd3805cc72c7b85f9",
          "md5": "a59055c26b57fddfcee16d4712b8d68c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftcontrol-0.4.3-sources.jar",
          "url": "ftcontrol-0.4.3-sources.jar",
          "size": 87563,
          "sha512": "be4c52326261c9a6046f8a6c3ddb798f03fffd291de33089ff6abe148c05f9ef7d5a0bd23e07c303b5417b2f85a1b0ca6ea492372bbbee88331aad1ce71f14db",
          "sha256": "ea7c4b95299acfa441405dd006e76b96087a90c23064453486edcb4a257fb66c",
          "sha1": "e37b1e702d032e3726d0cd52174a0331902844ff",
          "md5": "a75480061f6766962edb8a4de2772592"
        }
      ]
    }
  ]
}
