{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.2.aar",
          "url": "panels-0.0.2.aar",
          "size": 20234976,
          "sha512": "f96807b3bc6fa2baaef18de88b44fe02c1440c77f45d2fff240ad03ede9345d1685e73ff39efca811c4f72f46c9149054f3dde4531072274b6567a07070eeb51",
          "sha256": "4044f3ff4884b6969d1c156fc2faa972b13f94547a6d350615cd3e1588836152",
          "sha1": "7ac143ff26c4ea14befd8ec0669783f62a4f75bd",
          "md5": "e2966cb988e9d83cb85fec215cec6792"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.2.aar",
          "url": "panels-0.0.2.aar",
          "size": 20234976,
          "sha512": "f96807b3bc6fa2baaef18de88b44fe02c1440c77f45d2fff240ad03ede9345d1685e73ff39efca811c4f72f46c9149054f3dde4531072274b6567a07070eeb51",
          "sha256": "4044f3ff4884b6969d1c156fc2faa972b13f94547a6d350615cd3e1588836152",
          "sha1": "7ac143ff26c4ea14befd8ec0669783f62a4f75bd",
          "md5": "e2966cb988e9d83cb85fec215cec6792"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "panels-0.0.2-sources.jar",
          "url": "panels-0.0.2-sources.jar",
          "size": 33167,
          "sha512": "0ecf375f2c90feddd27a5243415cb805eb3107313103992288337b126aa15f29bd98843fc2f2844e780788aa9893a719d44507e5a896ffa0f68e3aaf786dcf46",
          "sha256": "17dd79098d636c03def2a8ac46a4a9fc6682996db10190e6ece57d62877fc9c4",
          "sha1": "8da97e31f81cd69da76a01d0c807671854c9f273",
          "md5": "7dbcce7efe95644f54ff827a407e34ef"
        }
      ]
    }
  ]
}
