{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "exampleplugin",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.3.aar",
          "url": "exampleplugin-0.0.3.aar",
          "size": 83422,
          "sha512": "31d3826db3e81b2fde9fd50d3fb7908e04489291fe2d35436b7fa65511a665b099e7d9653228750290e78c8853e970e9c81481c6a448a6ca6f345ad8b2fb510e",
          "sha256": "a0cd3ba0fdb54e81c2cc39fc01d186ee6f73a02e21ef278a2e1a93e22a7b8dd9",
          "sha1": "dd3e20fea3f9cdda8621fb725913a84217664d54",
          "md5": "3cfce4501795ac68638eb3b9bd7875e2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.3.aar",
          "url": "exampleplugin-0.0.3.aar",
          "size": 83422,
          "sha512": "31d3826db3e81b2fde9fd50d3fb7908e04489291fe2d35436b7fa65511a665b099e7d9653228750290e78c8853e970e9c81481c6a448a6ca6f345ad8b2fb510e",
          "sha256": "a0cd3ba0fdb54e81c2cc39fc01d186ee6f73a02e21ef278a2e1a93e22a7b8dd9",
          "sha1": "dd3e20fea3f9cdda8621fb725913a84217664d54",
          "md5": "3cfce4501795ac68638eb3b9bd7875e2"
        }
      ]
    }
  ]
}
