{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "ftcontrol",
    "version": "0.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.5.7.aar",
          "url": "ftcontrol-0.5.7.aar",
          "size": 30665245,
          "sha512": "b8063b50646de6e81a1a684c61dcbd2c0604ce3ce41135078792268da727263944d480104cff2482fcf8ec03ae509b026beab3aa3d3d48b268c500ea1ecff2f0",
          "sha256": "0c46888673deaa109581e91323a51f24a12d77d7928125a2b4f62eaac7a181f3",
          "sha1": "ba193be51ddbbcbe72099004af9e09fd7b90161e",
          "md5": "cef1b3f41237a928f08595f5085fd09f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.5.7.aar",
          "url": "ftcontrol-0.5.7.aar",
          "size": 30665245,
          "sha512": "b8063b50646de6e81a1a684c61dcbd2c0604ce3ce41135078792268da727263944d480104cff2482fcf8ec03ae509b026beab3aa3d3d48b268c500ea1ecff2f0",
          "sha256": "0c46888673deaa109581e91323a51f24a12d77d7928125a2b4f62eaac7a181f3",
          "sha1": "ba193be51ddbbcbe72099004af9e09fd7b90161e",
          "md5": "cef1b3f41237a928f08595f5085fd09f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftcontrol-0.5.7-sources.jar",
          "url": "ftcontrol-0.5.7-sources.jar",
          "size": 87683,
          "sha512": "eb04fbd24ee179240922af6a1aa55e044b47d6fe12569dfdb15242e9376478c963b38de435bb083a3197abf48e0e11712dc301b19ebbdabf4a54514e51b33973",
          "sha256": "682cf85e5086063d539370c7ba13a1d7f4ff158962a4b5b52475b5a10ff665af",
          "sha1": "0e59fe41fe9f344d8608b38760a044e54164d74c",
          "md5": "a287be6c3a0a320636963ecc5d078fb1"
        }
      ]
    }
  ]
}
