{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "docs",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.11.aar",
          "url": "docs-0.0.11.aar",
          "size": 224760,
          "sha512": "780e29c1482e5635fc1fd27e9df7eaa51cdc783a0d5e0255a5312e9e2a87228af374cbbb9431e71267d3ba8dc2d268b206eb0ab42555153ec59279ceab447e0c",
          "sha256": "5b3b240d4584814ea44e698c9b77b122aeb94810a3d1f4f40339a860d1f2b960",
          "sha1": "8a131781a6925899be9a20ce041401f91107cd45",
          "md5": "5b232bb4d7989d46f89898bef9473e1f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.11.aar",
          "url": "docs-0.0.11.aar",
          "size": 224760,
          "sha512": "780e29c1482e5635fc1fd27e9df7eaa51cdc783a0d5e0255a5312e9e2a87228af374cbbb9431e71267d3ba8dc2d268b206eb0ab42555153ec59279ceab447e0c",
          "sha256": "5b3b240d4584814ea44e698c9b77b122aeb94810a3d1f4f40339a860d1f2b960",
          "sha1": "8a131781a6925899be9a20ce041401f91107cd45",
          "md5": "5b232bb4d7989d46f89898bef9473e1f"
        }
      ]
    }
  ]
}
