{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "opmodecontrol",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.12.aar",
          "url": "opmodecontrol-0.0.12.aar",
          "size": 875119,
          "sha512": "e8dfeb2cd83ffc0e4122088bdbc7b2d5287c03701fd7fa344a4b6e0ba27fc5bec944b1e76b3a743400cc62969aa91854cacc5ae156d1ccda01569c3e0027c778",
          "sha256": "8322e87cae17fbf859809647d904331e3d58ccfc8113971282751ba82aada6e4",
          "sha1": "c9f9629180d6aa5e9777fa3fd86bd901683c7aaa",
          "md5": "7694425b67b18bf658f41a550fa040ac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.12.aar",
          "url": "opmodecontrol-0.0.12.aar",
          "size": 875119,
          "sha512": "e8dfeb2cd83ffc0e4122088bdbc7b2d5287c03701fd7fa344a4b6e0ba27fc5bec944b1e76b3a743400cc62969aa91854cacc5ae156d1ccda01569c3e0027c778",
          "sha256": "8322e87cae17fbf859809647d904331e3d58ccfc8113971282751ba82aada6e4",
          "sha1": "c9f9629180d6aa5e9777fa3fd86bd901683c7aaa",
          "md5": "7694425b67b18bf658f41a550fa040ac"
        }
      ]
    }
  ]
}
