{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "telemetry",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.2.aar",
          "url": "telemetry-0.0.2.aar",
          "size": 89182,
          "sha512": "29092f01438df06ec737d3caa72fd742029a5d17fdcff60e6ffef73c9d7588dda93282bc675dc5ff662afccd9e021649cd23a17e663291d5e1a4f6318f58b16f",
          "sha256": "84275c85bf93baa64df1e362ac03964c58066c63b4ba8b892ffa147b0b36d16f",
          "sha1": "25be6cd81951df02d7170bff648cf07c885a3814",
          "md5": "4d68d40736f59f65a09c04daca22500b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.2.aar",
          "url": "telemetry-0.0.2.aar",
          "size": 89182,
          "sha512": "29092f01438df06ec737d3caa72fd742029a5d17fdcff60e6ffef73c9d7588dda93282bc675dc5ff662afccd9e021649cd23a17e663291d5e1a4f6318f58b16f",
          "sha256": "84275c85bf93baa64df1e362ac03964c58066c63b4ba8b892ffa147b0b36d16f",
          "sha1": "25be6cd81951df02d7170bff648cf07c885a3814",
          "md5": "4d68d40736f59f65a09c04daca22500b"
        }
      ]
    }
  ]
}
