{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "telemetry",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.2.aar",
          "url": "telemetry-0.0.2.aar",
          "size": 88948,
          "sha512": "7b0d3c217a1cee736b7bb3b337d067252dd464f9d306bfe5606ebd66c4d083a7aa54ee20106e53fcaaa231943c62044379d7c09372e2927ebad1ca4659e41221",
          "sha256": "87ea3a460e18924ce1bd5d48f0b643db4bfad7f7388fb3678184049cc8df656d",
          "sha1": "a29aef8db8d6eeb68b676fd3a6e7f4ecbf6e5212",
          "md5": "ab6e9a403ee76ef5ccce7b579c573029"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.2.aar",
          "url": "telemetry-0.0.2.aar",
          "size": 88948,
          "sha512": "7b0d3c217a1cee736b7bb3b337d067252dd464f9d306bfe5606ebd66c4d083a7aa54ee20106e53fcaaa231943c62044379d7c09372e2927ebad1ca4659e41221",
          "sha256": "87ea3a460e18924ce1bd5d48f0b643db4bfad7f7388fb3678184049cc8df656d",
          "sha1": "a29aef8db8d6eeb68b676fd3a6e7f4ecbf6e5212",
          "md5": "ab6e9a403ee76ef5ccce7b579c573029"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "telemetry-0.0.2-sources.jar",
          "url": "telemetry-0.0.2-sources.jar",
          "size": 4361,
          "sha512": "b586262ed56ae1eb951a0549725d91bb65d49108023deaf30a343a2bd92176d0f371803acf16a541922b0d0e96d1e77781c5174423897eb0a218d0093464e2ae",
          "sha256": "d301b0ac116eb24765d1b86642d02aa49c7b2e18378ecde6ce285aa7367497c7",
          "sha1": "8fe3065b2c83511adc1d080d5139957d0ae516e8",
          "md5": "7610b1ff5ed90b56cc3f0f83ee79f709"
        }
      ]
    }
  ]
}
