{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "limelightproxy",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-1.0.0.aar",
          "url": "limelightproxy-1.0.0.aar",
          "size": 1677033,
          "sha512": "ec95e481b62776f262889ca445e4b2571ce0935b42805299712b18c5fe18414a76c30d38ebb7ae1e4a724438eb4f19eabd4a8ee9d513f2c4e8aab879d37588b3",
          "sha256": "8ec0ac71231939151e76d24b19575745923ea81fbea3c18aaa3c6618636e92a5",
          "sha1": "4f92c09e43342bc65ef2f1262699b263c7b40479",
          "md5": "a35d4851b333442cfefdbff02f7a0144"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-1.0.0.aar",
          "url": "limelightproxy-1.0.0.aar",
          "size": 1677033,
          "sha512": "ec95e481b62776f262889ca445e4b2571ce0935b42805299712b18c5fe18414a76c30d38ebb7ae1e4a724438eb4f19eabd4a8ee9d513f2c4e8aab879d37588b3",
          "sha256": "8ec0ac71231939151e76d24b19575745923ea81fbea3c18aaa3c6618636e92a5",
          "sha1": "4f92c09e43342bc65ef2f1262699b263c7b40479",
          "md5": "a35d4851b333442cfefdbff02f7a0144"
        }
      ]
    }
  ]
}
