{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "limelightproxy",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.8.aar",
          "url": "limelightproxy-0.0.8.aar",
          "size": 136888,
          "sha512": "6e77f5f973dbe448e7242fcd44e246ff57302588b0fcd18df620ea8364cd00a11b52f4f89e5cd13e401d48bfcb863c37a6769f462c0d2ac218c1f14ecdd3897d",
          "sha256": "34e8ecf72654f0a6373e2e4745343bdf2f2426616f2a09eff5065c663e122a06",
          "sha1": "78256b822e66dbce8ff43ca150ba37f4e5b23346",
          "md5": "2fbde2bbc9d69e047da28cf74ca1b1c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.8.aar",
          "url": "limelightproxy-0.0.8.aar",
          "size": 136888,
          "sha512": "6e77f5f973dbe448e7242fcd44e246ff57302588b0fcd18df620ea8364cd00a11b52f4f89e5cd13e401d48bfcb863c37a6769f462c0d2ac218c1f14ecdd3897d",
          "sha256": "34e8ecf72654f0a6373e2e4745343bdf2f2426616f2a09eff5065c663e122a06",
          "sha1": "78256b822e66dbce8ff43ca150ba37f4e5b23346",
          "md5": "2fbde2bbc9d69e047da28cf74ca1b1c9"
        }
      ]
    }
  ]
}
