{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "limelightproxy",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.8.aar",
          "url": "limelightproxy-0.0.8.aar",
          "size": 495087,
          "sha512": "b2121bc3c2f014006e7eb21b2335f180361e6afb9b0c61280f927747edecf37b40a07c2a72d7e295688674031aad32316e3175ccdc66beafd0da2d19722f00bb",
          "sha256": "d9637f1c5d37c0abae2b9a4db1c340978bf311d068d086b8e6a34eb9dd8c869e",
          "sha1": "78277bde739a5c3fde307180692f01c183b8d863",
          "md5": "94f9961b39ec3fdca42e007a6eb65e20"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.8.aar",
          "url": "limelightproxy-0.0.8.aar",
          "size": 495087,
          "sha512": "b2121bc3c2f014006e7eb21b2335f180361e6afb9b0c61280f927747edecf37b40a07c2a72d7e295688674031aad32316e3175ccdc66beafd0da2d19722f00bb",
          "sha256": "d9637f1c5d37c0abae2b9a4db1c340978bf311d068d086b8e6a34eb9dd8c869e",
          "sha1": "78277bde739a5c3fde307180692f01c183b8d863",
          "md5": "94f9961b39ec3fdca42e007a6eb65e20"
        }
      ]
    }
  ]
}
