{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "exampleplugin",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.2.aar",
          "url": "exampleplugin-0.0.2.aar",
          "size": 83559,
          "sha512": "cf975f3411cdc0a4f22b97e7187e5cbc62c8634921f4bfc66e738a9f09893227a46aa8991bf709339c7135180183e033162b4b9551921ccc6cad9eb8f06dfbad",
          "sha256": "a73b474f785d0725a25cf651fca22fe99ae9b95e95ce29904fbf9d38f7f79025",
          "sha1": "301a495bd4c433c18e4296c3c083dadd833d1cc4",
          "md5": "f04ca29b5df2afef17bdae159fd15d13"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.2.aar",
          "url": "exampleplugin-0.0.2.aar",
          "size": 83559,
          "sha512": "cf975f3411cdc0a4f22b97e7187e5cbc62c8634921f4bfc66e738a9f09893227a46aa8991bf709339c7135180183e033162b4b9551921ccc6cad9eb8f06dfbad",
          "sha256": "a73b474f785d0725a25cf651fca22fe99ae9b95e95ce29904fbf9d38f7f79025",
          "sha1": "301a495bd4c433c18e4296c3c083dadd833d1cc4",
          "md5": "f04ca29b5df2afef17bdae159fd15d13"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "exampleplugin-0.0.2-sources.jar",
          "url": "exampleplugin-0.0.2-sources.jar",
          "size": 2395,
          "sha512": "7a4f75a6fef9107d59c6e3dd9854dc940add8c74f8de8042c59f234f7462feb73ddfb79b796f608492740721b0cc2a18e6c6a497e8e261a63c2e6c358e23f47b",
          "sha256": "479368dfb6d53a183a44252c467a85b8676f75fca9b397b12c2d754aa4f2e0ac",
          "sha1": "c3589270cefa09f52b664674e3d9c420246663c6",
          "md5": "2f04927b41644e5ff03ca1abd39dae97"
        }
      ]
    }
  ]
}
