{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "battery",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.13.aar",
          "url": "battery-0.0.13.aar",
          "size": 522647,
          "sha512": "a4dc9c60ef44ae86e6a27c9f8f93259d378914a709a4237a4bb833a1de1238bb2e34dc55e0ebc73371a6f0986f26a1c1ecf795cfd4785f78fd93eb7ddaeb3d53",
          "sha256": "f256915e2d649993bb594e585de3922b3b5cae1a59bb227b2c43dc505f979c8e",
          "sha1": "a33b0c6074b98eebe7e6816e9eaaf1c013cac74e",
          "md5": "d75d36c8c70c0ebc018adba3e70a8765"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.13.aar",
          "url": "battery-0.0.13.aar",
          "size": 522647,
          "sha512": "a4dc9c60ef44ae86e6a27c9f8f93259d378914a709a4237a4bb833a1de1238bb2e34dc55e0ebc73371a6f0986f26a1c1ecf795cfd4785f78fd93eb7ddaeb3d53",
          "sha256": "f256915e2d649993bb594e585de3922b3b5cae1a59bb227b2c43dc505f979c8e",
          "sha1": "a33b0c6074b98eebe7e6816e9eaaf1c013cac74e",
          "md5": "d75d36c8c70c0ebc018adba3e70a8765"
        }
      ]
    }
  ]
}
