{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "exampleplugin",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.7.aar",
          "url": "exampleplugin-0.0.7.aar",
          "size": 428885,
          "sha512": "1de82ee6b2f61108d1a6a7105bbdce778f732c27aff7afc7d95fc2a3d4e8f9f30178aa97b60008b44d73d204d45aacb95209ab1c309b23f5fb6b09425a44aec3",
          "sha256": "dcbe1930c5b1acb0f73c27bdde02fd2e8d6abf2a682c9fd1a7a269b0596c0be9",
          "sha1": "82802988a339f4e93c62433468c571e4f0e9a0f5",
          "md5": "af86eb681ce3261020e6127309bc4aef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.7.aar",
          "url": "exampleplugin-0.0.7.aar",
          "size": 428885,
          "sha512": "1de82ee6b2f61108d1a6a7105bbdce778f732c27aff7afc7d95fc2a3d4e8f9f30178aa97b60008b44d73d204d45aacb95209ab1c309b23f5fb6b09425a44aec3",
          "sha256": "dcbe1930c5b1acb0f73c27bdde02fd2e8d6abf2a682c9fd1a7a269b0596c0be9",
          "sha1": "82802988a339f4e93c62433468c571e4f0e9a0f5",
          "md5": "af86eb681ce3261020e6127309bc4aef"
        }
      ]
    }
  ]
}
