{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "field",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-1.0.9.aar",
          "url": "field-1.0.9.aar",
          "size": 1023476,
          "sha512": "5f63ed067af3c53aaa6a1c11f9739bd7b05335e39872cc0e4ffad450371e787eef0128e0363b541a8a9837e948bf778ba003da07282865342bfb399b8423ae44",
          "sha256": "355c9f2b959013c6cc912a4d7858709e75ea146a22eaf2c7266645459ca80ad8",
          "sha1": "4caa7dd8f838ed2d3f22e4f58ce2361bbc570daa",
          "md5": "41d0e06b335a371677ab60c038d0d52b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-1.0.9.aar",
          "url": "field-1.0.9.aar",
          "size": 1023476,
          "sha512": "5f63ed067af3c53aaa6a1c11f9739bd7b05335e39872cc0e4ffad450371e787eef0128e0363b541a8a9837e948bf778ba003da07282865342bfb399b8423ae44",
          "sha256": "355c9f2b959013c6cc912a4d7858709e75ea146a22eaf2c7266645459ca80ad8",
          "sha1": "4caa7dd8f838ed2d3f22e4f58ce2361bbc570daa",
          "md5": "41d0e06b335a371677ab60c038d0d52b"
        }
      ]
    }
  ]
}
