{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "ftcontrol",
    "version": "0.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.6.7.aar",
          "url": "ftcontrol-0.6.7.aar",
          "size": 22710172,
          "sha512": "ad4aa51437357a038dddad075de9723654294143b1bb3212443812962d393b06f97e8164c4792a1d375033b9fe59505a340af6ea7bf3e351b17697302f367e68",
          "sha256": "ad2b72991d993b765ab472430cfc9040bc8b3daf6c2cc6d13d46f623c522d437",
          "sha1": "b964aeb99192be5438b131d099ba029a5bc5420b",
          "md5": "51e5e104b10050cb58972b4683b6aebf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.6.7.aar",
          "url": "ftcontrol-0.6.7.aar",
          "size": 22710172,
          "sha512": "ad4aa51437357a038dddad075de9723654294143b1bb3212443812962d393b06f97e8164c4792a1d375033b9fe59505a340af6ea7bf3e351b17697302f367e68",
          "sha256": "ad2b72991d993b765ab472430cfc9040bc8b3daf6c2cc6d13d46f623c522d437",
          "sha1": "b964aeb99192be5438b131d099ba029a5bc5420b",
          "md5": "51e5e104b10050cb58972b4683b6aebf"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftcontrol-0.6.7-sources.jar",
          "url": "ftcontrol-0.6.7-sources.jar",
          "size": 98343,
          "sha512": "edfe12d29f9a695b4f1482e65ba6f600927b16be68c057c4e9af1de02e1b9060f18bb60f811a45f36bd1d12c4d2ee61e36efdf385e1525614a4649b87295b7af",
          "sha256": "ecb1dd2184ba6d364401e35f1d892e3b973ea7b7730e254e0e9c4f1abddf9659",
          "sha1": "87afd890a3118162cd8dac2504f10b9992772280",
          "md5": "a7911593d4a848f86920219f4c7af024"
        }
      ]
    }
  ]
}
