{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "gamepad",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.12.aar",
          "url": "gamepad-0.0.12.aar",
          "size": 8845136,
          "sha512": "4335add045532eb3fef520734a3615d529669148ac3b9077b38c2c852f080ecd8d074eed8d2cb80dc3abf631da6b1d036cdef6270bee60172f1dd2f8b88faf31",
          "sha256": "018c1e032bbdf5cdb1e477084eb52b944995af4387b4f083f25046dd5f29d2b3",
          "sha1": "727202dbd941d9cd6f2cd39f3217dc233da8ca79",
          "md5": "15b6e9e6b748dc1d20bbe6df5ada30be"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.12.aar",
          "url": "gamepad-0.0.12.aar",
          "size": 8845136,
          "sha512": "4335add045532eb3fef520734a3615d529669148ac3b9077b38c2c852f080ecd8d074eed8d2cb80dc3abf631da6b1d036cdef6270bee60172f1dd2f8b88faf31",
          "sha256": "018c1e032bbdf5cdb1e477084eb52b944995af4387b4f083f25046dd5f29d2b3",
          "sha1": "727202dbd941d9cd6f2cd39f3217dc233da8ca79",
          "md5": "15b6e9e6b748dc1d20bbe6df5ada30be"
        }
      ]
    }
  ]
}
