{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "field",
    "version": "0.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.16.aar",
          "url": "field-0.0.16.aar",
          "size": 894042,
          "sha512": "a308f8813ec0cdc013b0527db11c9769bdc721c10181b22665fe157194763a0529cff4898e7fd2f394a5a0c49dee2f62852fde02ac4f4a1132b106bf18baf794",
          "sha256": "730355e409ecd9523f8bdf6e3803e9f81531ad7ce8bbb15fb102ade58fdd74ee",
          "sha1": "eda458d03fc25802fcea2ec1c6cb4514841c9775",
          "md5": "2cd1e6da5148db3a206b6d4b43881f54"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.16.aar",
          "url": "field-0.0.16.aar",
          "size": 894042,
          "sha512": "a308f8813ec0cdc013b0527db11c9769bdc721c10181b22665fe157194763a0529cff4898e7fd2f394a5a0c49dee2f62852fde02ac4f4a1132b106bf18baf794",
          "sha256": "730355e409ecd9523f8bdf6e3803e9f81531ad7ce8bbb15fb102ade58fdd74ee",
          "sha1": "eda458d03fc25802fcea2ec1c6cb4514841c9775",
          "md5": "2cd1e6da5148db3a206b6d4b43881f54"
        }
      ]
    }
  ]
}
