{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "ftcontrol",
    "version": "0.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.6.5.aar",
          "url": "ftcontrol-0.6.5.aar",
          "size": 34812465,
          "sha512": "9f19edb645b4811319969c3636c7f15aa856c80e7ca719c9a45b3391e093d1cf7bffb53ed094806710fb3ca96e69e7693bb57ecea400d508f060701689d26612",
          "sha256": "9df1f6fbe75fd922c74f85a5a0e992c366ea31a94e8ac2beb06abb017ae7116c",
          "sha1": "9caf10fd4596c280f5962f3ba4a2895be85e87f8",
          "md5": "48f00ffe419bee4e3ee5cea5fcf58edf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.6.5.aar",
          "url": "ftcontrol-0.6.5.aar",
          "size": 34812465,
          "sha512": "9f19edb645b4811319969c3636c7f15aa856c80e7ca719c9a45b3391e093d1cf7bffb53ed094806710fb3ca96e69e7693bb57ecea400d508f060701689d26612",
          "sha256": "9df1f6fbe75fd922c74f85a5a0e992c366ea31a94e8ac2beb06abb017ae7116c",
          "sha1": "9caf10fd4596c280f5962f3ba4a2895be85e87f8",
          "md5": "48f00ffe419bee4e3ee5cea5fcf58edf"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftcontrol-0.6.5-sources.jar",
          "url": "ftcontrol-0.6.5-sources.jar",
          "size": 95185,
          "sha512": "890d45c66c83c9c9304b8d9180f961940a3c1fa5d9e278cf0bbfe1c56d2fcc184cd34dbc93d416f99df0cbd4612cc6eaa59dfcf6634a5659f6b62c7e06c2d9d8",
          "sha256": "08a13b763d1d1752261610a056ccf0577fa0279cd5cafd6b316d89a6755708ad",
          "sha1": "547c4e694027bdaf239e22752315024dedc1632c",
          "md5": "d1752767788f82795bc66b2c919be9b7"
        }
      ]
    }
  ]
}
