{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.5.aar",
          "url": "panels-0.0.5.aar",
          "size": 262887,
          "sha512": "013ad2699a014e28d5e84c5f43914a681d97ca3039371eb9d6a535730de44ac0723820c9299d9d5fe24fafd8c498fb5df1e39531f755437958459c266447130e",
          "sha256": "d79ec81c3212bc1b9a6c1c75bc80144a61d4a2f2de9f6adf19c3e7aefc5f9d4a",
          "sha1": "ecc338db38cb88ba2ee97ad7b3590a23f98a5986",
          "md5": "b68412f8b5803076222979b498bae04c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.5.aar",
          "url": "panels-0.0.5.aar",
          "size": 262887,
          "sha512": "013ad2699a014e28d5e84c5f43914a681d97ca3039371eb9d6a535730de44ac0723820c9299d9d5fe24fafd8c498fb5df1e39531f755437958459c266447130e",
          "sha256": "d79ec81c3212bc1b9a6c1c75bc80144a61d4a2f2de9f6adf19c3e7aefc5f9d4a",
          "sha1": "ecc338db38cb88ba2ee97ad7b3590a23f98a5986",
          "md5": "b68412f8b5803076222979b498bae04c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "panels-0.0.5-sources.jar",
          "url": "panels-0.0.5-sources.jar",
          "size": 34595,
          "sha512": "d427e14ce13eb3b400d0e6bf758a34621e0f2f939996f5cffef802b418bd556dfe2df388460839bf2400570e11f61b2dc7380569d31d067f7729cbe4f6234df1",
          "sha256": "98fad9e0773791c116a1d5c8f7713976887feb30e83c38b49971e55ec34e727f",
          "sha1": "f700a3e540a1732b81f649e3df6d6f5950c85913",
          "md5": "f0e3e22ced54a96b4ae385dc04f60a18"
        }
      ]
    }
  ]
}
