{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "gamepad",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.14.aar",
          "url": "gamepad-0.0.14.aar",
          "size": 3005848,
          "sha512": "af4366295f8f982e30997fb7339fde9fd32f1d8dabda0a24ec52f119f7c4b34a1b1cb7e866b09f675639db6da0b3fd5dd6751b3fa9e70268fa71345bbdd9c95b",
          "sha256": "570569a00bfb31dcd3aee3919242dec71ff6cba601cfabf02315e86cb4002b55",
          "sha1": "c1c8c387c2afb78af6bfd1807017ffc6b1d9403f",
          "md5": "1d68627aa33facad838605bec866288f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.14.aar",
          "url": "gamepad-0.0.14.aar",
          "size": 3005848,
          "sha512": "af4366295f8f982e30997fb7339fde9fd32f1d8dabda0a24ec52f119f7c4b34a1b1cb7e866b09f675639db6da0b3fd5dd6751b3fa9e70268fa71345bbdd9c95b",
          "sha256": "570569a00bfb31dcd3aee3919242dec71ff6cba601cfabf02315e86cb4002b55",
          "sha1": "c1c8c387c2afb78af6bfd1807017ffc6b1d9403f",
          "md5": "1d68627aa33facad838605bec866288f"
        }
      ]
    }
  ]
}
