{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "gamepad",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.6.aar",
          "url": "gamepad-0.0.6.aar",
          "size": 2879457,
          "sha512": "7438bad03056e548913e24d99999659ed8b04f73f02e60ac2bd17899260d4afe0fb94ea76c1e1b15b1aef357f0292a932c5cb89fc47a05ab82d1e62a826408e3",
          "sha256": "ec6b2252a5c53cb5885a290b63657b6fae76c5eeb09c88efa594c17b22d47499",
          "sha1": "fd6ea95954548cc636b52210dfe7affc96eb5f77",
          "md5": "d685177c00bc2933a638283cf9670d39"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.6.aar",
          "url": "gamepad-0.0.6.aar",
          "size": 2879457,
          "sha512": "7438bad03056e548913e24d99999659ed8b04f73f02e60ac2bd17899260d4afe0fb94ea76c1e1b15b1aef357f0292a932c5cb89fc47a05ab82d1e62a826408e3",
          "sha256": "ec6b2252a5c53cb5885a290b63657b6fae76c5eeb09c88efa594c17b22d47499",
          "sha1": "fd6ea95954548cc636b52210dfe7affc96eb5f77",
          "md5": "d685177c00bc2933a638283cf9670d39"
        }
      ]
    }
  ]
}
