{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "telemetry",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.3.aar",
          "url": "telemetry-0.0.3.aar",
          "size": 89183,
          "sha512": "f794b3f814f82120633002b6bda2b255320ef2613b5c19c2c4ee54ce4f2a884ec45509a1c3c826cc4976f6e3d5e696a196926dcfa9f46501ca93373de58643d9",
          "sha256": "a4d269200f171f7382b2d0f3121c732018dafb3d5dd8a15334efb1950d3161cc",
          "sha1": "ec5692cd3f5e247c51dbd2f229a2a291a9ed6d1a",
          "md5": "6dff96cec0d5ac5a07ace952d83e1a79"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.3.aar",
          "url": "telemetry-0.0.3.aar",
          "size": 89183,
          "sha512": "f794b3f814f82120633002b6bda2b255320ef2613b5c19c2c4ee54ce4f2a884ec45509a1c3c826cc4976f6e3d5e696a196926dcfa9f46501ca93373de58643d9",
          "sha256": "a4d269200f171f7382b2d0f3121c732018dafb3d5dd8a15334efb1950d3161cc",
          "sha1": "ec5692cd3f5e247c51dbd2f229a2a291a9ed6d1a",
          "md5": "6dff96cec0d5ac5a07ace952d83e1a79"
        }
      ]
    }
  ]
}
