{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "opmodecontrol",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.6.aar",
          "url": "opmodecontrol-0.0.6.aar",
          "size": 729203,
          "sha512": "be82e385d7913852b626565be26b023f95e83cd6641f8903b6f568344d5945e5d7b5cbd3a232da75d500081cfcfc2aa770f1e13df0615666c4e37c6551caa483",
          "sha256": "4ab034786f0b706eb62281ffb9a4d58bf30842f23e7d375c44f153395d731a24",
          "sha1": "b7233b556c679c9ba5cad5610449e024e0cfcff3",
          "md5": "b29ad797bd7cc18e219091c2dc1dc113"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.6.aar",
          "url": "opmodecontrol-0.0.6.aar",
          "size": 729203,
          "sha512": "be82e385d7913852b626565be26b023f95e83cd6641f8903b6f568344d5945e5d7b5cbd3a232da75d500081cfcfc2aa770f1e13df0615666c4e37c6551caa483",
          "sha256": "4ab034786f0b706eb62281ffb9a4d58bf30842f23e7d375c44f153395d731a24",
          "sha1": "b7233b556c679c9ba5cad5610449e024e0cfcff3",
          "md5": "b29ad797bd7cc18e219091c2dc1dc113"
        }
      ]
    }
  ]
}
