{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "battery",
    "version": "0.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.15.aar",
          "url": "battery-0.0.15.aar",
          "size": 522646,
          "sha512": "05ba6ddb982f154978395b805b30c441f29d3d3b9b76da109648c86579b0d47c8bde4e445a7bfd79197664d97124d9906c3e5a4a01d5e463b49a6121859329aa",
          "sha256": "bbe47c5af844254bd95e781317a505f629dac2800966f40740ac0af9f3289ba2",
          "sha1": "574f15dc90af86d9e4c96d4c8dddc42305f4db3a",
          "md5": "28ddd9a2cd16e1109f99cd6ae968b0ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.15.aar",
          "url": "battery-0.0.15.aar",
          "size": 522646,
          "sha512": "05ba6ddb982f154978395b805b30c441f29d3d3b9b76da109648c86579b0d47c8bde4e445a7bfd79197664d97124d9906c3e5a4a01d5e463b49a6121859329aa",
          "sha256": "bbe47c5af844254bd95e781317a505f629dac2800966f40740ac0af9f3289ba2",
          "sha1": "574f15dc90af86d9e4c96d4c8dddc42305f4db3a",
          "md5": "28ddd9a2cd16e1109f99cd6ae968b0ad"
        }
      ]
    }
  ]
}
