{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "configurables",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.10.aar",
          "url": "configurables-0.0.10.aar",
          "size": 927088,
          "sha512": "3e93f830dc174c28808ebc655cb8e4615bafda835f999ae630d52d0cfd4cd9d938dcc1fe8420a01e74f86385608672e4c4005e63f622e4d5e7b66b550125041e",
          "sha256": "18c2d49efeae545860f70cde93f8471c895fe69ff783731c9cee7627601fa462",
          "sha1": "25ddaa6a958d56a9e7c73d7998df90f444023504",
          "md5": "225df497bf5eacac85488180fe989f51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.10.aar",
          "url": "configurables-0.0.10.aar",
          "size": 927088,
          "sha512": "3e93f830dc174c28808ebc655cb8e4615bafda835f999ae630d52d0cfd4cd9d938dcc1fe8420a01e74f86385608672e4c4005e63f622e4d5e7b66b550125041e",
          "sha256": "18c2d49efeae545860f70cde93f8471c895fe69ff783731c9cee7627601fa462",
          "sha1": "25ddaa6a958d56a9e7c73d7998df90f444023504",
          "md5": "225df497bf5eacac85488180fe989f51"
        }
      ]
    }
  ]
}
