{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "configurables",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.10.aar",
          "url": "configurables-0.0.10.aar",
          "size": 909631,
          "sha512": "4a5fcbdd4cdd6f6d678caf1a5dc75354054154d2c82f8c5be1b4a4c2455a40f276ee5d6bb35703026ca2d33d6ccf88a13ecdf3297df00a5300254e243b16a9e6",
          "sha256": "15bb864d8441df03fba69759937119cfd108e572b8fbb80296230d1cc9a0b1b7",
          "sha1": "4b7d76147c96f96e428565fca88ef0ce2bdfda07",
          "md5": "032e3d4e7ef8c9fbd6bc8373f8fbe152"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.10.aar",
          "url": "configurables-0.0.10.aar",
          "size": 909631,
          "sha512": "4a5fcbdd4cdd6f6d678caf1a5dc75354054154d2c82f8c5be1b4a4c2455a40f276ee5d6bb35703026ca2d33d6ccf88a13ecdf3297df00a5300254e243b16a9e6",
          "sha256": "15bb864d8441df03fba69759937119cfd108e572b8fbb80296230d1cc9a0b1b7",
          "sha1": "4b7d76147c96f96e428565fca88ef0ce2bdfda07",
          "md5": "032e3d4e7ef8c9fbd6bc8373f8fbe152"
        }
      ]
    }
  ]
}
