{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.23.aar",
          "url": "panels-0.0.23.aar",
          "size": 734670,
          "sha512": "cacfd66d145515cf6a4ef49afb030383c46402c34a7135edd41c4bebd0d2dd9c230f7de59f8e03ccff48adfe322a39c46ede68edae36b651be052a0480b65e47",
          "sha256": "b87e15163d32487fd77661f14cedfa37a4db455e1d9ba9ba70cf26534a458e4b",
          "sha1": "ea20272b058ff928d2cee92ad770c635cb588b9e",
          "md5": "4b77e08f24a3a5e5e81c87965dc8c533"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.23.aar",
          "url": "panels-0.0.23.aar",
          "size": 734670,
          "sha512": "cacfd66d145515cf6a4ef49afb030383c46402c34a7135edd41c4bebd0d2dd9c230f7de59f8e03ccff48adfe322a39c46ede68edae36b651be052a0480b65e47",
          "sha256": "b87e15163d32487fd77661f14cedfa37a4db455e1d9ba9ba70cf26534a458e4b",
          "sha1": "ea20272b058ff928d2cee92ad770c635cb588b9e",
          "md5": "4b77e08f24a3a5e5e81c87965dc8c533"
        }
      ]
    }
  ]
}
