{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "configurables",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.9.aar",
          "url": "configurables-0.0.9.aar",
          "size": 171349,
          "sha512": "2ef72cc9c92a933b88689400eda62389da2a36319d24d09080853d014f81bbba23d118da57fec0b91908120fc23fdf480e80be2466849c8670f6005ea5158c1a",
          "sha256": "eeb2bc6596261863588470e2bdf3cc45c0d7333ac761ccb7c14a467ba04ffef4",
          "sha1": "02a853ff93f281b35e34e782191e28b1857a244f",
          "md5": "e03c5b89e1c2283a077a2d5232e4bc53"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.9.aar",
          "url": "configurables-0.0.9.aar",
          "size": 171349,
          "sha512": "2ef72cc9c92a933b88689400eda62389da2a36319d24d09080853d014f81bbba23d118da57fec0b91908120fc23fdf480e80be2466849c8670f6005ea5158c1a",
          "sha256": "eeb2bc6596261863588470e2bdf3cc45c0d7333ac761ccb7c14a467ba04ffef4",
          "sha1": "02a853ff93f281b35e34e782191e28b1857a244f",
          "md5": "e03c5b89e1c2283a077a2d5232e4bc53"
        }
      ]
    }
  ]
}
