{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.24.aar",
          "url": "panels-0.0.24.aar",
          "size": 734743,
          "sha512": "1a6b93f3f49b7a10fb7a2520749398133346d3f07bada39984b88f2224c47ca9054d36045f880200ab8603be22a2214d517e2250671ade4488324a4269571f8b",
          "sha256": "4e94c453033180497d707d01a094a549995c963683dae759da476a4494f032f9",
          "sha1": "4fbb211a6aa1c49b8c0f5b6df9fa8f301c7dec5d",
          "md5": "1b321da041a2df4a200c32ca72095e3c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.24.aar",
          "url": "panels-0.0.24.aar",
          "size": 734743,
          "sha512": "1a6b93f3f49b7a10fb7a2520749398133346d3f07bada39984b88f2224c47ca9054d36045f880200ab8603be22a2214d517e2250671ade4488324a4269571f8b",
          "sha256": "4e94c453033180497d707d01a094a549995c963683dae759da476a4494f032f9",
          "sha1": "4fbb211a6aa1c49b8c0f5b6df9fa8f301c7dec5d",
          "md5": "1b321da041a2df4a200c32ca72095e3c"
        }
      ]
    }
  ]
}
