{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "gamepad",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.11.aar",
          "url": "gamepad-0.0.11.aar",
          "size": 8825746,
          "sha512": "eb382684d89f78949296244f3d128a89880cc11e1d90c06b00456a6794ae3b49e44705e99816b2af94ad30b828706508a0aca4b804689f31d1c5d16dbe7b2ef5",
          "sha256": "967e0b982877cdfb1902ff9899c93f9d92cd707c46f2280924ccdd3e53878540",
          "sha1": "8e8434a576e549cfd283c9fb42e2828494e95552",
          "md5": "4a9fcae10dbc884148117d5824ff9df0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.11.aar",
          "url": "gamepad-0.0.11.aar",
          "size": 8825746,
          "sha512": "eb382684d89f78949296244f3d128a89880cc11e1d90c06b00456a6794ae3b49e44705e99816b2af94ad30b828706508a0aca4b804689f31d1c5d16dbe7b2ef5",
          "sha256": "967e0b982877cdfb1902ff9899c93f9d92cd707c46f2280924ccdd3e53878540",
          "sha1": "8e8434a576e549cfd283c9fb42e2828494e95552",
          "md5": "4a9fcae10dbc884148117d5824ff9df0"
        }
      ]
    }
  ]
}
