{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "gamepad",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.11.aar",
          "url": "gamepad-0.0.11.aar",
          "size": 8487394,
          "sha512": "4907aa9848797fc50bebc45af9de917382e10ad4f377cb637b7267ef54e74fad4c9ba96088b4dca1232e0fc8b4ea7d5e94ad75da3e8bd89e23e5211c71961520",
          "sha256": "d039891361663fd27a2427d88b0156ed5d17cf3d1e0d4903cb185c8e08bb7c84",
          "sha1": "204bb45285c1c9c1e3ca6bdcb9f01628215ebba4",
          "md5": "f7c27ace867709c822e28ec1deef509e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.11.aar",
          "url": "gamepad-0.0.11.aar",
          "size": 8487394,
          "sha512": "4907aa9848797fc50bebc45af9de917382e10ad4f377cb637b7267ef54e74fad4c9ba96088b4dca1232e0fc8b4ea7d5e94ad75da3e8bd89e23e5211c71961520",
          "sha256": "d039891361663fd27a2427d88b0156ed5d17cf3d1e0d4903cb185c8e08bb7c84",
          "sha1": "204bb45285c1c9c1e3ca6bdcb9f01628215ebba4",
          "md5": "f7c27ace867709c822e28ec1deef509e"
        }
      ]
    }
  ]
}
