{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.29.aar",
          "url": "panels-0.0.29.aar",
          "size": 735947,
          "sha512": "8046c64796c35f8e398ac0bcbf9542357de720500d12807c7e88bfc0e7ed0272a460a0d2f8fdecc21bc5c3741008483a29bc54af59147cf26c46c79c23eab27f",
          "sha256": "6f4ad2d70d90f0d1c2681f2d97822df290e23f9e26a4b7579930b8195740d99a",
          "sha1": "34855912d8e7dbff24238ee3fdf5845f1e6fd851",
          "md5": "d627ec8146174083f3aeb26bace5fa6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.29.aar",
          "url": "panels-0.0.29.aar",
          "size": 735947,
          "sha512": "8046c64796c35f8e398ac0bcbf9542357de720500d12807c7e88bfc0e7ed0272a460a0d2f8fdecc21bc5c3741008483a29bc54af59147cf26c46c79c23eab27f",
          "sha256": "6f4ad2d70d90f0d1c2681f2d97822df290e23f9e26a4b7579930b8195740d99a",
          "sha1": "34855912d8e7dbff24238ee3fdf5845f1e6fd851",
          "md5": "d627ec8146174083f3aeb26bace5fa6a"
        }
      ]
    }
  ]
}
