{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "gamepad",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.3.aar",
          "url": "gamepad-0.0.3.aar",
          "size": 2878795,
          "sha512": "5fd5baf47e56e603c0cde018d27afe83731ff60c2291014146d92ad51e4c5080051f9e1d1e65f439b4265312cc6caf12965f45e47c22e93777b8cc77f4390157",
          "sha256": "1771cd15d4693882c530d466e02c3f2d335cbaaf73c589db9eacbebbbc4b7334",
          "sha1": "da13c1aa450c423f437506e984527fd48eddb83c",
          "md5": "f767d67d515384356cfe34add90f339d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.3.aar",
          "url": "gamepad-0.0.3.aar",
          "size": 2878795,
          "sha512": "5fd5baf47e56e603c0cde018d27afe83731ff60c2291014146d92ad51e4c5080051f9e1d1e65f439b4265312cc6caf12965f45e47c22e93777b8cc77f4390157",
          "sha256": "1771cd15d4693882c530d466e02c3f2d335cbaaf73c589db9eacbebbbc4b7334",
          "sha1": "da13c1aa450c423f437506e984527fd48eddb83c",
          "md5": "f767d67d515384356cfe34add90f339d"
        }
      ]
    }
  ]
}
