{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "panels",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.14.aar",
          "url": "panels-0.0.14.aar",
          "size": 284600,
          "sha512": "cc1aeca5e43dfa2f09e28ed1b00f0df2a1ede90d9552943269f49fc91c0e88ac580a182364cb5b7547d8398142fe561fc1819953613e808a8afe1a6ec961ae08",
          "sha256": "770c7fdf53aa8699840acc41f291a4ed435f9625784ee550ea6c682193c33440",
          "sha1": "77d7a40683a1a2e3b042a37682d76452c8fb6284",
          "md5": "4f59ba459a95819ef9f358c1083328a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.14.aar",
          "url": "panels-0.0.14.aar",
          "size": 284600,
          "sha512": "cc1aeca5e43dfa2f09e28ed1b00f0df2a1ede90d9552943269f49fc91c0e88ac580a182364cb5b7547d8398142fe561fc1819953613e808a8afe1a6ec961ae08",
          "sha256": "770c7fdf53aa8699840acc41f291a4ed435f9625784ee550ea6c682193c33440",
          "sha1": "77d7a40683a1a2e3b042a37682d76452c8fb6284",
          "md5": "4f59ba459a95819ef9f358c1083328a4"
        }
      ]
    }
  ]
}
