{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "exampleplugin",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.14.aar",
          "url": "exampleplugin-0.0.14.aar",
          "size": 74725,
          "sha512": "931856777229086c43146ad20178a1f6c0b5fa00e0da6f8819f3aed1641330c1cf53b2d023e0884b9efa37f6d4b8d5141ef0116f6eb4543466f3b5a325f7bda3",
          "sha256": "e186dfbc5aeaf4df356daba8d03e0f5cb2b861c6dd87796a2c1135bd464479a8",
          "sha1": "f930dbb3f5d562dcf39baf663b7f50b7c25b0d31",
          "md5": "d95933811866e3e43974c477c1543cf5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.14.aar",
          "url": "exampleplugin-0.0.14.aar",
          "size": 74725,
          "sha512": "931856777229086c43146ad20178a1f6c0b5fa00e0da6f8819f3aed1641330c1cf53b2d023e0884b9efa37f6d4b8d5141ef0116f6eb4543466f3b5a325f7bda3",
          "sha256": "e186dfbc5aeaf4df356daba8d03e0f5cb2b861c6dd87796a2c1135bd464479a8",
          "sha1": "f930dbb3f5d562dcf39baf663b7f50b7c25b0d31",
          "md5": "d95933811866e3e43974c477c1543cf5"
        }
      ]
    }
  ]
}
