{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "exampleplugin",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.14.aar",
          "url": "exampleplugin-0.0.14.aar",
          "size": 74727,
          "sha512": "b76fde74067f4f349f29c55ace8a57dd4ca31eaa4e74fd8a58c9013beba4cc420d22a37cd76f4e01c26599d5c44fca5159f3152ca9595ec3e841a2e84c2b5512",
          "sha256": "e65c869964ea489db84b38a40608dde5f028134ca79fcdc2baa56fb72fbe1929",
          "sha1": "d4c278df1d6ab7888e78045e08c1d5f953a66e56",
          "md5": "a635ebe58cf4e77798eeead3ac14e468"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.14.aar",
          "url": "exampleplugin-0.0.14.aar",
          "size": 74727,
          "sha512": "b76fde74067f4f349f29c55ace8a57dd4ca31eaa4e74fd8a58c9013beba4cc420d22a37cd76f4e01c26599d5c44fca5159f3152ca9595ec3e841a2e84c2b5512",
          "sha256": "e65c869964ea489db84b38a40608dde5f028134ca79fcdc2baa56fb72fbe1929",
          "sha1": "d4c278df1d6ab7888e78045e08c1d5f953a66e56",
          "md5": "a635ebe58cf4e77798eeead3ac14e468"
        }
      ]
    }
  ]
}
