{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "exampleplugin",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.14.aar",
          "url": "exampleplugin-0.0.14.aar",
          "size": 228715,
          "sha512": "f7c6d00d8a0f2be6ab1ede6e897ab4f7f1ca64b75fd74d1643b4b6524520c440f5aa29a6c519b0e526ff9ad84c09560eb02522ec03d5d6986c31b3ab61a986e1",
          "sha256": "38578c269d7b47bd75a58e05500272cd4368393bbf4561703ef50e16de0fd16a",
          "sha1": "16de80b21a4cd269e34b01a70a27ce1764af6198",
          "md5": "65ce0dba7b5c88a9074a6c4e5b35aaf1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.14.aar",
          "url": "exampleplugin-0.0.14.aar",
          "size": 228715,
          "sha512": "f7c6d00d8a0f2be6ab1ede6e897ab4f7f1ca64b75fd74d1643b4b6524520c440f5aa29a6c519b0e526ff9ad84c09560eb02522ec03d5d6986c31b3ab61a986e1",
          "sha256": "38578c269d7b47bd75a58e05500272cd4368393bbf4561703ef50e16de0fd16a",
          "sha1": "16de80b21a4cd269e34b01a70a27ce1764af6198",
          "md5": "65ce0dba7b5c88a9074a6c4e5b35aaf1"
        }
      ]
    }
  ]
}
