{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bylazar",
    "module": "ftcontrol",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.4.4.aar",
          "url": "ftcontrol-0.4.4.aar",
          "size": 29048418,
          "sha512": "2cc83bc9129a9f8297f85703121b5c2626b9623d03628ab6710c1fd0b055e1fcf05bb3a40040409379e169a9228f9e325ae703f4f50e14cbb910d07ddf845fe0",
          "sha256": "034543880a80a57965e5bdca313364827d90213df33857f9e43407b5f99af4f8",
          "sha1": "495fb54bf864a730890c68281eeb53964df91cde",
          "md5": "5664b9948f93dea632d0cec3d0675f06"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftcontrol-0.4.4.aar",
          "url": "ftcontrol-0.4.4.aar",
          "size": 29048418,
          "sha512": "2cc83bc9129a9f8297f85703121b5c2626b9623d03628ab6710c1fd0b055e1fcf05bb3a40040409379e169a9228f9e325ae703f4f50e14cbb910d07ddf845fe0",
          "sha256": "034543880a80a57965e5bdca313364827d90213df33857f9e43407b5f99af4f8",
          "sha1": "495fb54bf864a730890c68281eeb53964df91cde",
          "md5": "5664b9948f93dea632d0cec3d0675f06"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftcontrol-0.4.4-sources.jar",
          "url": "ftcontrol-0.4.4-sources.jar",
          "size": 87723,
          "sha512": "20d9a6680cb70d9789d90c4b02b36363a010ed76670dfdff53ef8994d48967b6496e62535c68cd05f10e2e64dd1de0989b007fd180da6ed067e8faadcb555e39",
          "sha256": "f0109922854a986a81863ee0b9d6b5f006653372407a93aa7184fce910fa4d43",
          "sha1": "e6ded8d31625d2faa1b16e1096f684b0f57720af",
          "md5": "7d3d156ccd8d08355a9f4c760af56f4a"
        }
      ]
    }
  ]
}
